### ISSUE TITLE
Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent

### ISSUE THREAD

**Issue by garrett-gottlieb** [expo/expo-cli#4594] opened 2022-11-03 21:11 UTC
### Summary

When I run `expo run:android` I see the following error:
```
› Opening com.myapp://expo-development-client/?url=http%3A%2F%2F192.168.50.133%3A8081 on Pixel_6_API_33
Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=com.myapp://expo-development-client/... flg=0x10000000 }
```

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.4
      Shell: 3.0.2 - /usr/local/bin/fish
    Binaries:
      Node: 14.19.1 - /usr/local/bin/node
      Yarn: 1.22.5 - ~/.yarn/bin/yarn
      npm: 6.14.16 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 30, 31, 32, 33
        Build Tools: 29.0.2, 30.0.2, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-33 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: 44.0.6 => 44.0.6
      react-native: 0.64.3 => 0.64.3
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Android Pixel 6 API 33 Emulator (as well as Pixel 4 API 30 Emulator)

### Error output

/Users/me/Library/Android/sdk/platform-tools/adb devices -l
/Users/me/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu avd name
/Users/me/Library/Android/sdk/platform-tools/adb devices -l
/Users/me/Library/Android/sdk/platform-tools/adb -s emulator-5554 emu avd name
› Opening com.myapp://expo-development-client/?url=http%3A%2F%2F192.168.50.133%3A8081 on Pixel_6_API_33
/Users/me/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell pm list packages com.myapp
/Users/me/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.VIEW -d com.myapp://expo-development-client/?url=http%3A%2F%2F192.168.50.133%3A8081
Couldn't start project on Android: Error running adb: Error running app. Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=com.myapp://expo-development-client/... flg=0x10000000 }

### Reproducible demo or steps to reproduce from a blank project

1. Create bare Expo 44 project
2. Download Android Studio and all tools, set up environment and emulator
3. Run `expo run:android`

**Comment by brentvatne** [comment] 2022-11-03 21:36
it looks like the app may have failed to install. are you able to find it and launch it manually?

also, as the issue template suggests we require that you try to reproduce issues against the latest sdk version, so i will close this issue - happy to reopen if you can reproduce with sdk 46 or 47 beta

**Closed by brentvatne** 2022-11-03 21:36 UTC
Labels: needs review
