### ISSUE TITLE
Xcode 10: Command PhaseScriptExecution failed with NVM

### ISSUE THREAD

**Issue by pieterbeulque** [expo/expo-cli#43] opened 2018-09-24 12:28 UTC
## Description

I have expo-cli installed globally through NPM (that is installed on my system using `nvm`).
I ejected Expo to install Cocoapods depedendencies for Expo GL (EXGL).

## Expected Behavior

Run Xcode Build and get a compiled app.

## Observed Behavior

Xcode build fails.

```
Please install expo-cli command
Command PhaseScriptExecution failed with a nonzero exit code
```

## Environment

Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.8.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: Xcode 10.0 Build version 10A255
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/pieterbeulque-768c02ed-a08c-4951-9f56-e887077ab919.tar.gz

Also specify:

* Phone/emulator/simulator platform, model and version:

xCode 10.0 with any simulator.

**Comment by pieterbeulque** [comment] 2018-09-24 13:44
It works if I edit the _Prepare Expo_ Build Phase in Xcode to:

```expocommand="/Users/pieterbeulque/.nvm/versions/node/v10.8.0/bin/expo"```

**Comment by esamelson** [comment] 2018-09-27 23:07
Hi @pieterbeulque - thanks for the report. I believe we're working on finding a more sustainable solution for this. In the meantime your workaround should work just fine.

**Comment by esamelson** [comment] 2018-09-28 00:10
Going to close this as a duplicate of https://github.com/expo/expo/issues/2301 since the relevant code is in the expo/expo repo, not this one.

**Closed by esamelson** 2018-09-28 00:10 UTC

**Comment by mrchauhan2802** [comment] 2018-10-26 14:15
> It works if I edit the _Prepare Expo_ Build Phase in Xcode to:
> 
> `expocommand="/Users/pieterbeulque/.nvm/versions/node/v10.8.0/bin/expo"`

What you change and how you open it to edit 

i have same issue
