### ISSUE TITLE
Invariant violation: "main: has not been registered.

### ISSUE THREAD

**Issue by SPineapple** [expo/expo-cli#2670] opened 2020-09-19 15:21 UTC
## Description

I wanted to try the release-channel, I thought somehow its same as switching channels in flutter, and its my fault that I didn't read the document enough to understand. Now that I know the purpose of it after I actually did publish it in privacy of "unlisted" , and found the project in my account, and afterwards I did deleted the channel because my app wasn't ready. Now going back to run the app locally, I keep having an error about _AppRegistery.registerComponent_.
This is the first time I went so far on dealing a pre-published app,  so I don't know how exactly the process works...

## Expected Behavior

I deleted the release-channel from my account , I expected everything would work fine- normally.

I also followed to add this:
`registerRootComponent(App);`
https://docs.expo.io/versions/latest/sdk/register-root-component/

But that didn't solve the issue.

## Observed Behavior

<img width="374" alt="Screen Shot 2020-09-19 at 6 09 36 PM" src="https://user-images.githubusercontent.com/18646285/93670323-499f2080-faa3-11ea-98b4-6997451c5a5b.png">

## Environment

Expo CLI 3.27.6 environment info:
    System:
      OS: macOS 10.15.6
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 14.4.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    Managers:
      CocoaPods: 1.9.3 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ^38.0.0 => 38.0.10 
      react: 16.11.0 => 16.11.0 
      react-dom: 16.11.0 => 16.11.0 
      react-native: 0.62.2 => 0.62.2 
      react-native-web: ~0.11.7 => 0.11.7 
    Expo Workflow: bare

## Reproducible Demo

publish a release channel, delete it from your account through expo website, then run the app.

**Comment by brentvatne** [comment] 2020-09-19 21:26
publishing to a release channel won't have anything to do with your local development environment. if you are seeing this locally it could be due to any number of issues as it's a fairly generic error, sadly. try reverting to your last known working commit and bisecting. if you can provide a mcve (https://stackoverflow.com/help/mcve) we can help investigate, post to the forums and link me to it from here. closing this issue because it's not a bug report.

**Closed by brentvatne** 2020-09-19 21:26 UTC
