### ISSUE TITLE
Error publish project to EXPO

### ISSUE THREAD

**Issue by alexalannunes** [expo/expo-cli#1173] opened 2019-11-02 23:08 UTC
### Hi. I'm trying to run `expo publish` via web expo but I got this error:
![aaaaaaaaa](https://user-images.githubusercontent.com/16847836/68077925-5cd1d080-fdab-11e9-87c3-aadea1d2ae7a.png)
------------------------
### Then, I rode `expo publish` via terminal with `EXPO_DEBUG=true` and a got this:
![msmsmsmsm](https://user-images.githubusercontent.com/16847836/68077941-c8b43900-fdab-11e9-969f-0e62d483a0c4.png)

------------------------
## Expo Diagnostics
```log
Expo CLI 3.4.1 environment info:
    System:
      OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
      Shell: 4.3.48 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.11.3 - ~/.npm-global/bin/npm
    npmPackages:
      expo: ^35.0.0 => 35.0.0 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.0 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.4.1
```
----------------------------
## My `app.json` file
```json
{
  "expo": {
    "name": "picpay",
    "slug": "picpay",
    "owner": "Alex Alan Nunes",
    "privacy": "public",
    "sdkVersion": "35.0.0",
    "platforms": [
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "primaryColor": "#1D1E20",
    "scheme": "picpay+me",
    "androidStatusBar": {
      "barStyle": "light-content",
      "backgroundColor": "#1D1E20"
    },
    "splash": {
      "resizeMode": "contain",
      "backgroundColor": "#11C76F"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "description": ""
  }
}
```

----------------------------

## My `package.json` file
```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject",
    "test": "jest --watchAll"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/samples": "~3.0.3",
    "@expo/vector-icons": "^10.0.3",
    "axios": "^0.19.0",
    "expo": "^35.0.0",
    "expo-asset": "^7.0.0",
    "expo-constants": "^7.0.0",
    "expo-font": "^7.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-navigation": "^3.12.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^7.0.0",
    "jest-expo": "^35.0.0"
  },
  "private": true
}
```

**Comment by alexalannunes** [comment] 2019-11-13 13:38
????

**Comment by ccheever** [comment] 2019-11-14 08:10
HI-
It's possible this was an intermittent network failure or something. Did you try republishing?
Also, does your project run fine when you are working on it locally? And just fails when you publish?

**Comment by alexalannunes** [comment] 2019-11-14 17:31
Hi @ccheever 
Yes, I tried to republish it, but I got the same error.
And it run fine locally! :(

**Comment by jhenrich** [comment] 2019-11-22 11:13
Do you have an .expo folder in your project? Delete it and try again

**Comment by brentvatne** [comment] 2019-11-26 00:19
@jhenrich's suggestion is good - try that and also try `expo logout` and `expo login`. it's possible that there was an intermittent network issue at the time as @ccheever suggested as well.

if the issue persists please let me know that you have tried the above and i will reopen the issue. i cannot reproduce it on my end and others are not reporting it so i'll close this.

**Closed by brentvatne** 2019-11-26 00:19 UTC
