### ISSUE TITLE
[Web] babel-preset-expo's current config strips out property decorators

### ISSUE THREAD

**Issue by bayoremit** [expo/expo-cli#788] opened 2019-06-28 16:34 UTC
## Description

Property decorators on web builds don't work.
E.g:
```ts
@SomeClassDecorator()
export SomeClass {

    @SomePropDecorator()
    public someProp: string;

    ....
}
```

`SomeClassDecorator` works as expected but `SomePropDecorator` doesn't. This makes modules like `class-transformer` fail on web builds.

## Expected Behavior

Expected both class and property decorators should work (are emitted).

## Observed Behavior

Only class decorators are emitted, the property ones fail silently as they are stripped during babel's compilation

## Environment

```
  Expo CLI 2.21.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.19 => 16.8.19 
      @types/react-native: ^0.57.60 => 0.57.60 
      expo: ^33.0.7 => 33.0.7 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 2.21.1
```

Also specify:

- This is for Expo Web
- I am using Typescript

## Reproducible Demo

Create a project using `class-transformer` and try using it.

## Extra

After investigating, the problem is in babel-preset-expo located in expo-cli's `node_modules`. Moving `plugin-proposal-decorators` before `plugin-transform-flow-strip-types` solves the issue. My guess is `plugin-transform-flow-strip-types` is somehow discarding property decorators.

```js
  const defaultPlugins = [
    [
      'babel-plugin-module-resolver',
      {
        alias: {
          'react-native-vector-icons': '@expo/vector-icons',
        },
      },
    ],
    // proposal-decorator must go BEFORE flow strip types or it strips property decorators which breaks typescript
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    // the flow strip types plugin must go BEFORE class properties!
    ['@babel/plugin-transform-flow-strip-types'],
    [
      '@babel/plugin-proposal-class-properties',
      // use `this.foo = bar` instead of `this.defineProperty('foo', ...)`
      { loose: true },
    ],
    ['@babel/plugin-syntax-dynamic-import'],
    ['@babel/plugin-transform-react-jsx'],
    ['babel-plugin-react-native-web'],
  ];
```

**NOTES**:
* There is another `babel-preset-expo` located in the active project's `node_modules` folder which I notice also gets called and runs. Making the changes above in the local doesn't work. Expo-cli's version seems to be the one that matters even though they both run.
* Making certain changes to the local one works, but not the decorator change.
* Leaving the plugin order untouched in the local one is ok for some reason. As long as the CLI one is updated, property decorators will work.

Could someone pls explain:
* Why we have two of `babel-preset-expo`?
* Why they both run?
* How they play with each other?
* Why does the CLI one seem to matter for this change

Thanks!

**Comment by ide** [comment] 2019-06-28 19:13
If you can answer the questions at the end of your post, that's probably one of the most helpful ways to make progress on this issue (and other issues in general; when you can identify the root cause that unlocks progress).

**Comment by bayoremit** [comment] 2019-06-29 01:57
Hi ide

Do you mean the 4 questions at the end of the bug report or some questions I missed in the bug report template.  If you meant the 4 at the end of the post, I have no idea where to start, that's why I am reaching out to the community. I assumed it's an expo design choice. One that confuses me.

Could the dual `babel-preset-expo` be a result of my setup falling into a bad state?

If there is any more info I can provide or want me to try something to help figure out what's going on, pls let me know

Thanks

**Comment by ide** [comment] 2019-07-01 07:05
I mean the four questions at the end of your post. I suspect answering those will lead to the root cause.

**Comment by bayoremit** [comment] 2019-07-01 19:02
Ah got it. Sorry for the confusion on my part. Indeed, I think they will definitely shed some light on whats going on. I left my environment as is incase I need to provide more information to help y'all get to the bottom of this.

**Comment by bayoremit** [comment] 2019-07-24 21:02
Anything I can do to help move this forward?

**Comment by EvanBacon** [comment] 2019-07-25 18:27
Fixed with https://github.com/expo/expo/pull/5012

**Comment by EvanBacon** [comment] 2019-07-25 18:28
We also added tests to ensure the code works as expected across platforms: https://github.com/expo/expo/blob/6733239953132d74c2469045fad6c946432eabd8/packages/babel-preset-expo/__tests__/index-test.js

**Closed by EvanBacon** 2019-07-25 18:27 UTC
