### ISSUE TITLE
expo-cli [4.2.1] - Stopping serverError: spawn pgrep EAGAIN

### ISSUE THREAD

**Issue by FrederickEngelhardt** [expo/expo-cli#3262] opened 2021-02-26 17:38 UTC
**Summary**

The spawn pgrep EAGAIN error has not gone away when running the expo server using `expo start` or `EXPO_USE_DEV_SERVER=true expo start` on latest 4.2.1 expo-cli.

This error has been around to me since **06/2018**. Curious if people are still running into this error when running expo services.

Another place you can encounter this error is running `expo upgrade`. If expo fails to upgrade it attempts to clear the cache and the same output occurs.

**Environment**

  Expo CLI 4.2.1 environment info:
    System:
      OS: macOS 10.15.7
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.20.1 - /var/folders/nn/pf3r3x090wg4ydmr7bjtx1yw0000gn/T/fnm_multishell_20488_1614359855321/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 6.14.11 - /var/folders/nn/pf3r3x090wg4ydmr7bjtx1yw0000gn/T/fnm_multishell_20488_1614359855321/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.1 - /Users/frederickengelhardt/.rbenv/shims/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    IDEs:
      Xcode: 12.4/12D4e - /usr/bin/xcodebuild
    npmPackages:
      expo: ^40.0.1 => 40.0.1
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz => 0.63.2
    npmGlobalPackages:
      expo-cli: 4.2.1
    Expo Workflow: managed

**Please specify your device/emulator/simulator platform, model and version**

n/a

**Error output**

⠹ Stopping serverError: spawn pgrep EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Reproducible demo or steps to reproduce from a blank project**

It should be as simple as running (accepting any template)
```
expo init my-app
echo '{
  "packagerPort": 19000,
  "packagerPid": 88479,
  "devToolsPort": 19002,
  "expoServerPort": 19000
}' > ./.expo/packager-info.json
expo start
```

Then in your terminal cancel the process with CTRL+C. Expo will hang and crash with `Stopping serverError: spawn pgrep EAGAIN` error

## Related Older Issues
#1596 
#1852

**Comment by FrederickEngelhardt** [comment] 2021-02-26 17:46
The above issue was submitted because it's still valid on some older projects. I resolve it by replacing the following in the `.expo/` folder (which should not have commits besides initial project creation)

Config that broke:

**.expo/package-info.json**
```json
{
  "packagerPort": 19000,
  "packagerPid": 88479,
  "devToolsPort": 19002,
  "expoServerPort": 19000
}
```

Replace with
**.expo/package-info.json**
```json
{
  "devToolsPort": 19003,
  "expoServerPort": null,
  "packagerPort": 19000
}
```

This error has been all of my expo projects. Perhaps the upgrade process should commit the new `.expo` folder settings so that older projects are fixed.

@brentvatne any reason why the above settings would break?

**Comment by brentvatne** [comment] 2021-02-26 17:59
hi @FrederickEngelhardt! I copied your repro steps and did not see the error that you described above. we could clear the `.expo/packager-info.json` file on upgrade but i'd rather understand why this isn't working and fix the underlying issue. given that you're able to reproduce this on your machine, could you try cloning the expo-cli repo and digging in to the code to get a better understanding of the problem?

**Comment by brentvatne** [comment] 2021-03-22 04:00
closing because no follow up from poster

**Closed by brentvatne** 2021-03-22 04:00 UTC
Labels: bug

**Comment by raphaelpra** [comment] 2021-12-23 13:31
I don't if it help, but I have the same issue (only on `expo upgrade`).

After a little bit of digging, I found that it crashes on the line 

```js
// build/commands/info/upgradeAsync.js
 await _xdl().Project.startReactNativeServerAsync({                                         
      projectRoot,                                                                             
      options: {                                                                               
        reset: true,                                                                           
        nonPersistent: true                                                                    
      }                                                                                        
    })
```
(using expo-cli 5.0.3)

I could dig further, but I need some directions.
