### ISSUE TITLE
Error While QR Code Scanning through Expo App - Android

### ISSUE THREAD

**Issue by GK2112** [expo/expo-cli#4053] opened 2021-12-07 09:53 UTC
### Summary

While Scanning QR Code in Android APP "Expo" - error occurred in compiler as below

Logs for your project will appear below. Press Ctrl+C to exit.
Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at stableHash (C:\Users\gaurav.kalamkar\NEW_Design_1View\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (C:\Users\gaurav.kalamkar\NEW_Design_1View\node_modules\metro-transform-worker\src\index.js:647:7)
    at getTransformCacheKey (C:\Users\gaurav.kalamkar\NEW_Design_1View\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:32:19)
    at new Transformer (C:\Users\gaurav.kalamkar\NEW_Design_1View\node_modules\metro\src\DeltaBundler\Transformer.js:180:28)
    at C:\Users\gaurav.kalamkar\NEW_Design_1View\node_modules\metro\src\Bundler.js:58:29
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processTimers (node:internal/timers:497:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
Android Bundling failed 31ms
Cannot read properties of undefined (reading 'transform file)
Android Bundling failed 10ms
Cannot read properties of undefined (reading 'transform file)

### Environment

  Expo CLI 4.13.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 17.2.0 - C:\Program Files\nodejs\node.EXE
      npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
    npmPackages:
      expo: ~43.0.2 => 43.0.3
      react: 17.0.1 => 17.0.1
      react-dom: 17.0.1 => 17.0.1
      react-native: 0.64.3 => 0.64.3
      react-native-web: 0.17.1 => 0.17.1
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

Samsung M40

### Reproducible demo or steps to reproduce from a blank project

Yes -

**Comment by brentvatne** [comment] 2021-12-14 23:32
it seems that you can work around this for now by using node 16 - https://stackoverflow.com/a/70253732/659988

**Comment by brentvatne** [comment] 2021-12-14 23:33
also, duplicate of https://github.com/expo/expo-cli/issues/4037

**Closed by brentvatne** 2021-12-14 23:33 UTC
Labels: bug
