### ISSUE TITLE
Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

### ISSUE THREAD

**Issue by saulamsal** [expo/expo-cli#4532] opened 2022-08-27 05:56 UTC
### Summary

Not exactly sure what may be causing the issue, as it was working just fine few days back. 
Looking at the EAS CLI console, it states that 
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 executed
Unable to list file systems to check whether they can be watched. The whole state of the virtual file system has been discarded. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory)
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.

```

### Environment

```
expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 11.6.2
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^45.0.0 => 45.0.5 
      react: 17.0.2 => 17.0.2 
      react-dom: 17.0.2 => 17.0.2 
      react-native: 0.68.2 => 0.68.2 
      react-native-web: 0.17.7 => 0.17.7 
    npmGlobalPackages:
      eas-cli: 1.1.1
      expo-cli: 5.4.12
    Expo Workflow: managed
```

### Please specify your device/emulator/simulator platform, model and version

N/A

### Reproducible demo or steps to reproduce from a blank project

N/A

**Comment by brentvatne** [comment] 2022-08-27 06:02
can you share a link to the page with those build logs?

**Comment by EvanBacon** [comment] 2022-10-27 22:36
Closing as I could not reproduce this issue and we couldn't get more information. If you believe the issue is still relevant, please reopen in https://github.com/expo/eas-cli with a minimum reproducible example.

**Closed by EvanBacon** 2022-10-27 22:36 UTC
Labels: needs review
