### ISSUE TITLE
Don't show "Using node to generate images. This is much slower than using native packages." message when ejecting

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#2878] opened 2020-11-13 02:51 UTC
![Screen Shot 2020-11-12 at 6 49 09 PM](https://user-images.githubusercontent.com/90494/99022640-f6cc6d00-2517-11eb-882d-5379ec415025.png)

I think people won't and probably shouldn't stop ejecting for this. We don't process many assets when ejecting so this should be relatively fast, especially compared to other steps like installing node modules and CocoaPods.

**Comment by EvanBacon** [comment] 2020-11-16 15:29
duplicate of your own issue https://github.com/expo/expo-cli/issues/2676

**Closed by EvanBacon** 2020-11-16 15:29 UTC

**Comment by brentvatne** [comment] 2020-11-17 00:44
😆
