### ISSUE TITLE
[v4.7.2] No more option to create bare project with typescript ?

### ISSUE THREAD

**Issue by kytosai** [expo/expo-cli#3632] opened 2021-07-04 09:54 UTC
I just updated from expo-cli from v4.5.2 to v4.7.2

When I create a new project with the "bare" option I no longer see the option to create a new bare project with typescript. Has this option been removed?

How can I create a bare typescript project with expo ?

![alt](https://i0.wp.com/s1.uphinh.org/2021/07/04/Screen-Shot-2021-07-04-at-16.54.56.jpg)

**Comment by EvanBacon** [comment] 2021-07-05 23:08
Duplicate of https://github.com/expo/expo-cli/issues/3623 -- add typescript by creating a TS file and running expo start https://docs.expo.io/guides/typescript/

**Closed by EvanBacon** 2021-07-05 23:08 UTC
