### ISSUE TITLE
Where is index.js?

### ISSUE THREAD

**Issue by i-schuetz** [expo/expo-cli#363] opened 2019-02-10 14:15 UTC
I'm having the issue described here: https://github.com/react-community/create-react-native-app/issues/771

Creating index.js as described in the comments doesn't help. Still complains about missing index.js. I confirmed that my index.js is exactly in the path shown in the error message.

Note: Using Typescript. It's maybe relevant.

**Comment by fson** [comment] 2019-02-19 17:43
This seems to be a bug with the `plain` eject. We're working on improvements to this command and that will include a fix to this bug.

As a workaround, you can create an `index.js` file with following contents:
```
import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
```

**Comment by fson** [comment] 2019-02-19 17:44
Duplicate of #107

**Closed by fson** 2019-02-19 17:44 UTC
Labels: bug

**Comment by jendang** [comment] 2019-03-16 20:39
I tried to create index.js in like about and also want to wrap the <App/> in <Provider> to be able to use with Redux but it does not work . Here is the error: 

Invariant Violation: Could not find "store" in the context of "Connect(App)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(App) in connect options.

Here is my code in index.js

import React from 'react';
import { AppRegistry } from 'react-native';
import App from './App';
import { Provider } from 'react-redux'
import { name as appName } from './app.json';
import configureStore from './src/store/configureStore'

const store = configureStore()

const RNRedux = () => {
    <Provider store={store}>
        <App/>
    </Provider>

}

AppRegistry.registerComponent(appName, () => RNRedux);

**Comment by SemihKoc** [comment] 2019-08-29 10:29
You should define index.js as main in package.json

{
  "main": "index.js",
}

instead 

{
 "main": "node_modules/expo/AppEntry.js"
}
