### ISSUE TITLE
"sourceExts" in the Metro config are ignored

### ISSUE THREAD

**Issue by zyxel648** [expo/expo-cli#1019] opened 2019-08-05 14:26 UTC
### Environment
  Expo CLI 3.0.8 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
Android, Expo Client v.2.12.0

```
npm list -g --depth=0

+-- @vue/cli@3.9.3
+-- @vue/cli-init@3.9.0
+-- create-react-native-app@2.0.2
+-- exp@57.2.1
+-- expo-cli@3.0.8
+-- npm@6.10.0
+-- react-native-cli@2.0.1
+-- vue-native-cli@0.1.0
+-- webpack@4.29.6
`-- webpack-cli@3.3.0

```
package.json

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^34.0.1",
    "react": "16.8.3",
    "react-dom": "^16.8.6",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-web": "^0.11.4",
    "vue-native-core": "^0.1.0",
    "vue-native-helper": "^0.1.0",
    "vue-native-scripts": "0.0.16"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-preset-expo": "^6.0.0"
  },
  "private": true
}
```

`metro.config.js`

```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  const {
    resolver: { sourceExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve("./vueTransformerPlugin.js"),
      getTransformOptions: async () => ({
        transform: {
          experimentalImportSupport: false,
          inlineRequires: false,
        },
      })
    },
    resolver: {
      sourceExts: [...sourceExts, "vue"]
    }
  };
})();
```

### Steps to Reproduce
Download [Repository](https://github.com/zyxel648/vue-native-sample)

1. run `npm install`
2. run `npm start`
3. open in expo client on Android

### Expected Behavior

Expected to see label "My Vue Native App"

### Actual Behavior

Error:
![image](https://user-images.githubusercontent.com/2689644/62469948-f9cba000-b7a1-11e9-9982-7f2b1d8e240b.png)

In stack trace I see: 
```
The module '../../App' could not be found from 'C:\\sample\\node_moudules\\expo\\AppEntry.js'. Indead, none of these files exist:
* 'C:\\sample\\App(.native||.android.expo.js|.native.expo.js|.expo.js|.android.expo.ts|.native.expo.ts|.expo.ts|.android.expo.tsx|.native.expo.tsx|.expo.tsx|.android.expo.json|.native.expo.json|.expo.json|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx
```

But why it's don't try to resolve module with `vue` extension (see metro.config.js)? I mean, module is located in `App.vue` file, and in `metro.config.js` resolver contains 'vue' extension, but it's not used for resolving modules.

If I add App.js, and inside it try to import something like `import MyApp from "./App.vue'`, I would get almost the same error (_The module 'App' could not be found from ..._), because resolver don't try to use `vue` extension.

I spent about 3 days trying to solve this issue, but nothing found how to do this.

### Reproducible Demo
using vue-native-cli create new project:
`vue-native init <project name>`
`npm install vue-native-scripts`
`npm install @babel/core@7.0.0`
And then, delete App.js file (App.vue file still exists)

Or get sample code from [Repository](https://github.com/zyxel648/vue-native-sample)

**Comment by ide** [comment] 2019-09-23 18:35
Any help finding the root cause would be appreciated.

**Comment by fson** [comment] 2019-11-08 15:00
There's currently no good way for us to provide default values for Metro configuration values, other than passing them as command-line arguments to the React Native CLI, which unfortunately means they take precedence over the values in `metro.config.js`.

As a workaround, you could add `{ "expo": { "packagerOpts": { "sourceExts": ["vue"] } } }` to your `app.json` file. Unlike the `metro.config.js` values, these options are merged with the defaults provided by Expo CLI.

**Comment by ide** [comment] 2019-11-09 01:10
You may also need to specify the path to your metro.config.js file in app.json (I forget the specifics, IIRC it's in packagerOpts, look at the source code). Ex: debug to see whether/when your Metro config is loaded.

**Comment by Macilias** [comment] 2019-11-19 11:03
It's a pity, that there is no documentation for what ever reason the metro.config.js is clearly ignored. 
I declared the moule to use ONLY my custom extensions metro.config.js like: 
```
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: [
    './src/assets/icons',
    './src/assets/svg',
    './src/assets/ai',
  ],
  assetExts: [
    '.xml', ".png", ".jpg", ".pb", ".tflite"
  ]
};
```
and the message is still the same:
```
error: bundling failed: Error: Unable to resolve module `./ai/annotations/Part1.xml` from `...src/assets/default-assets.js`: The module `./ai/annotations/Part1.xml` could not be found from `.../src/assets/default-assets.js`. Indeed, none of these files exist:
  * `.../src/assets/ai/annotations/Part1.xml(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
```

Its starting to make making crazy...
How coult it be so hard to use custom assets within an application?

**Comment by fson** [comment] 2019-11-19 13:41
**Currently the `assetExts` and `sourceExts` settings (for managed apps) can not be specified in `metro.config.js`.**

To use custom asset or source extensions in your managed application, you can specify them in `app.json` using `packagerOpts` instead:
```json
{
  "expo": {
    "packagerOpts": {
      "assetExts": ["ttf"],
      "sourceExts": [
        "expo.ts", "expo.tsx",
        "expo.js", "expo.jsx",
        "ts", "tsx",
        "js", "jsx",
        "json", "wasm"
      ]
    }
  }
}
```

**Comment by Macilias** [comment] 2019-11-19 14:58
thanks, but your suggestion does not work either. Please consider the commit: 
`fson's suggestion to use app.json - failing the same way`
on this extra created github repo: https://github.com/Macilias/ReactNativeAssetFail

The fail looks exactly the same:
```
error: bundling failed: Error: Unable to resolve module `./ai/annotations/SomeFile.xml` from `src/assets/default-assets.js`: 

None of these files exist:
  * src/assets/ai/annotations/SomeFile.xml(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * src/assets/ai/annotations/SomeFile.xml/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)

```

And what is the difference between **assetExts** and **sourceExts**?

**Comment by Macilias** [comment] 2019-11-21 10:52
Update, I managed to get rid of the error by pointing to metro.config.js from app.json like this:
```
{
  "name": "reactNativeTestapp",
  "displayName": "reactNativeTestapp",
  "packagerOpts": {
    "config": "metro.config.js"
  }
}
```

and the content of the metro.config.js looks like this:
```
const {getDefaultConfig} = require('metro-config');

module.exports = (async () => {
  const {
    resolver: {sourceExts, assetExts},
  } = await getDefaultConfig();
  return {
    resolver: {
      assetExts: [assetExts, 'txt', 'xml', 'png', 'jpg', 'pb', 'tflite'],
      sourceExts: [...sourceExts, 'txt', 'xml', 'png', 'jpg', 'pb', 'tflite'],
    },
  };
})();
```

how ever the content of the xml file is not shown in the form App.js, it only prints a number maybe corresponding to the number of lines?! But how can I actually access the content of the file?

**Comment by ide** [comment] 2019-11-22 20:08
The number is perhaps Metro's internal module ID. IIRC Metro had some special-casing around .json and .txt extensions. It needs some kind of heuristic to know that it should give you a string for a .txt file and an image descriptor object for a .png file. I'd try renaming your .xml file to .txt or looking at the Metro source code for the source of truth.

**Comment by brentvatne** [comment] 2019-12-08 06:47
what @ide says sounds right to me. `json` is a special case in the react-native packager and the contents are inlined, but every other asset resolves to a number that is registered with the react-native asset registry. the image component and video component and other things know how to take this module id and get the underlying asset from it, and you'll need to do something similar to get the contents of the xml file.

- use this to an asset and called downloadAsync on it, then get the localUri https://docs.expo.io/versions/v35.0.0/sdk/asset/#assetfrommodulemodule
- after that you can read it from filesystem https://docs.expo.io/versions/v35.0.0/sdk/filesystem/#filesystemreadasstringasyncfileuri-options

we should document using metro config in expo-cli, will create a new issue for that

**Closed by brentvatne** 2019-12-08 06:47 UTC

**Comment by pgte** [comment] 2020-01-31 18:49
Is this issue solved on the latest release of `expo` (36.0.0)?

**Comment by pgte** [comment] 2020-01-31 18:50
I'm using expo 36.0.0 and I'm using `expo.packagerOpts.assetExts`, but they're not reaching metro.

**Comment by patrickjm** [comment] 2020-03-17 13:51
> There's currently no good way for us to provide default values for Metro configuration values, other than passing them as command-line arguments to the React Native CLI, which unfortunately means they take precedence over the values in metro.config.js.

@fson Maybe Expo could provide a base config repo like [@expo/webpack-config](https://www.npmjs.com/package/@expo/webpack-config)?

**Comment by brentvatne** [comment] 2020-03-18 18:25
@patrickjm - that seems pretty reasonable!

**Comment by sajith-eashwar** [comment] 2023-07-07 12:31
![image](https://github.com/expo/expo-cli/assets/60972764/9f45d0e8-447b-4fa7-8294-5889bf165cbd)

getting error
