### ISSUE TITLE
Expo projects not compiling due to Metro's package-json

### ISSUE THREAD

**Issue by joshiatharva** [expo/expo-cli#2356] opened 2020-07-14 18:12 UTC
## Description

Had a problem compiling projects in Expo -  it keeps loading an error concerning Metro's package.json. The problem has also presented itself whenever I try to load a freshly created project. See the command line screenshot below (a new project called "my-app" is made, attempting to load produces the following error).

## Expected Behavior

Apps should load and produce the QR code before displaying any errors.

## Observed Behavior
Had a problem compiling projects in managed Expo flow that kept loading an error concerning Metro's package.json. The problem has also presented itself whenever I try to load a freshly created project. See the command line screenshot below (a new project called "default" is made, attempting to load produces the following error).

```
error Error parsing C:\Users\Atharva\default\node_modules\metro\package.json: Unexpected token   in JSON at position 510.

SyntaxError: Error parsing C:\Users\Atharva\default\node_modules\metro\package.json: Unexpected token   in JSON at position 510
    at parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:263:20)
    at readPackageExports (internal/modules/cjs/loader.js:303:15)
    at applyExports (internal/modules/cjs/loader.js:444:20)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
Metro Bundler process exited with code 1
Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (C:\@expo\xdl@57.9.22\src\Project.ts:1857:16)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

## Environment

OS: Windows 10
Phone: iPhone SE
Expo-CLI: 3.22.1
SDK Version: 38.0.0
Both have just been installed with node (version 12.18.2)

## Reproducible Demo

![screenshot](https://user-images.githubusercontent.com/44905452/87461109-d7731100-c605-11ea-9ffa-33a4a71abde3.png)

Metro's package.json is shown below - for some reason the installed file ends prematurely:

![screenshot](https://user-images.githubusercontent.com/44905452/87461533-7c8de980-c606-11ea-82a1-98c870924111.png)

**Comment by brentvatne** [comment] 2020-07-15 00:21
hello! it seems like something is wrong with the installation from npm. perhaps the download terminated before it was completed. certainly strange that there wasn't some other error from npm to warn you of this. you should delete your node_modules, delete the npm cache `npm cache clean --force` and run `npm install` again

if the issue persists, i'd suggest switching to [yarn classic](https://classic.yarnpkg.com/lang/en/) as your package manager.

closing this issue because the error message we provide seems to be reasonable given the cause

**Closed by brentvatne** 2020-07-15 00:21 UTC
