### ISSUE TITLE
expo start : Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?

### ISSUE THREAD

**Issue by LeDoudou** [expo/expo-cli#38] opened 2018-09-17 13:50 UTC
Hi, I try to make an expo projet but I always have the error.
Here is the list of command : 

1. yarn global add expo-cli
2. expo init
3. cd testexpo / expo start 

But i always reach this error : "Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?"

**Below the complete command/response :** 

➜  test **yarn global add expo-cli**
yarn global v1.9.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info @expo/ngrok-bin-darwin-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info "@expo/ngrok-bin-darwin-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-freebsd-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-freebsd-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-freebsd-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-arm64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-arm64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-arm64@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-ia32@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-ia32@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-linux-ia32@2.2.8: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-linux-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-linux-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-sunos-x64@2.2.8: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-sunos-x64@2.2.8" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-win32-ia32@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/ngrok-bin-win32-ia32@2.2.8-beta.1: The CPU architecture "x64" is incompatible with this module.
info @expo/ngrok-bin-win32-x64@2.2.8-beta.1: The platform "darwin" is incompatible with this module.
info "@expo/ngrok-bin-win32-x64@2.2.8-beta.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info @expo/traveling-fastlane-linux@1.5.0: The platform "darwin" is incompatible with this module.
info "@expo/traveling-fastlane-linux@1.5.0" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...

success Installed "expo-cli@2.1.1" with binaries:
      - expo
      - expo-cli
✨  Done in 3.07s.
➜  test **expo init**
? Choose a project name: testexpo
? Choose a template: blank
[20:43:47] Extracting project files...
[20:43:53] Customizing project...

Your project is ready at /Users/edouardmalot/Desktop/test/testexpo
To get started, you can type:

  cd testexpo
  expo start

➜  test **cd testexpo** 
➜  testexpo git:(master) ✗ **expo start** 
[20:44:05] Starting project at /Users/edouardmalot/Desktop/test/testexpo
[20:44:12] Starting Metro Bundler on port 19001.
[20:44:12] Metro Bundler ready.
[20:44:40] Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?
[20:44:40] Set EXPO_DEBUG=true in your env to view the stack trace.
➜  testexpo git:(master) ✗ **export EXPO_DEBUG=tru**
➜  testexpo git:(master) ✗ **export EXPO_DEBUG=true**
➜  testexpo git:(master) ✗ **expo start**            
[20:45:02] Starting project at /Users/edouardmalot/Desktop/test/testexpo
[20:46:23] Starting Metro Bundler on port 19001.
[20:46:23] Metro Bundler ready.
[20:46:52] Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?
_[20:46:52] Error: Could not access packager status at http://localhost:19001/status. Are you sure the packager is running and reachable?
    at Timeout._onTimeout (/xdl@51.3.0/src/Project.js:1490:11)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)_
➜  testexpo git:(master) ✗ 

Any ideas ?

**Comment by jarecsni** [comment] 2018-09-24 22:37
Same here, both with old client (exp) and new one. 

It must have something to do with the fact that I've migrated the home folder of my user on Mac... but it's still kind of an issue that there is no meaningful error message. I believe the expo client cannot start the packager for some reason, but there is 0 error message for that, only the consequence, that the packager cannot be contacted.

**Comment by jarecsni** [comment] 2018-09-24 22:39
Just to add to that, in my case I don't even have the messages (as in the original post) saying that the packager is started, ready etc. No message at all, except for the error.

**Comment by jarecsni** [comment] 2018-09-25 06:44
Managed to fix my issue by reinstalling Node. Currently running on Node v 10.11

**Comment by iamchandu** [comment] 2018-09-29 07:12
same here. Please help me.

**Comment by calvinlang** [comment] 2018-10-02 18:48
I'm having the same issue, updating node didn't help.

**Comment by jarecsni** [comment] 2018-10-03 05:54
How did you update it? I completely wiped Node (deleting it from every single location from the Mac) and then installing it with NVM.

**Comment by roquefore** [comment] 2018-10-04 21:57
Same issue, cleaning up all node data and reinstalling it didnt help at all.

**Comment by jarecsni** [comment] 2018-10-05 12:51
One thing which may or may not help. I noticed the same error message again, but when I started 'exp' again, i could not see the error any more.

**Comment by techfresh** [comment] 2018-10-12 11:31
Hi, has there been any progress with this bug? I've tried numerous things but I still get the same issue

**Comment by sunviwo** [comment] 2018-10-31 07:53
I have the same error. Has someone found a fix please ?

**Comment by korede360** [comment] 2018-11-05 02:20
I'm having this same issue. Has anyone found a fix yet?

**Comment by poserr** [comment] 2018-11-05 15:01
Same problem. 

Every week or so I am trying to start new React Native project from scratch using new expo cli - and every time it fails due to different reasons. I cannot even get it launched in iOS Simulator.

**Comment by fson** [comment] 2018-11-29 23:15
Thanks for reporting this issue and sorry it's taken such a long time to get the root cause fixed. I'm closing this issue in favor of #52, which describes the same problem. See my comment in https://github.com/expo/expo-cli/issues/52#issuecomment-443025598 for the latest status of the issue.

**Closed by fson** 2018-11-29 23:15 UTC
Labels: bug
