### ISSUE TITLE
Regression: expo install react-native-svg installs incompatible version

### ISSUE THREAD

**Issue by jmatsushita** [expo/expo-cli#1466] opened 2020-01-21 09:51 UTC
## Description

This issue resurfaced https://github.com/expo/expo/issues/6142

## Expected Behavior

In a fresh `expo init` project. Runing `expo install react-native-svg` installs version `11.0.1`.
Reverting manually to `10.1.0` or `9.13.6` fixes the issue (after a cache reset).

## Observed Behavior

`expo start` flashes this error message (before the console is cleared)
```
Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-svg - expected version range: 9.13.3 - actual version installed: ^11.0.1
```

Then the iOS simulator displays this error:
```
Exception thrown while executing UI block: -[__NSCFNumber firstObject]: unrecognized selector sent to instance 0xc761e0cf0ce52dd7

__53-[ABI36_0_0RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    ABI36_0_0RCTUIManager.m:1166
__53-[ABI36_0_0RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.418
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start
```

## Environment

```
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.15.3/bin/npm
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ~16.9.0 => 16.9.17
      @types/react-native: ~0.60.23 => 0.60.31
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: ~0.61.4 => 0.61.5
    npmGlobalPackages:
      expo-cli: 3.11.7
```

The simulator is running iPhoneX 12.2

## Reproducible Demo

Using the SvgExample code in the documentation creates the crash in the simulator https://docs.expo.io/versions/latest/sdk/svg/#svg

**Comment by dafooz** [comment] 2020-02-28 21:48
Any news on this issue?

**Comment by molchanovskiy** [comment] 2020-03-14 17:49
Any news?

**Comment by ccheever** [comment] 2020-03-16 22:01
Hi--

We were able to reproduce this with the version of expo-cli that you are using but the bug appears to be fixed in the most recent version of expo-cli. If you use the latest versions of node, yarn, and expo-cli, I believe this issue will go away.

It's possible that if you made a new project using an older version of expo-cli, there are some artifacts in place that are causing this bug. 

If you upgrade and still have an issue, please post it here and we can try to help you migrate.

**Comment by devika7** [comment] 2020-03-17 22:55
Hi, I did install the latest version of expo- cli but I am still facing the same issue mentioned above.

**Comment by ccheever** [comment] 2020-03-18 00:11
Hi @devika7 - Thanks for following up. I'll reopen this issue.

Would you be open to doing some kind of screenshare at some point to debug this issue? I don't know how to work on it from my own computer.

**Comment by devika7** [comment] 2020-03-18 02:50
Sounds good. I can do that. Meanwhile, il uninstall the packages to continue working on the rest of my code and recreate the issue before the call.

**Comment by headwinds** [comment] 2020-03-20 17:54
I can confirm that this is still happening that installing 9.13.6 fixes it 

Strangely enough I have 2 projects - one on version sdk-36.0.0 where its works and one on sdk-36.0.1 where it doesn't so with this project I downgraded to 9.13.6 and can see some svgs again.

**Comment by brentvatne** [comment] 2020-04-06 20:55
it will depend on the version of the expo package you have installed, because that includes a file called `bundledNativeModules.json` that tells expo-cli what version is compatible. make sure you have the latest expo@36 version in your package.json (36.0.2) and run npm install again, then run `expo install` and you will have the correct version

this works as expected on new projects

```
expo init ExampleSvg --template blank@sdk-36
cd ExampleSvg
expo install react-native-svg
```

^ if you copy+paste example from snack in there you will see it works

**Closed by brentvatne** 2020-04-06 20:55 UTC
