### ISSUE TITLE
app.config.js can take longer to load when developing on Android itself

### ISSUE THREAD

**Issue by gsbenevides2** [expo/expo-cli#2341] opened 2020-07-04 23:45 UTC
## Description

I tried to use `app.config.js` to be able to set environment variables.  However, I can't access any of them in my app using `expo-constants`.  I tried to do a console log in the config parameter that comes in the function and the CLI returns the `app.json` config.

## Expected Behavior

That when I configure the additional manifest in app.config.js and see `Constants.manifest.extra` appear `{test: 'test'}`.

## Observed Behavior

`Constants.manifest.extra = undefined`

## Environment

Expo CLI 3.21.13 environment info:
    System:
      OS: android
    Binaries:
      Node: 12.18.1 - /data/data/com.termux/files/usr/bin/node
      Yarn: 1.22.4 - /data/data/com.termux/files/usr/bin/yarn
      npm: 6.14.5 - /data/data/com.termux/files/usr/bin/npm
    npmPackages:
      expo: ~38.0.8 => 38.0.8
      react: ~16.11.0 => 16.11.0
      react-dom: ~16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.1.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7

Expo Android Client Version 2.16.1
LG K12 Max Android 9

## Reproducible Demo
`app.config.js`
![carbon (1)](https://user-images.githubusercontent.com/45762112/86522555-3a122300-be36-11ea-850a-876f8504a46a.png)

## Comments
1.I tried using Typescript: `app.config.ts`.
2.With the `app.config.js` file, the CLI became noticeably slow and strange.
3.No error message.

**Comment by cruzach** [comment] 2020-07-09 20:01
This is because there is no manifest object when running the app locally. To generate the manifest, you need to publish with `expo publish`  

Tested this and the `extra` object is correctly populated for me in published experiences

**Comment by cruzach** [comment] 2020-07-09 20:10
@gsbenevides2 this is working for me with the exact same setup, could you try restarting the Expo client app and clearing your cache? That seems to be the go to solution for most people- https://github.com/expo/expo-cli/issues/88

**Comment by gsbenevides2** [comment] 2020-07-09 21:09
I've tried to clear the cache with expo start -c, reinstalled the expo-cli with old versions, cleared the cache and erased all data from the expo's android client, but nothing worked.

 When I deleted all customer data and tried to open it, the timeout error appeared:
![Screenshot_20200709-180006](https://user-images.githubusercontent.com/45762112/87090937-2c321880-c20f-11ea-98db-002f534a738a.png)
![Screenshot_20200709-180015](https://user-images.githubusercontent.com/45762112/87090958-33592680-c20f-11ea-8a65-63d0c8809614.png)


 I see something similar in the following issue: #2349

 In addition, when the CLI detects an app.config.js or app.config.ts file, it starts working slowly.

**Comment by cruzach** [comment] 2020-07-09 22:13
Let's rule out any issues with the code first- can you try to run this project https://github.com/cruzach/cli2341 ? Just clone, `yarn`, and `expo start`

When you do run the project, you can check the URL that expo-cli outputs to see the manifest that's being served. it'll be a url like
```
exp://10.0.0.44:19000
```
and in that case you'd visit `http://localhost:19000/`

**Comment by gsbenevides2** [comment] 2020-07-09 22:43
Still with the timeout error :(

**Comment by brentvatne** [comment] 2020-07-09 22:45
@gsbenevides2 - it times out when accessing the project from your computer in the web browser at http://localhost:19000/?

**Comment by gsbenevides2** [comment] 2020-07-09 23:08
I just did a test here and no, the manifest appears correctly with the `extra`.  I did a test with a tool here and the request time was: 63587ms.  The result in the browser:
```json
{
   "name":"cli2341",
   "slug":"cli2341",
   "version":"1.0.0",
   "orientation":"portrait",
   "icon":"./assets/icon.png",
   "splash":{
      "image":"./assets/splash.png",
      "resizeMode":"contain",
      "backgroundColor":"#ffffff",
      "imageUrl":"http://127.0.0.1:19001/assets/./assets/splash.png"
   },
   "updates":{
      "fallbackToCacheTimeout":0
   },
   "assetBundlePatterns":[
      "**/*"
   ],
   "ios":{
      "supportsTablet":true
   },
   "web":{
      "favicon":"./assets/favicon.png"
   },
   "sdkVersion":"38.0.0",
   "platforms":[
      "ios",
      "android",
      "web"
   ],
   "extra":{
      "key":"value"
   },
   "xde":true,
   "developer":{
      "tool":"expo-cli",
      "projectRoot":"/data/data/com.termux/files/home/Projetos/cli2341"
   },
   "packagerOpts":{
      "hostType":"lan",
      "lanType":"ip",
      "dev":true,
      "minify":false,
      "urlRandomness":null,
      "https":false
   },
   "env":{

   },
   "bundleUrl":"http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false",
   "debuggerHost":"127.0.0.1:19001",
   "mainModuleName":"node_modules/expo/AppEntry",
   "logUrl":"http://127.0.0.1:19000/logs",
   "hostUri":"127.0.0.1:19000",
   "iconUrl":"http://127.0.0.1:19001/assets/./assets/icon.png"
}
```

**Comment by brentvatne** [comment] 2020-07-09 23:48
i see that you are using android for your development machine. honesty i didn’t know this was even possible, we don’t officially support it with expo-cli so your mileage may vary. when we evaluate app.config.js we spawn a new js process and execute it, it could be that this is very slow with the terminal emulator you’re using. if you would like to investigate how to improve this you are welcome to, but i don’t think we can prioritize support for running expo-cli on android above other features and issues.

**Comment by gsbenevides2** [comment] 2020-07-10 00:00
I use Termux.  An android app that allows the emulation of an almost Linux environment.  I admit that there are some limitations, but the expo has always performed normally for me.  And I accidentally commented wrongly on the issue I mentioned:
https://github.com/expo/expo-cli/issues/2342

**Comment by brentvatne** [comment] 2020-07-16 17:53
@gsbenevides2 - if you can reproduce this issue on macos, windows, or linux and give us instructions on how to reproduce it, that would be very helpful and we can investigate

**Comment by gsbenevides2** [comment] 2020-07-26 17:58
Good afternoon, I did a test using Google Cloud Shell there were no errors.

```
Expo CLI 3.22.3 environment info:
    System:
      OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
      Shell: 5.0.3 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.22.4 - /usr/local/nvm/versions/node/v10.14.2/bin/yarn
      npm: 6.14.6 - /usr/local/nvm/versions/node/v10.14.2/bin/npm
    npmGlobalPackages:
      expo-cli: 3.22.3
```

**Comment by Inlustra** [comment] 2020-07-29 13:11
I'm also seeing this when running in a Docker container... 
I'm using code-server for my VSCode instance, running over LAN.

iOS is working fine and I think this is because the iOS version of expo has a much longer timeout that the Android version. Can this be changed?

**Comment by brentvatne** [comment] 2020-07-29 20:55
@Inlustra - can you share a reproducible example?

**Comment by Inlustra** [comment] 2020-08-01 23:40
Not easily unfortunately, my project grew quite large before I started seeing this.
I need to do some investigation but I honestly don't know where to start.

**Comment by gsbenevides2** [comment] 2020-08-01 23:45
@Inlustra Check what @cruzach said.  Try to reproduce what he said and see if it works.

**Comment by Inlustra** [comment] 2020-08-01 23:57
I've just done exactly that, same result, suggesting it's nothing to do with my code.
`
    time_namelookup:  0.004360s
       time_connect:  0.005060s
    time_appconnect:  0.000000s
   time_pretransfer:  0.005105s
      time_redirect:  0.000000s
 time_starttransfer:  12.793500s
                    ----------
         time_total:  12.793571s
`

**Comment by Rafatcb** [comment] 2020-08-13 12:07
I had this problem too, on an old Windows 10 computer. Updating to expo-cli v3.24.0 solved it.

**Comment by brentvatne** [comment] 2020-09-09 22:04
if you are experiencing this issue:

- run `npx expo-eval-config .` in your project with app.config.js and let me know what the "completed time" is
- next, run `npx raw-expo-eval-config ./app.config.js` in that same directory and let me know what the "completed time" is

**Comment by Rafatcb** [comment] 2020-09-10 19:52
I had this problem when I was developing on an old computer, so I decided to test it.

Without `app.config.js`:
* `npx expo-eval-config .` = 273.5249990224838ms

With `app.config.js`:
* `npx expo-eval-config .` = 10499.244100034237ms
* `npx raw-expo-eval-config ./app.config.js` = 30483.15299898386ms

And the `raw-expo-eval-config` thrown an error:

```json
{
  "message":"Cannot read property 'config' of null",
  "name":"TypeError",
  "stack":"TypeError: Cannot read property 'config' of null
    at _default (C:\\Users\\Usuario\\Desktop\\Dev\\coletor\\/app.config.js:1:19)
    at Object.<anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm-cache\\_npx\\3808\\node_modules\\raw-expo-eval-config\\node_modules\\@expo\\config\\src\\scripts\\read-config.ts:42:14)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\\Users\\Usuario\\AppData\\Roaming\\npm-cache\\_npx\\3808\\node_modules\\raw-expo-eval-config\\index.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:955:30)"
}
```

**Comment by brentvatne** [comment] 2020-09-10 23:30
@Rafatcb - what if you run `npx spawn-node-process` on that machine?

**Comment by Rafatcb** [comment] 2020-09-11 10:53
@brentvatne I ran `npx spawn-node-process` three times:

* 2162.9763000011444ms
* 577.9609999656677ms
* 935.6690000295639ms

**Comment by Inlustra** [comment] 2020-09-12 11:22
`npx spawn-node-process` = 55.17ms, 54.82ms, 56.76ms

With `app.config.js`:
- `npx npx expo-eval-config .` = 4079.79ms 
- `npx raw-expo-eval-config .` = 4651.04ms

Without:
- `npx npx expo-eval-config .` = 13.82ms, 12.18ms
- `npx raw-expo-eval-config .` = 4201.06ms, 4718.45ms

Admittedly the raw-expo-eval-config is throwing MODULE_NOT_FOUND
But I'm really not running this on a slow machine

**Comment by EvanBacon** [comment] 2020-09-15 23:35
The bottleneck here is babel/core which is used to transpile the ES/TS code. We recently reduced improved the evaluation code a bit by removing the external spawn script and simplifying the serialization in #2625

**Comment by EvanBacon** [comment] 2020-09-15 23:36
Closing as this is a [wontfix] issue. We will continue to find ways to improve config parsing speed. Another good speed improvement comes in #2636

**Closed by EvanBacon** 2020-09-15 23:36 UTC
Labels: needs research, wontfix
