### ISSUE TITLE
Ubuntu 17.10 entire system freezes when JavaScript bundle builds to 100%

### ISSUE THREAD

**Issue by johntzan** [expo/expo-cli#200] opened 2018-03-05 09:51 UTC
### Environment

Environment:
  OS: Linux 4.13
  Node: 9.7.1
  Yarn: 1.5.1
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^25.0.0 => 25.0.0
  react: 16.2.0 => 16.2.0
  react-native: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz => 0.52.0

### Steps to Reproduce

This happens about 8/10 times I try to run my project. 

1. Either running npm run start in terminal 
2. or running in xde client
3. Wait for bundle to reach 100%

### Expected Behavior

Project should load on my device right after. 
### Actual Behavior

Entire computer freezes and requires me to hold power button to restart.
System logs show this when it happens: 

Mar  5 04:18:05 YianniLemur org.gnome.Nautilus[1947]: Opened project at /home/yiannitzan/dev/restaurants
\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\0

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

Link to project zip file: https://www.dropbox.com/s/d5leu2jerjd9izs/restaurants.zip?dl=0

**Comment by jakubste** [comment] 2018-11-27 14:35
The last update in this issue was a long time ago, so I'm going to close this. Feel free to reopen if the problem is still occurring.

**Closed by jakubste** 2018-11-27 14:35 UTC
Labels: transferred
