### ISSUE TITLE
PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by varora1406** [expo/expo-cli#3896] opened 2021-10-10 17:39 UTC
### Summary

Expo is throwing error - PayloadTooLargeError: request entity too large
Source - `at readStream (_My Location_\node_modules\expo-cli\node_modules\@expo\dev-server\node_modules\raw-body\index.js:155:17)`

-----
Ideally, it should not throw error

### Environment

  Expo CLI 4.11.0 environment info:
    System:
      OS: Windows 10 10.0.19043
    Binaries:
      Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
      Yarn: 1.22.11 - C:\Users\varor\AppData\Roaming\npm\yarn.CMD
      npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6858069
    npmPackages:
      expo: ~42.0.1 => 42.0.3
      react: 16.13.1 => 16.13.1
      react-dom: 16.13.1 => 16.13.1
      react-native: https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz => 0.63.2
      react-native-web: ~0.13.12 => 0.13.18
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

POCO F1 Mobile

### Reproducible demo or steps to reproduce from a blank project

https://github.com/PhotoOrganizer/mobile-app

**Comment by varora1406** [comment] 2021-10-14 06:18
I am trying to load media from my phone.
While scrolling and loading more content, it runs into this error and stops loading media.

I even checked https://github.com/sivarajng/react-native-photo-grid-frame#readme for console logs but didn't found any.

**Comment by cederom** [comment] 2021-12-04 05:35
any solution to this one?

**Comment by buffaloDeveloper** [comment] 2021-12-14 04:46
Running into this error as well.

**Comment by cederom** [comment] 2021-12-14 10:49
Quick fix for this is to use XCode and its internal logging window, it does not trim messages. Those messages are really useful, as there is no debug this is the only way to monitor application behaviors when running from console.. expo please fix this limit or make it user controllable.

**Comment by valinagacevschi** [comment] 2022-01-26 11:28
> me too facing this issue. For me, its looks like I get a response from API. But my data is not that big at all.
> 
> PayloadTooLargeError: request entity too large at readStream (/usr/local/lib/node_modules/expo-cli/node_modules/raw-body/index.js:155:17) at getRawBody (/usr/local/lib/node_modules/expo-cli/node_modules/raw-body/index.js:108:12) at read (/usr/local/lib/node_modules/expo-cli/node_modules/body-parser/lib/read.js:77:3) at jsonParser (/usr/local/lib/node_modules/expo-cli/node_modules/body-parser/lib/types/json.js:135:5) at call (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7) at next (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5) at remoteDevtoolsCorsMiddleware (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/dev-server/src/middleware/remoteDevtoolsCorsMiddleware.ts:31:3) at call (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7) at next (/usr/local/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5) at serveStatic (/usr/local/lib/node_modules/expo-cli/node_modules/serve-static/index.js:75:16)

+1

**Comment by brunolcarlos** [comment] 2022-01-26 21:06
I have the same problem in Expo and my express is already configured to agree 200MB but not works

**Comment by bmitioglov** [comment] 2022-02-01 06:26
same problem

**Comment by Alb3it** [comment] 2022-02-11 08:26
same problem +1. My project is about 200MB and it still not working...

**Comment by mickey-stringer** [comment] 2022-02-11 22:04
I get this after `expo start` as soon as I run my app from iPhone. What is extra weird is that it's running code I've commented out, and is also running in some sort of infinite loop.
That is, I've commented out a few `console.log`s and saved my project. But when I reload the app, I see those log lines printed ad infinitum until I stop the server.

**Comment by Slapbox** [comment] 2022-02-25 01:39
I still see this when sending a payload of 5.4mb from the native app to an embedded webview with `5.2.0`.

How's it possible to update the limit? @brunolcarlos ?

**Comment by evelant** [comment] 2022-04-10 22:14
I ran into this when converting my plain RN project to expo (eas and the ability to use most native code packages finally made it possible!) because my app was spitting out a ton of warnings on startup. I worked around it for now with `patch-package` here's the 1 line patch to fix the issue in your node-modules until a permanent fix lands in expo-cli. Just put it in a file `@expo+dev-server+0.1.106.patch` in your patches directory. See [patch package](https://github.com/ds300/patch-package) for details.

```
diff --git a/node_modules/@expo/dev-server/build/middleware/devServerMiddleware.js b/node_modules/@expo/dev-server/build/middleware/devServerMiddleware.js
index 9490afe..53b0cc9 100644
--- a/node_modules/@expo/dev-server/build/middleware/devServerMiddleware.js
+++ b/node_modules/@expo/dev-server/build/middleware/devServerMiddleware.js
@@ -38,7 +38,7 @@ function createDevServerMiddleware({ watchFolders, port, logger, }) {
     middlwareMutations_1.replaceMiddlewareWith(middleware, cli_server_api_1.securityHeadersMiddleware, remoteDevtoolsSecurityHeadersMiddleware_1.remoteDevtoolsSecurityHeadersMiddleware);
     middleware.use(remoteDevtoolsCorsMiddleware_1.remoteDevtoolsCorsMiddleware);
     middlwareMutations_1.prependMiddleware(middleware, suppressErrorMiddleware_1.suppressRemoteDebuggingErrorMiddleware);
-    middleware.use(body_parser_1.default.json());
+    middleware.use(body_parser_1.default.json({limit: "2MB"}));
     middleware.use('/logs', clientLogsMiddleware_1.default(logger));
     middleware.use('/inspector', createJsInspectorMiddleware_1.default());
     return { middleware, attachToServer, logger };

```

**Comment by atroudi** [comment] 2022-06-07 14:12
Solved in my case it was a big error log so I convert the error to string (.toString()), its truncates the error to the first 1000 character of error object.

**Comment by GeneralTyres** [comment] 2022-06-14 14:29
@atroudi Where did the error log that you converted to a string?

**Comment by evelant** [comment] 2022-06-30 17:11
Is there a particular reason for the limit or truncation in the first place? Sometimes very long things (stack traces, etc) need to get logged during development. Unless there's a compelling reason to truncate/limit log messages why not set a large default so it's not a problem?

**Closed** 2022-06-30 17:13 UTC
Labels: bug

**Comment by brentvatne** [comment] 2022-07-07 19:49
no, you would only see this error if you are logging the a very large object. you can log part of it or not log it at all.

**Comment by nightness** [comment] 2022-08-03 01:12
> this is resolved using the new local cli: https://blog.expo.dev/new-versioned-expo-cli-cf6e10632656 - we're rolling this out more broadly in sdk 46 and you can use it already in sdk 45.
> 
> closing this because we don't plan on fixing in expo-cli.

Not fixed... Still see it using the beta CLI

**Comment by brentvatne** [comment] 2022-08-03 01:26
@nightness - can you provide a reproducible example please?

**Comment by cederom** [comment] 2022-08-03 01:53
Folks, if you prefer Python, you may want to switch to www.kivy.org, I consider JavaScript + ReactNative solutions unmaintainable, goodybe :-(

**Comment by brentvatne** [comment] 2022-08-03 03:26
@cederom bye!

**Comment by nightness** [comment] 2022-08-03 04:00
> @nightness - can you provide a minimal reproducible example please?
> 
> you're not using the local cli in the above example, you are using `expo-cli`. the local cli is `@expo/cli`. you need to invoke it with `npx expo start` and have the environment variable from the blog post set. it is the default in sdk 46 - https://blog.expo.dev/expo-sdk-46-c2a1655f63f7

I did use ```npx expo start```. I wish I could share the code to help, but can't (large project). I did remove all console calls, it it went away. I just don't understand why React can't tell me which console function is causing this. :(

**Comment by brentvatne** [comment] 2022-08-03 04:12
@nightness - if you're using sdk 45 you need to set `EXPO_USE_BETA_CLI=1` also

**Comment by nightness** [comment] 2022-08-03 04:12
> @nightness - if you're using sdk 45 you need to set `EXPO_USE_BETA_CLI=1` also

I did that

**Comment by nightness** [comment] 2022-08-03 04:17
> @nightness - if you're using sdk 45 you need to set `EXPO_USE_BETA_CLI=1` also

I am, I think the problem might be not pushing the new Expo Go to the simulator... It uses installing Expo Go 2.24.6, 2.25.x is newest right?

**Comment by brentvatne** [comment] 2022-08-03 04:24
@nightness - this change is only on the cli level. based on the log you provided you're still invoking expo-cli somehow. if you have that env var set and you are using `npx expo start` i'm not quite sure what is happening there. if you can provide a reproducible example we can check it out

**Comment by nightness** [comment] 2022-08-03 04:50
@brentvatne Looks like the messages are only suppressed... React still don't indicate where it's happening.
```
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  const hugeData = Array(10000000).fill('***********************************************************************************************');
  console.log(hugeData);
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

**Comment by brentvatne** [comment] 2022-08-03 05:00
what do you mean by suppressed? and what do you mean by "Expo still doesn't indicate where it's happening"?

**Comment by nightness** [comment] 2022-08-03 05:12
> what do you mean by suppressed?
Sorry this was an expo 46 project, seems it took too much time time to process in a reasonable amount of time on my computer.

> what do you mean by "Expo still doesn't indicate where it's happening"?
If a console function is getting crazy amounts of data, the exception should of been where it was happening... the stack trace didn't tell us which console function was causing it.

**Comment by lordkyle0** [comment] 2022-08-03 23:48
I'm trying to get all audioFiles with expo-medialibrary for using it in react-native-track-player but il get this error after the first objet of my media.assets

PayloadTooLargeError: request entity too large
    at readStream (C:\Users\Ir Francis Isasi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\raw-body\index.js:155:17)
    at getRawBody (C:\Users\Ir Francis Isasi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\raw-body\index.js:108:12)
    at read (C:\Users\Ir Francis Isasi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\body-parser\lib\read.js:77:3)
    at jsonParser (C:\Users\Ir Francis Isasi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\body-parser\lib\types\json.js:135:5)
    at call (D:\ReactNative\Projects\NduleAfrik\node_modules\connect\index.js:239:7)
    at next (D:\ReactNative\Projects\NduleAfrik\node_modules\connect\index.js:183:5)
    at remoteDevtoolsCorsMiddleware (C:\Users\Ir Francis Isasi\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\dev-server\src\middleware\remoteDevtoolsCorsMiddleware.ts:31:3)
    at call (D:\ReactNative\Projects\NduleAfrik\node_modules\connect\index.js:239:7)
    at next (D:\ReactNative\Projects\NduleAfrik\node_modules\connect\index.js:183:5)
    at serveStatic (D:\ReactNative\Projects\NduleAfrik\node_modules\serve-static\index.js:75:16)


Here is setupPlayer method

let media = await MediaLibrary.getAssetsAsync({
            mediaType: 'audio',
        });
        media = await MediaLibrary.getAssetsAsync({
            mediaType: 'audio',
            first: media.totalCount,
        })

        const tracks = []
        try {
            for (let asset of media.assets) {

                let obj = {
                    id: asset.id,
                    url: asset.uri,
                    title: asset.filename,
                    artist: "Inconnu",
                    duration: asset.duration,
                    album: asset.albumId || "Inconnu",
                    artwork: require('../assets/icon.png') || "https://picsum.photos/id/1016/200/301"
                }
                tracks.push(obj);
               TrackPlayer.add(tracks);
            }
            TrackPlayer.add(tracks);
        } catch (error) {
            console.log(error);
        }

**Comment by jeremyfrancis** [comment] 2022-09-13 21:50
<img width="343" alt="Screen Shot 2022-09-13 at 5 49 24 PM" src="https://user-images.githubusercontent.com/24768588/190015559-74515c1f-5e8d-4e81-b5ce-544ecc4cce26.png">
As a workaround I opened the file that the error gave me and just manually gave it a higher limit. Apparently it was at 1GB so I upped it to 2GB.

That seems a bit high so something might be off elsewhere but it did get rid of the error.

This is for "expo start"

**Comment by mathieucoinmiles** [comment] 2022-11-02 19:20
Added a detailed fix from @jeremyfrancis explanation here 
https://stackoverflow.com/questions/74280471/how-to-solve-expo-cli-request-entity-too-large

**Comment by marcosflp** [comment] 2023-03-31 17:14
I ran over this issue, and after digging, I found that the problem was because the ReactNative or Apollo was getting too many objects from the BE. After reducing the number of objects to parse, the warning was fixed.

Maybe there is a config that allows increasing the amount of data parsed?!

**Comment by thesoicalapp91** [comment] 2023-04-18 11:24
I haven't read all the comments but just going to add my use case. I received this error when console.log() my firebase firestore get requests for pagination. The data would come in fine but the error would still show. I just changed my 'lastVisible' variable console.log() to the firebase item data i.e console.log(lastVisible.data()) instead of just console.log(lastVisible) and this removed the error. I assume the large firebase object was casing the issue.

**Comment by gabalicious** [comment] 2023-08-08 17:07
This is literally happening for a brand new app with no extra dependencies other than expo entry npm packages

**Comment by daniel-ricado** [comment] 2023-09-11 00:09
having the same issue on a poll (both react query and fetch api versions), it's a reoccuriring poll but the payloads are very small.

**Comment by mathieucoinmiles** [comment] 2023-09-11 12:53
> having the same issue on a poll (both react query and fetch api versions), it's a reoccurring poll but the payloads are very small.

Have you tried this? https://github.com/expo/expo-cli/issues/3896#issuecomment-1301105376

**Comment by mr-ryan-james** [comment] 2023-09-29 10:01
This was happening to me because I was console.log(ing) too many things during an API call

**Comment by antgel** [comment] 2023-10-10 14:50
> This was happening to me because I was console.log(ing) too many things during an API call
> 
> I removed the console.log and the problem went 💨

Well, logging something shouldn't cause an error / undefined behaviour. The problem went, but so did your log. :man_shrugging: What next, you deleted your code and the bugs went away? :D
