### ISSUE TITLE
expo eject UnhandledPromiseRejectionWarning: Error: Cannot find module './log'

### ISSUE THREAD

**Issue by pcowgill** [expo/expo-cli#1406] opened 2020-01-02 22:06 UTC
# Description

Error when running `npx expo eject` with the `Bare` setting: `UnhandledPromiseRejectionWarning: Error: Cannot find module './log'`

## Expected Behavior

I ran `npx expo eject` to use the local version of `expo-cli`, and I expected it to run without errors using the `Bare` setting.

## Observed Behavior

It errored out after installing new packages step, when using the `Bare` setting.

Error message

```
Writing app.json...
Wrote to app.json, please update it manually in the future.
Successfully copied template native code.
Updating your package.json...
Your package.json is up to date!
Adding entry point...
Removing "main": main.ts from package.json. We recommend using index.js instead.
Added new entry points!
Note that using `npm start` will now require you to run Xcode and/or Android Studio to build the native code for your project.
Removing node_modules...
Installing new packages...
(node:15100) UnhandledPromiseRejectionWarning: Error: Cannot find module './log'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at _log (/expo-cli@3.11.3/src/exp.ts:35:1)
    at Command.action (/expo-cli@3.11.3/src/exp.ts:94:9)
(node:15100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Note that the global expo info isn't relevant, as I ran the local version with `npx expo eject`. However, the local version happens to be `3.11.3` as well.

```
Expo CLI 3.11.3 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      Yarn: 1.16.0 - ~/.yarn/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.7.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmGlobalPackages:
      expo-cli: 3.11.3
```

Also specify:

- Phone/emulator/simulator platform, model and version: n/a

**Comment by brentvatne** [comment] 2020-01-02 22:23
using expo-cli 3.11.3:

```
╭─~/coding/ReactTutorial ‹master›
╰─$ expo eject
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard

? How would you like to eject your app?
  Read more: https://docs.expo.io/versions/latest/expokit/eject/ Bare
We have a couple of questions to ask you about how you'd like to name your app:
? What should your app appear as on a user's home screen? ReactTutorial
? What should your Android Studio and Xcode projects be called? Hello
Writing app.json...
Wrote to app.json, please update it manually in the future.
Successfully copied template native code.
Updating your package.json...
Your package.json is up to date!
Adding entry point...
Added new entry points!
Note that using `yarn start` will now require you to run Xcode and/or Android Studio to build the native code for your project.
Removing node_modules...
Installing new packages...
> yarn install
yarn install v1.19.2
[1/4] 🔍  Resolving packages...




success Saved lockfile.
info To upgrade, run the following command:
warning Your current version of Yarn is out of date. The latest version is "1.21.1", while you're on "1.19.2".
$ brew upgrade yarn
$ jetify
Jetifier found 1189 file(s) to forward-jetify. Using 4 workers...
✨  Done in 42.67s.

Ejected successfully!

Before running your app on iOS, make sure you have CocoaPods installed and initialize the project:

  cd ios
  pod install

Then you can run the project:

  yarn android
  yarn ios

Warning: your app includes 1 package that requires additional setup. See the following URL for instructions.
Your app may not build/run until the additional setup for this package has been completed.

- expo-image-picker: https://github.com/expo/expo/tree/master/packages/expo-image-picker
```

using npx:

```
╭─~/coding/ReactTutorial ‹master›
╰─$ npx expo eject
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard

? How would you like to eject your app?
  Read more: https://docs.expo.io/versions/latest/expokit/eject/ Bare
We have a couple of questions to ask you about how you'd like to name your app:
? What should your app appear as on a user's home screen? ReactTutorial
? What should your Android Studio and Xcode projects be called? Hello
Writing app.json...
Wrote to app.json, please update it manually in the future.
Successfully copied template native code.
Updating your package.json...
Your package.json is up to date!
Adding entry point...
Added new entry points!
Note that using `yarn start` will now require you to run Xcode and/or Android Studio to build the native code for your project.
Removing node_modules...
Installing new packages...
> yarn install
yarn install v1.19.2
[1/4] 🔍  Resolving packages...




success Saved lockfile.
$ jetify
Jetifier found 1189 file(s) to forward-jetify. Using 4 workers...
✨  Done in 29.28s.
[-/5] ⠈ waiting...
Ejected successfully!

Before running your app on iOS, make sure you have CocoaPods installed and initialize the project:

  cd ios
  pod install

Then you can run the project:

  yarn android
  yarn ios

Warning: your app includes 1 package that requires additional setup. See the following URL for instructions.
Your app may not build/run until the additional setup for this package has been completed.

- expo-image-picker: https://github.com/expo/expo/tree/master/packages/expo-image-picker
```

unable to reproduce it :(

**Comment by pcowgill** [comment] 2020-01-02 23:13
@brentvatne Thanks for looking into this. I was using npm rather than yarn, which may be related.

FYI after reverting the changes to the last clean git commit from right before running the eject command and rerunning the command, it completed successfully.

This would suggest that there is some race condition in the CLI scripts OR that one of the underlying packages had an issue and reinstalling fixed it due to the `~` or `^` in `package.json` (but that seems unlikely given that there was a lockfile).

These lines in the error output...

```
at _log (/expo-cli@3.11.3/src/exp.ts:35:1)
at Command.action (/expo-cli@3.11.3/src/exp.ts:94:9)
```

...suggest that for some reason `./log` doesn't get defined reliably by the time those lines are run?

**Comment by pcowgill** [comment] 2020-01-02 23:18
@brentvatne Installing `expo-cli` in individual projects as a dev dep is nice because you can ensure that all of the devs working on the project will be running the same version.

**Comment by pcowgill** [comment] 2020-01-07 18:24
> @brentvatne Installing `expo-cli` in individual projects as a dev dep is nice because you can ensure that all of the devs working on the project will be running the same version.

@brentvatne I suppose using `npx` to run the latest version as it if were global without it installed locally is better than either of the alternatives we mentioned

**Comment by EvanBacon** [comment] 2020-04-28 04:10
expo-cli is currently way to big to be a worthy candidate of npx. Related https://github.com/expo/expo-cli/issues/1979

**Comment by pcowgill** [comment] 2020-04-28 04:32
> expo-cli is currently way to big to be a worthy candidate of npx. Related https://github.com/expo/expo-cli/issues/1979

@EvanBacon Not when it’s running the local version if included in the project as a dev dependency, right?

**Comment by EvanBacon** [comment] 2020-09-15 18:38
Closing as we've rewritten a bunch of the eject command. If the problem persists, please reopen the issue.

**Closed by EvanBacon** 2020-09-15 18:38 UTC
Labels: needs repro
