### ISSUE TITLE
IOS build fails: cannot read property '0' of undefined

### ISSUE THREAD

**Issue by stilllife00** [expo/expo-cli#1078] opened 2019-10-06 15:07 UTC
## Description

At the build step "Building and Signing IPA" of a ios build the build fails.

## Expected Behavior

The build succeeds

## Observed Behavior

```
building and signing IPA
saved provisioning profile to temporary path
provisioning profile copied to home directory
done retrieving provisioning profile data
checking if teamID is present in keychain and that certificate is valid...
ensured certificate is valid
validating provisioning profile...
removed provisioning profile from the home directory
TypeError: Cannot read property '0' of undefined
    at _ensureDeveloperCertificateIsValid (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosCodeSigning.js:138:56)
    at Object.validateProvisioningProfile (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosCodeSigning.js:132:3)
    at Object.build (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosIPABuilder.js:131:24)
    at <anonymous>
```

## Environment

Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.15.1 - ~/.nvm/versions/node/v8.15.1/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.6 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8 
      react-navigation: 3.11.0 => 3.11.0 
    npmGlobalPackages:
      expo-cli: 3.2.3

**Comment by brentvatne** [comment] 2019-12-08 06:40
@dsokal - this issue is a bit old, any idea if it is still a problem or if it has since been resolved?

**Comment by dsokal** [comment] 2019-12-09 15:49
@brentvatne no idea
@stilllife00 could you please send your build id so I could investigate it more?

**Comment by stilllife00** [comment] 2019-12-09 19:53
https://expo.io/dashboard/mirkoguarnier/builds/2e6710d6-baf6-4106-9d5c-753bf172084f

**Comment by dsokal** [comment] 2019-12-10 08:57
@stilllife00 What happens if you try building again? I can see that you changed the bundle identifier for your app but the app credentials in our database (dist certificate, provisioning profile, etc.) only exist for the app with the original bundle identifier.

**Comment by stilllife00** [comment] 2019-12-10 09:03
So I don't remember exactly the steps I made to fix it but ai remember the following: I tried with custom made credentials but I made some mistakes in providing the correct parameters. I tried again with credentials handled by Expo and after understanding the mistake it worked. I think this issue can be closed but the error message should be more informative. A wild guess is that i was providing the wrong params in some of the questions and so ending up in that error

**Comment by dsokal** [comment] 2019-12-10 09:12
Alright, thanks for the clarification. We're totally aware that the error messages in the build process could be more informative, but I think this is not the best issue to track this thing. 
Like you suggested - I'm closing this one but I promise we keep in mind making the error messages better.

**Comment by nmpribeiro** [comment] 2020-02-06 15:13
I have this exact same result:

### Description
At the build step "Building and Signing IPA" of a ios build the build fails.

### Expected Behaviour
The build succeeds

### Observed Behaviour
```
building and signing IPA
saved provisioning profile to temporary path
provisioning profile copied to home directory
done retrieving provisioning profile data
checking if teamID is present in keychain and that certificate is valid...
ensured certificate is valid
validating provisioning profile...
removed provisioning profile from the home directory
TypeError: Cannot read property '0' of undefined
    at _ensureDeveloperCertificateIsValid (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosCodeSigning.js:148:56)
    at Object.validateProvisioningProfile (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosCodeSigning.js:142:3)
    at Object.build (/usr/local/turtle-js/node_modules/@expo/xdl/build/detach/IosIPABuilder.js:133:24)
    at <anonymous>
```

### Environment
Expo CLI 2.19.4 environment info:
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.9.17 => 16.9.19
      @types/react-native: ^0.60.30 => 0.60.31
      @types/react-navigation: ^3.4.0 => 3.4.0
      expo: ^35.0.0 => 35.0.1
      react: 16.8.6 => 16.8.6
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8
      react-navigation: ^2.1.18 => 2.18.3
    npmGlobalPackages:
      expo-cli: 3.11.7

**Comment by nmpribeiro** [comment] 2020-02-06 16:39
Interestingly, the app I was trying to build was successful once I `expo logout` , then logged in with my company's expo account.

-- A bit out of the scope, but somewhat related --
However, in my personal account I can see teams, but in my company's account I cannot. Perhaps if my personal account was part of my company's team, the build would pass.

**Comment by tcdavis** [comment] 2020-02-06 16:48
Hi @nmpribeiro,  would love to help you get this figured out.  Could you share your app.json and the account names for both you and you company?

**Comment by nmpribeiro** [comment] 2020-02-06 16:55
Can we PM? I am at expo developers slack (@Nuno #general or #random)
Any relevant information for the solution of this issue should be left here, but those informations shouldn't be relevant information to be left in a public thread :) We're cool?

**Comment by nmpribeiro** [comment] 2020-02-16 15:24
Thanks @tcdavis ! Now we can setup teams in the company account, should that be something we aim for.
Turns out my error was really due to not building with the correct user under expo account.

**Comment by tcdavis** [comment] 2020-02-17 20:45
It's up to you.  If you're ok with waiting for your builds to make it through the queue and sharing your password / making sure you're signed in to the right account there's no need, but I think teams is nicer :)

**Closed by tcdavis** 2020-02-17 20:45 UTC
Labels: needs more info, waiting-for-response
