### ISSUE TITLE
Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"

### ISSUE THREAD

**Issue by maxsl89** [expo/expo-cli#4710] opened 2023-05-27 18:50 UTC
### Summary

When I try to build an ios package, I'm getting an error in Prebuild section

### Environment

expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v12.22.12/bin/yarn
      npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    IDEs:
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      expo: ^48.0.0 => 48.0.17 
      react: 18.2.0 => 18.2.0 
      react-dom: 18.2.0 => 18.2.0 
      react-native: 0.71.3 => 0.71.3 
      react-native-web: ~0.18.11 => 0.18.12 
    Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

macbook m1

### Error output

yarn run v1.22.17
$ /Users/expo/workingdir/build/node_modules/.bin/expo prebuild --no-install --platform ios
- Creating native project directories (./ios and ./android) and updating .gitignore
✔ Created native project | gitignore skipped
- Adding Metro bundler config
✔ Added Metro config
- Updating your package.json scripts, dependencies, and main file
✔ Updated package.json and added index.js entry point for iOS and Android
› Removed "main": "node_modules/expo/AppEntry.js" from package.json because we recommend using index.js as main instead
- Config syncing
[stderr] 
Using node to generate images. This is much slower than using native packages.
[stderr] 
› Optionally you can stop the process and try again after successfully running `npm install -g sharp-cli`.
- Config syncing
✖ Config sync failed
[stderr] 
UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
[stderr] 
Please report this as an issue on https://github.com/expo/expo-cli/issues
[stderr] 
UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/expo/workingdir/build"
[stderr] 
Please report this as an issue on https://github.com/expo/expo-cli/issues
[stderr] 
    at getAppDelegateFilePath (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/build/ios/Paths.js:113:11)
[stderr] 
    at getAppDelegate (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/build/ios/Paths.js:178:20)
[stderr] 
    at Object.getSourceRoot (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/build/ios/Paths.js:183:23)
[stderr] 
    at /Users/expo/workingdir/build/node_modules/@expo/prebuild-config/build/plugins/unversioned/expo-splash-screen/withIosSplashAssets.js:103:66
[stderr] 
    at action (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/build/plugins/withMod.js:235:29)
[stderr] 
    at interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/prebuild-config/node_modules/@expo/config-plugins/build/plugins/withMod.js:126:27)
[stderr] 
    at action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:206:14)
[stderr] 
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
[stderr] 
    at async interceptingMod (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/withMod.js:105:21)
[stderr] 
    at async action (/Users/expo/workingdir/build/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:61:21)
[stderr] 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn exited with non-zero code: 1

### Reproducible demo or steps to reproduce from a blank project

run eas build -p ios
wait for error in eas

**Comment by reflect-zz** [comment] 2023-05-30 00:54
same error.

**Comment by maxsl89** [comment] 2023-06-05 10:16
> same error.

hi, did you find a solution?

**Comment by reflect-zz** [comment] 2023-06-05 15:16
Yes! I solved using npm ls @expo/config-plugins (for example)
you can see which plugin or component has the wrong version. 
Need to uninstall individually and then install in correct version.
because some library might be in wrong version inside this component.

**Comment by maxsl89** [comment] 2023-06-06 03:55
> Yes! I solved using npm ls @expo/config-plugins (for example) you can see which plugin or component has the wrong version. Need to uninstall individually and then install in correct version. because some library might be in wrong version inside this component.

Thank u!
I found an outdated expo-app-loading package using **npm ls @expo/config-plugins** and reinstalled it to the actual version 
now it's builded!

**Comment by godlatro** [comment] 2023-06-19 05:00
same error
nodeJs 18.16.0
create-expo-app@2.0.3
expo eject

UnexpectedError: [ios.dangerous]: withIosDangerousBaseMod: Could not locate a valid AppDelegate at root: "/Users/user/App"
Please report this as an issue on https://github.com/expo/expo-cli/issues
    at getAppDelegateFilePath (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:52:11)
    at getAppDelegate (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:114:20)
    at Object.getSourceRoot (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/Paths.ts:119:23)
    at getProjectName (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/ios/utils/Xcodeproj.ts:33:28)
    at getIosNamedProjectPath (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:172:23)
    at setIconsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:107:31)
    at /usr/local/lib/node_modules/expo-cli/node_modules/@expo/prebuild-config/src/plugins/icons/withIosIcons.ts:15:13
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:227:29)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:27)
    at action (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/createBaseMod.ts:82:27)
    at interceptingMod (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/withMod.ts:108:21)
    at evalModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:172:25)
    at compileModsAsync (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/config-plugins/src/plugins/mod-compiler.ts:82:10)
    at configureManagedProjectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/configureProjectAsync.ts:64:12)
    at prebuildAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/prebuildAppAsync.ts:90:21)
    at ejectAsync (/usr/local/lib/node_modules/expo-cli/src/commands/eject/ejectAsync.ts:37:19)

**Comment by byCedric** [comment] 2023-12-25 07:47
Hi all! I'm glad you could find the cause. If this still happens for newer projects, please open a new issue on [github.com/expo/expo](https://github.com/expo/expo).

Closing this issue as `expo-app-loading` is deprecated, use `expo-splash-screen` API methods instead.

**Closed by byCedric** 2023-12-25 07:47 UTC
Labels: needs review

**Comment by viiicky** [comment] 2023-12-25 14:15
Replacing `expo-app-loading` with `expo-splash-screen` solved the problem for me.
