### ISSUE TITLE
Expo server crashes often.

### ISSUE THREAD

**Issue by EltonZhong** [expo/expo-cli#519] opened 2019-01-16 07:19 UTC
ECONNRESET

![image](https://user-images.githubusercontent.com/20570738/51232472-cbbb7580-19a1-11e9-83f2-390c8adb4fb9.png)
![image](https://user-images.githubusercontent.com/20570738/51232480-d7a73780-19a1-11e9-80c1-78c9fe77310d.png)
I served the app with the command: `expo start`
But it keeps crashing again and again. And I can not get any information from the message.

**Comment by tozenda** [comment] 2019-04-17 02:42
Hey there!

Same problem for me. Expo server crashes without apparent reasons. 

### Environment

Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^32.0.0 => 32.0.6 
      react: 16.5.0 => 16.5.0 
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1 
      react-navigation: ^3.8.1 => 3.8.1 
    npmGlobalPackages:
      expo-cli: 2.14.0

### Error is : 

events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by mohameddroussi** [comment] 2019-04-17 11:56
I am having the same issue.. anyone have any insight on this?
`events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by ImBeCiliC** [comment] 2019-04-18 08:25
Someone tried to downgrade their node to version 8.16.0? Some reported that this solves the crashing expo-cli.

**Comment by ahmedu007** [comment] 2019-04-25 14:53
Issue still remains 

```js
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
      Memory: 58.02 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.5.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

Error message: 

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by alexzubovsky** [comment] 2019-04-25 19:12
On Windows I uninstalled  node, then downloaded v8.9.4 msi from node site and install it. Looks like the problem is gone

**Comment by byCedric** [comment] 2019-05-12 11:33
I have the same issue here. To me it looks like it's crashing after being idle (make no changes, and don't connect a phone) for about 5 - 10 min. After that it consistently resets the connection. To me, it looks a bit like a websocket timeout. I'll try to dig a bit deeper, see where the error is coming from exactly.

```
> expo diagnostics                                                                                     [7c1d523]  2:19

  Expo CLI 2.17.1 environment info:
    System:
      OS: macOS 10.14.4
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      @types/expo: ^32.0.11 => 32.0.11
      @types/react: ^16.8.14 => 16.8.14
      @types/react-native: ^0.57.50 => 0.57.50
      @types/react-navigation: ^3.0.6 => 3.0.6
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: github:expo/react-native#sdk-32.0.3 => 0.57.1
      react-navigation: ^3.9.1 => 3.9.1
    npmGlobalPackages:
      expo-cli: 2.17.1
```

**Comment by jrgleason** [comment] 2019-05-14 21:00
I am getting a similar solution on an app I am working on, can someone see if ti works for them with node v11? I am getting the error on node 10 but not 11

**Comment by cruzach** [comment] 2019-05-20 16:11
I can't seem to reproduce this on my end, can someone confirm that they still get this behavior on the the most recent version of Expo-CLI (2.18.2)?

I would also make sure you have watchman installed, as per our [Installation Guide](https://docs.expo.io/versions/latest/introduction/installation/#watchman)

**Comment by JStewUnivers** [comment] 2019-05-24 13:13
I just updated my Expo version and followed the Installation guide for watchman. I can confirm the issue still persists.

**Comment by someonesatan** [comment] 2019-06-11 13:52
I have the same issue with Expo-cli (2.19.4)

**Comment by JigzIO** [comment] 2019-06-13 12:21
Also experiencing the same issue, Expo-cli(2.19.5)

**Comment by cruzach** [comment] 2019-06-13 15:49
Hey everyone, we can definitely look into this, but there seems to be a lot of comments just saying that they're also experiencing the issue. Please provide some additional information (good example is @byCedric's comment above), that helps us to investigate where the bug is (the source code is all open source, so feel free to also take a peak 😄)

@byCedric - we (basically) have the same environment setup, but I can't reproduce this. Can you confirm this happens on a blank `expo init` project? Once I can replicate it, I'm happy to help find the root cause

**Comment by llamaluvr** [comment] 2019-06-13 17:09
I've experienced this issue for at least the last four months, and I've been regularly updating the Expo CLI. I've found a high correlation between this issue and debugging on the Expo app using both my iOS simulator and an Android phone at the same time.

So, I will usually start by running `expo start`, then running Expo and connecting to my local instance in an iOS simulator. Then I'll do the same on my Android phone. Things are usually fine for a few live-reloads, but eventually I get that error, and once I get it, it usually happens again within 5 minutes. I then can get it to stop by killing the Expo CLI, swiping closed anything Expo-related on the Android phone, and restarting Expo.

**Comment by byCedric** [comment] 2019-06-16 17:27
@cruzach It's still happening on a blank typescript project for SDK 33. 

Did some digging around in the code, but couldn't come up with anything. Then I did some googling, and it turns out lots of other projects are experiencing the same weird behavior. I guess this all might be related to https://github.com/nodejs/node/issues/23169#issuecomment-470366571, I can't find anything else... 😅

**Comment by cruzach** [comment] 2019-06-17 20:14
@byCedric thanks for all that digging- an example reproducing this would be awesome, thanks!

**Comment by llamaluvr** [comment] 2019-06-18 21:08
I was just able to reproduce the crash reliably using the blank template on the latest expo-cli and SDK 33.

Expo diagnostics:
```
 Expo CLI 2.20.1 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - ~/.nvm/versions/node/v10.14.2/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.6
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
    npmGlobalPackages:
      expo-cli: 2.20.1
```

Repro steps:
1) Create blank project with `expo init`
2) Run `expo start`
3) Press i to launch it on the iOS simulator
4) Scan the barcode to launch it on an android phone (Galaxy S8 in this case)
5) Wait a few minutes (don't modify the code or anything), but you can keep doing other stuff on your computer, that's fine
6) Then it errors with:
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

I definitely found it did not do it if I kept tinkering with the code, forcing reloads. I had to stop doing stuff, and then it usually happened within 5 minutes.

It did not happen if just the iOS simulator was connected.
It did not happen if I connected an iPhone and the iOS simulator but no Android phone.
Haven't tried just an Android phone yet... guess that's next.

**Comment by byCedric** [comment] 2019-06-19 01:06
@llamaluvr Yeah, this is exactly how I'm "triggering" those errors too. Didn't test with the simulators, but it happens when I normally code and just be idle for a bit. So for me, changing 1 or 2 things and force (at least) 1 reload (and then be idle for ±5 min).

Again, I tend to think this is related to a timeout not being handled properly as described in the Node issue I found. The main expo server is still running because I have to quit it still after the error. Something I also found a bit weird is that Expo is telling me about "we've found some connectivity issues, try switching connection types" (tunnel/local/etc) when using web only.

@cruzach I'll set up something quick for you, but I think Keith has explained it better than I can 😄

**Comment by Shrekie** [comment] 2019-06-20 10:39
Want to report this happens to me also, the inconsistency of the error is odd. 
Sometimes I rarely get the error, other times a few reloads is all it takes.

Keep in mind the reproduction of this error in my case would be difficult as it could take a lot of a reloads before it happens.

**Comment by byCedric** [comment] 2019-06-20 22:29
Thanks @Shrekie, I've been experimenting with for quite some time. May I ask to you and @llamaluvr, are you using a globally installed expo-cli or project installed expo-cli? Might be a long shot, but project installed one appears to be a lot more stable for me. (as in, can't reproduce it with that one).

@cruzach I can reproduce the error with this project https://github.com/byCedric/use-expo/tree/bb04f8794f004820e101484f6737da131d86e2f9/example. If I start this with a globally installed expo-cli `expo start`, it will happen after some reloads and then some idle time. (e.g. ±5 min).

**Comment by Shrekie** [comment] 2019-06-21 07:09
@byCedric I've got expo installed globally.

**Comment by llamaluvr** [comment] 2019-06-21 14:35
@byCedric same here, Expo is global for me.

**Comment by byCedric** [comment] 2019-06-21 16:14
Ok, so I think that's one of the factors of triggering this error. Thanks @Shrekie and @llamaluvr! I'll try some possible fixes tonight!

**Comment by byCedric** [comment] 2019-06-22 14:27
Ok, so this is what I've observed so far:

- **`ECONNRESET` is thrown in the [`packagerProcess`](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.js#L1598) that lets the process exit with error status `1`**
I think this is related to changes in Node 10+ socket error handling, like [ibs explains here](https://github.com/nodejs/node/issues/23169#issuecomment-470366571). Fun thing about this is that _only the packager process is exiting_, both the Expo server and ngrok tunnels are still alive and kicking. When you encounter this error, check `.expo/packager-info.json`, I noticed both `packagerPort` and `packagerPid` were set to `null`.

- **The error is hard to reproduce consistently**
I've tried _a lot of things_, but I can't find a recipe where it consistently triggers the error. Here are some of the characteristics which I think are necessary to reproduce.

> 1. Start Expo with a **globally installed CLI**
> 2. Connect an external device (I tried Android only)
> 3. Make a couple of changes to rerender the app (I did 5x, just to make sure)
> 4. Set device in standby mode or close Expo on device
> 5. Wait ±5 min without making any changes at all (sometimes it took a bit longer)

> [Keith has a way more in-depth and detailed explanation though.](https://github.com/expo/expo-cli/issues/519#issuecomment-503312684)

- **What is the fix?**
This is a tough one to answer because the issue is really hard to reproduce. By looking at the Node 10+ changes related to sockets and error handling, I think we need to add extra error handlers. I'm not exactly sure where we need to add it, but it should be related to the packager's process. I've tried injecting libraries like [longjohn](https://www.npmjs.com/package/longjohn) to determine the exact origin, but so far no luck.

**Comment by GSolari79** [comment] 2019-06-24 12:05
Same here. It happens every 5 to 10 mins making development impossible:
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by rgoulter** [comment] 2019-06-24 14:19
> Same here. It happens every 5 to 10 mins making development impossible:

I had this problem when connecting the Expo app to the bundler over wifi. As a workaround, connecting the phone to the computer using a cable (per https://facebook.github.io/react-native/docs/running-on-device) helped avoid the issue for me.

**Comment by byCedric** [comment] 2019-06-24 15:53
@rgoulter I think you just found what I was looking for this whole weekend! ❤️  When I get home I'll try to inject some error handlers into the code. Will keep updating this issue when I know more 😄

**Comment by zilahir** [comment] 2019-06-27 21:10
same here. do we have a solution for this? sarted to happen today, after developing a project for months now. 

any ideas?

**Comment by byCedric** [comment] 2019-06-27 22:15
@zilahir No, I still haven't found the solution for this. Have been digging through the source code quite a while now, I'm afraid it might be even deeper nested in dependencies other than the react native community cli. But here are a few things that affect the issue:

- Only Node 10+ triggers this issue, Node 8 still has default error handlers.
- I could only trigger this with a globally installed Expo
- It happens after being idle for about 5 min (so if you frequently save, it won't happen)

Some other things on top of my mind:

- Might be related to an outdated `ws` dependency, I've seen some usage of versions 1..3. (Right now they released version 7. [Metro bundler has an open PR to update this](https://github.com/facebook/metro/pull/412).)

I'll keep trying to debug this when I have some spare time again!

**Comment by zilahir** [comment] 2019-06-27 22:21
@byCedric  thanks for your reply! And yes, I also noticed if I am saving often, the issue is not happening. 

There was not any change in my dep. tree though, so that's part probably still a mystery. 

Thank you!

**Comment by fedebabrauskas** [comment] 2019-08-17 01:57
Hi there!

I was experimenting this error every 5-10 minutes as others said.

Apparently, I solved this issue just by updating my Node version from 12.7.0 to 12.8.1, I'm running expo-server since a couple of hours and it didn't crashed! 😄

**Comment by AlexanderTserkovniy** [comment] 2019-08-17 12:45
Hi guys,

Same issue here, have just done first time install of the expo at all.

If you have any updates so far it would be great if you could share them.

**Comment by Slapbox** [comment] 2019-09-06 20:38
Oh! I can maybe solve this one, at least for Android. Disable battery saver for Expo on your Android device, otherwise the connection will regularly be severed.

**Comment by JimVanEeden** [comment] 2019-09-20 10:48
I constantly get this error, it's getting kind of frustrating. Tried all different kinds of things and I can't find a pattern in when the connection goes down, sometimes it stays up for quite a while, sometimes it's after a minute.

**Comment by lixx4793** [comment] 2019-09-20 19:08
Expo CLI 3.0.10 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

Same thing happen to me, not sure what's going on. If I don't stay active on testing my app, I get this error after 5 min

**Comment by GodwinEbikwo** [comment] 2019-09-23 05:55
Really annoying error it is

**Comment by vandrieu** [comment] 2019-09-24 14:51
> Maybe the problem because I use the socket.io and websocket in my project?

I get the "Error: read ECONNRESET" issue a lot as well and I also use socket.io in my project.

Everyone else having this error, are you also using socket.io?

**Comment by JStewUnivers** [comment] 2019-09-24 15:04
@vandrieu I don't think it is a Socket.io in the sense i wasn't using it at all and still received this error.

**Comment by Maadtin** [comment] 2019-09-24 16:09
this only happens on my windows 10 machine and yes it's very frustrating is there any fix yet?

**Comment by cesarhilario** [comment] 2019-10-04 14:51
same issue here on macOs Mojave

**Comment by Hyllesen** [comment] 2019-10-05 17:34
I get the same error very often on OS X Sierra, it usually happens when I do something dumb and I make my app crash. But the annoying thing is that the bundle server shuts down, and I have to restart Expo with expo start every time...

**Comment by gitowiec** [comment] 2019-10-15 13:15
Having this issue also
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

`$ npx react-native info`:
```
info 
  React Native Environment Info:
    System:
      OS: Linux 5.1 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 1.21 GB / 15.56 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
      Yarn: 1.19.1 - /usr/bin/yarn
      npm: 6.11.3 - ~/.nvm/versions/node/v10.16.2/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 28, 29
        Build Tools: 28.0.3, 29.0.2
        System Images: android-23 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom_64
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
```

I observed that using system image "android-28 | Google Play Intel x86 Atom_64" was all ok, but switching to another emulator (Nexus 4 with Android 6, system Image android-23 | Google APIs Intel x86 Atom_64) made errors sprout out a lot!

**Comment by angel-luis** [comment] 2019-11-05 19:59
Same here:

```
events.js:186
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
  code: 'ECONNRESET',
  syscall: 'read'
}
```
Windows 10 x64 1903 and last Expo version.

**Comment by Jordhan-Carvalho** [comment] 2019-11-08 14:47
Same issue

`info 
  React Native Environment Info:
    System:
      OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
      CPU: (8) x64 AMD FX-8320E Eight-Core Processor
      Memory: 158.22 MB / 7.69 GB
      Shell: 4.4.20 - /bin/bash
    Binaries:
      Node: 13.0.1 - /usr/local/bin/node
      npm: 6.12.0 - /usr/local/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8`

**Comment by azadious** [comment] 2019-11-14 12:38
I have downgraded node to version 8 from version 12. Now I have not encountered this problem at all.

**Comment by SamDe4574** [comment] 2019-11-14 13:11
I have the same issue, I have to restart Expo, everytime this happens, any fix for this issue?

**Comment by jongold** [comment] 2019-11-16 23:27
Getting this a bunch
```
  Expo CLI 3.7.1 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.10.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 1.5 AI-141.2422023
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.2 
      @types/react-native: ^0.57.65 => 0.57.65 
      @xstate/react: ^0.8.1 => 0.8.1 
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
      react-navigation: ^3.12.1 => 3.13.0 
    npmGlobalPackages:
      expo-cli: 3.7.1
```

**Comment by Wout-Vanneste-student** [comment] 2019-11-20 14:31
Working on a project and I get this error a lot of times.

If I don't do anything on the app, it doesn't happen all the time, or it takes a lot of time before the error occurs.
If I actually do something on the app (in my example, signing up a user to my firebase), the error pops up a few moments later.

Some more information about my environment:
![image](https://user-images.githubusercontent.com/44393610/69247224-5a90b400-0baa-11ea-8c74-d448dbb121d6.png)

Any ways to work around this error?

**Comment by yashank09** [comment] 2019-11-24 12:51
Hey guys, randomly started facing the same issue recently. I was wondering if this is an OS specific issue? I am viewing expo on my android app.

**Comment by rgoulter** [comment] 2019-11-24 13:49
This isn't an OS specific issue.

It seems it's just a case of one of the servers not graciously handling a socket error. (In Node v8, socket errors had a default error handler; since Node v10, they don't).
Easiest way to run into this error (as is pointed out upthread) is to just close/lock your phone, and wait for a few minutes.

**Comment by Jordhan-Carvalho** [comment] 2019-11-25 18:53
The error appears to occur only if you are using a real mobile device.

**Comment by JimVanEeden** [comment] 2019-11-26 08:01
> The error appears to occur only if you are using a real mobile device.

This is definitely not the case for me, both with IOS and Android simulators I experience this problem.

**Comment by yashank09** [comment] 2019-11-26 08:04
Okay so just upgrading my expo cli somehow helped... I understand this is a socket issue but `npm -g install expo` did the magic somehow. A temp fix I can think of is using your Android phone on Caine caffeine mode or just put the screen to never sleep?

**Comment by Slapbox** [comment] 2019-11-26 20:33
@yashank09 there's been many times I thought it helped, just to find it did not. Are you really sure it helped? If so, what version did you start on and what version is working better for you?

**Comment by SPineapple** [comment] 2019-12-13 09:04
I am having the same issue when I ' expo login '  I cannot login in my Terminal even though I can sign-in in Expo website . 

read ECONNRESET
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)


And I need to login because of expo notification feature, please help.

**Comment by Slapbox** [comment] 2019-12-13 20:12
@SPineapple I think that's a distinct/different issue. You might want to see if there's another thread of that specifically, or if there's not, open a new issue. Make sure that your firewall isn't blocking the request first though.

**Comment by arnaud-cortisse** [comment] 2019-12-14 09:33
I used to encounter this issue a lot. 
Lately I've been using an Android phone instead of an emulator and I've never encountered it again...

**Comment by Slapbox** [comment] 2019-12-14 19:24
Weird. I had this issue exclusively with a physical phone.

**Comment by angel-luis** [comment] 2019-12-16 11:23
Well, I've noted that it only happens with my Xiaomi phone. With the iPod Touch works fine.

**Comment by kevgrig** [comment] 2019-12-18 18:46
Great news, this issue is fixed for me with expo-cli 3.11.2 based on PR #1368. I upgraded expo-cli and then started with `expo start -c`.

It seems what was happening was that log messages would get split into chunks and if a chunk happened to be a string with an integer, it would get coerced into an integer and the `match` method wouldn't exist. The fix was to skip the `match` check if the chunk isn't a string. This happened to me consistently because I had log statements that would dump large, prettified JSONs which included lots of integers with whitespace around them. I suspect the randomness of this issue for some people depended on various factors of chunk size, debug log contents, application behavior, etc.

**Comment by natecartwright** [comment] 2020-01-03 00:23
Still get this error on expo-cli 3.11.3, after an idle period or device "sleep":

INFO
16:17
Starting Metro Bundler on port 19001.
INFO
16:17
Tunnel ready.
INFO
16:17
Building JavaScript bundle: finished in 410ms.
ERROR
16:21
events.js:186
      throw
ERROR
16:21
 er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}

**Comment by kevgrig** [comment] 2020-01-03 04:58
@natecartwright Did you do `expo start` with the clean (`-c`) option? Also, the ECONNRESET is one of the symptoms of the problem but could also be a symptom of a different problem; do you have any other error stacks anywhere related to `TypeError: chunk.msg.match is not a function` or a different error?

**Comment by vujevits** [comment] 2020-02-25 09:53
I have the same error all the time. Using ios simulator, expo version 3.11.1. I'll try for some time with the `-c` option.
```
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:183:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
```

**Comment by kevgrig** [comment] 2020-02-25 18:46
@vujevits One cause of this problem was fixed in [3.11.2](https://github.com/expo/expo-cli/issues/519#issuecomment-567160385) so please upgrade and try again.

**Comment by vujevits** [comment] 2020-02-26 11:54
thanks @kevgrig , upgrading solved the issue.

**Comment by katontech** [comment] 2020-03-30 07:59
I have the same problem during `expo start` very often.
Also, there is no difference with `expo start --clear`.
I started using expo-cli 3.11.3 and at the time this problem did not occur, but it does in the latest version.
My current environment is as follows.
>   Expo CLI 3.16.1 environment info:
>     System:
>       OS: Windows 10 10.0.18363
>     Binaries:
>       Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
>       Yarn: 1.22.4 - C:\Users\masa\AppData\Roaming\npm\yarn.CMD
>       npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
>     IDEs:
>       Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
>     npmPackages:
>       expo: ~36.0.0 => 36.0.2 
>       react: ~16.9.0 => 16.9.0 
>       react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4

**Comment by EvanBacon** [comment] 2020-04-28 03:58
This issue will continue to be fixed and broken again. Currently it's fixed in the latest, if someone has this problem again please feel free to open a new issue.

**Closed by EvanBacon** 2020-04-28 03:58 UTC
