### ISSUE TITLE
`expo publish` error formatting needs improvement

### ISSUE THREAD

**Issue by esamelson** [expo/expo-cli#79] opened 2018-10-09 19:04 UTC
Currently, if your code has a syntax error, `expo publish` just displays the stringified error object and does not filter out the color codes. This produces output that is difficult for humans to parse, e.g.

```
500 - "{\"type\":\"TransformError\",\"snippet\":\"\\u001b[0m \\u001b[90m 42 | \\u001b[39m getAsync\\u001b[33m:\\u001b[39m () \\u001b[33m=>\\u001b[39m {\\n \\u001b[90m 43 | \\u001b[39m\\n\\u001b[31m\\u001b[1m>\\u001b[22m\\u001b[39m\\u001b[90m 44 | \\u001b[39m \\u001b[36mconst\\u001b[39m hasit \\u001b[33m=\\u001b[39m await getPermission(\\u001b[33mPermissions\\u001b[39m\\u001b[33m.\\u001b[39m\\u001b[33mLOCATION\\u001b[39m)\\u001b[33m;\\u001b[39m\\n \\u001b[90m | \\u001b[39m \\u001b[31m\\u001b[1m^\\u001b[22m\\u001b[39m\\n \\u001b[90m 45 | \\u001b[39m \\u001b[36mif\\u001b[39m (\\u001b[33m!\\u001b[39mhasit) {\\n \\u001b[90m 46 | \\u001b[39m \\u001b[36mreturn\\u001b[39m \\u001b[36mnull\\u001b[39m\\u001b[33m;\\u001b[39m\\n \\u001b[90m 47 | \\u001b[39m }\\u001b[0m\",\"lineNumber\":44,\"column\":20,\"filename\":\"/Users/evanbacon/Documents/GitHub/bute/client/src/rematch/models.js\",\"errors\":[{\"description\":\"SyntaxError: /Users/evanbacon/Documents/GitHub/bute/client/src/rematch/models.js: await is a reserved word (44:20)\",\"filename\":\"/Users/evanbacon/Documents/GitHub/bute/client/src/rematch/models.js\",\"lineNumber\":44}],\"name\":\"SyntaxError\",\"message\":\"SyntaxError: /Users/evanbacon/Documents/GitHub/bute/client/src/rematch/models.js: await is a reserved word (44:20)\",\"stack\":\"SyntaxError: /Users/evanbacon/Documents/GitHub/bute/client/src/rematch/models.js: await is a reserved word (44:20)\\n\\u001b[0m \\u001b[90m 42 | \\u001b[39m getAsync\\u001b[33m:\\u001b[39m () \\u001b[33m=>\\u001b[39m {\\n \\u001b[90m 43 | \\u001b[39m\\n\\u001b[31m\\u001b[1m>\\u001b[22m\\u001b[39m\\u001b[90m 44 | \\u001b[39m \\u001b[36mconst\\u001b[39m hasit \\u001b[33m=\\u001b[39m await getPermission(\\u001b[33mPermissions\\u001b[39m\\u001b[33m.\\u001b[39m\\u001b[33mLOCATION\\u001b[39m)\\u001b[33m;\\u001b[39m\\n \\u001b[90m | \\u001b[39m \\u001b[31m\\u001b[1m^\\u001b[22m\\u001b[39m\\n \\u001b[90m 45 | \\u001b[39m \\u001b[36mif\\u001b[39m (\\u001b[33m!\\u001b[39mhasit) {\\n \\u001b[90m 46 | \\u001b[39m \\u001b[36mreturn\\u001b[39m \\u001b[36mnull\\u001b[39m\\u001b[33m;\\u001b[39m\\n \\u001b[90m 47 | \\u001b[39m }\\u001b[0m\\n at Parser.pp$5.raise (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:4454:13)\\n at Parser.pp$3.checkReservedWord (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:4347:10)\\n at Parser.pp$3.parseIdentifier (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:4324:10)\\n at Parser.pp$3.parseExprAtom (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:3648:21)\\n at Parser.parseExprAtom (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:7238:22)\\n at Parser.pp$3.parseExprSubscripts (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:3494:19)\\n at Parser.pp$3.parseMaybeUnary (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:3474:19)\\n at Parser.pp$3.parseExprOps (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:3404:19)\\n at Parser.pp$3.parseMaybeConditional (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:3381:19)\\n at Parser.pp$3.parseMaybeAssign (/Users/evanbacon/Documents/GitHub/bute/client/node_modules/babylon/lib/index.js:3344:19)\"}"

```
Ideally we'd parse these and display the error in a cleaner fashion, like we do with `expo start`.

**Comment by fson** [comment] 2019-11-12 16:02
Closing this since the bug has already been fixed earlier and I just confirmed that errors are now printed correctly.

**Closed by fson** 2019-11-12 16:02 UTC
Labels: bug
