### ISSUE TITLE
Unable to use typescript for custom platform (.native.tsx) with  @expo/next-adapter 

### ISSUE THREAD

**Issue by alantulais** [expo/expo-cli#2911] opened 2020-11-18 07:08 UTC
## Description

After setting up with "next" and @expo/next-adapter, babel is unable to locate platform specific code for extensions .ts and .tsx.

## Expected Behavior

Usage of platform-specific files (.native, .android, .ios) with typescript

## Observed Behavior

babel only uses the main ts/tsx file

**Comment by EvanBacon** [comment] 2020-11-18 09:20
`.native.*` should only work on native platforms. Please provide a minimal repro as I cannot reproduce given the provided info.

**Comment by EvanBacon** [comment] 2020-11-19 13:43
closing, please feel free to reopen after providing a minimal reproducible example.

**Closed by EvanBacon** 2020-11-19 13:43 UTC
Labels: Platform: web, needs more info

**Comment by Ngomana** [comment] 2021-03-07 22:50
I also have the same issue. I created and expo project using typescript `minimal with typescript` and followed the documentation on how to add next on your project and got the same error as above.
