### ISSUE TITLE
sourceExts not working in cli 3.x

### ISSUE THREAD

**Issue by DavidSvetlik** [expo/expo-cli#875] opened 2019-07-24 15:25 UTC
## Description

Hi, I am getting an error "While resolving module...  could not be found within the package" because bundler won't find jsx files even though they are set via `sourceExts`.

## Expected Behavior

Expected behavior is for `sourceExts` in metro.config.js to work as described in documentation [here](https://facebook.github.io/metro/docs/en/configuration#sourceexts), meaning bundler will include jsx files.

## Observed Behavior

```
Unable to resolve "./src/components/app" from "App.js"
Failed building JavaScript bundle.
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```
Expo CLI 3.0.4 environment info:
    System:
      OS: Windows 10
    Binaries:
      npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842
```
(I am not using Android Studio currently).

Also:
```
node 12.7.0
npm 6.5.0
expo-cli 3.0.4
```

## Reproducible Demo

Here's my config file:

```
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { assetExts, sourceExts }
  } = await getDefaultConfig();

  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer')
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [ ...sourceExts, 'jsx', 'svg' ],
    },
  };
})();
```

**Comment by darrell-roberts** [comment] 2019-07-24 16:49
I had the same issue when updated to v3.0.4 of expo-cli. Svg files could no longer be imported. I had to go back to expo-cli 2.21.1. 

metro.config.js
```javascript
const { getDefaultConfig } = require('metro-config');

module.exports = (async () => {
  const {
    resolver: { sourceExts, assetExts }
  } = await getDefaultConfig();
  return {
    transformer: {
      babelTransformerPath: require.resolve('react-native-svg-transformer')
    },
    resolver: {
      assetExts: assetExts.filter(ext => ext !== 'svg'),
      sourceExts: [...sourceExts, 'svg']
    }
  };
})();
```

app.json
```json
{
  "expo": {
  // Snip
    "packagerOpts": {
      "config": "metro.config.js"
    }
  }
}
```

**Comment by bayoremit** [comment] 2019-07-24 20:58
+ 1

**Comment by DavidSvetlik** [comment] 2019-07-25 10:57
I described a quick temporary workaround here:
https://github.com/expo/expo-cli/issues/191#issuecomment-514696692

**Comment by mrangta** [comment] 2019-07-26 10:14
> I had the same issue when updated to v3.0.4 of expo-cli. Svg files could no longer be imported. I had to go back to expo-cli 2.21.1.
> 
> metro.config.js
> 
> ```js
> const { getDefaultConfig } = require('metro-config');
> 
> module.exports = (async () => {
>   const {
>     resolver: { sourceExts, assetExts }
>   } = await getDefaultConfig();
>   return {
>     transformer: {
>       babelTransformerPath: require.resolve('react-native-svg-transformer')
>     },
>     resolver: {
>       assetExts: assetExts.filter(ext => ext !== 'svg'),
>       sourceExts: [...sourceExts, 'svg']
>     }
>   };
> })();
> ```
> 
> app.json
> 
> ```json
> {
>   "expo": {
>   // Snip
>     "packagerOpts": {
>       "config": "metro.config.js"
>     }
>   }
> }
> ```

Here is the solution for the expo-cli 3.0.4, just add `one` line in the app.json
`"packagerOpts": {
      "config": "metro.config.js",
      "sourceExts": ["js", "jsx", "svg", "svgx"]
    }`

it worked for me, hope it will work for you too :)

**Comment by darrell-roberts** [comment] 2019-07-26 14:55
@DavidSvetlik @mrangta That workaround fixes the issue. Thanks.

**Comment by intptr-t** [comment] 2019-07-31 12:29
As a result of processing "overrideConfigWithArguments() --> mergeConfig()" in `metro-config/src/loadConfig.js`,

the following contents take precedence
```
sourceExts: ['expo.js', 'expo.ts', 'expo.tsx', 'expo.json', 'js', 'json', 'ts', 'tsx']
```
in `@expo/xdl/build/Project.js`.

metro.config.js "resolver.sourceExts" is not merged.

## Environment

```
$ expo diagnostics
  Expo CLI 3.0.6 environment info:
    System:
      OS: macOS 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nodebrew/current/bin/node
      npm: 6.10.2 - ~/.nodebrew/current/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.1 => 34.0.3 
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.0.6
```

```
metro-config@0.51.1
```

**Comment by fson** [comment] 2019-11-08 15:11
Closing this as a duplicate of #1019.

Currently `sourceExts` and `assetsExts` values specified in `metro.config.js` are ignored, because the command-line flags used by Expo CLI take precedence over them. To change these settings in a managed Expo app, you should specify them in `expo.packagerOpts` in the `app.json` file, for example:

app.json
```
{
  "expo": {
    ...
    "packagerOpts": {
      "sourceExts": ["jsx"]
    }
  }
}
```

**Closed by fson** 2019-11-08 15:11 UTC
