### ISSUE TITLE
Error on expo start

### ISSUE THREAD

**Issue by manoramahp** [expo/expo-cli#47] opened 2018-09-26 05:32 UTC
## Description

Create a new app with expo init and start it with expo start

## Expected Behavior

Expo Dev Tools, should pop up in the web browser automatically when run expo start

## Observed Behavior

[13:28:27] Starting Metro Bundler on port 19001.
[13:28:27] Metro Bundler ready.
[13:28:35] Tunnel ready.
[13:28:35] Expo DevTools is running at http://localhost:19002
[13:28:35] Opening DevTools in the browser... (press shift-d to disable)
Error: spawn cmd ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Environment

Environment:
  OS: Windows 7
  Node: 8.11.3
  Yarn: Not Found
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

**Comment by fson** [comment] 2018-10-09 15:51
Can you check, if `"%SystemRoot%\system32;"` is included in your PATH variable? See https://github.com/sindresorhus/opn/issues/56#issuecomment-324254767

**Comment by jobinpaulk** [comment] 2019-05-03 16:51
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by msalman95** [comment] 2019-05-05 10:57
![image](https://user-images.githubusercontent.com/39700096/57192843-a05d9600-6f52-11e9-87bc-105e785974fb.png)
Cannot get around this error. Anybody knows the reason for this?

**Comment by ccheever** [comment] 2019-10-09 19:34
Hi-- @imdanielpiva @manoramahp 

I'm trying this on a Windows machine and I'm not able to repro across a couple different versions of node. Can you let me know if this is still happening?

Also, are you by any chance using WSL? Sometimes strange things happen under WSL.

**Comment by imdanielpiva** [comment] 2019-10-10 13:51
@ccheever Unfortunately I can't tell you if this problem is still happening, as I don't have access anymore to the setup I've mentioned at the time while back.

PS.: I've been using the recent versions of expo-cli on Mac and everything is working perfectly!

**Comment by fson** [comment] 2019-11-14 21:08
Glad to hear that it's working for you now!

It seems likely that this particular issue on Windows would also be fixed by now. After the issue was last reported, we've switched to another library for opening the browser in https://github.com/expo/expo-cli/pull/565.

**Closed by fson** 2019-11-14 21:08 UTC
Labels: bug, question

**Comment by stevematdavies** [comment] 2020-03-30 08:57
Why is this closed, the issue is not solved

**Comment by Arun-Mo** [comment] 2020-05-28 15:11
> ![image](https://user-images.githubusercontent.com/39700096/57192843-a05d9600-6f52-11e9-87bc-105e785974fb.png)
> Cannot get around this error. Anybody knows the reason for this?

getting same error did you solved it?
