### ISSUE TITLE
After running app insteed web ui black screen

### ISSUE THREAD

**Issue by Zimovets** [expo/expo-cli#739] opened 2019-06-16 18:47 UTC
![Аннотация 2019-06-16 180955](https://user-images.githubusercontent.com/28711392/59568181-e5abd200-907f-11e9-9c9f-5bc224fcb82e.jpg)

System:
windows 10
node 10.16.0
expo 32.0.0

**Comment by Zimovets** [comment] 2019-06-17 20:04
![Аннотация 2019-06-17 225657](https://user-images.githubusercontent.com/28711392/59632658-5b34a280-9153-11e9-9ef8-34a70a5bcbdf.jpg)

expo-cli v 2.20
I recently reinstall my windows and met this problem, before that it works properly, step-by-step
- clone project
- using npm install packages
- install globally expo-cli package
- run project 
- automatically chrome tab was open and I saw this result 
you can see some problem packages in the screenshot maybe this is it?
I don't know how someone can reproduce this behavior unfortunately

**Comment by Zimovets** [comment] 2019-06-17 21:19
reinstall expo-cli globally but got the same problem

**Comment by EvanBacon** [comment] 2019-10-04 17:44
Web support is still in beta. Closing for now as so much has changed. Please feel free to reopen with a repro if this continues. We'll also look into supporting more windows tests in the future.

**Closed** 2019-10-05 18:31 UTC

**Comment by nihiluis** [comment] 2020-01-11 22:04
@EvanBacon why is this issue closed? just because it has no reproduce repo? This issue occurs at random.
