### ISSUE TITLE
Next.js + Expo ReferenceError: setImmediate is not defined using createBottomTabNavigator

### ISSUE THREAD

**Issue by jdorado** [expo/expo-cli#2145] opened 2020-05-20 04:46 UTC
## Description

Building a simple PWA with Bottom Nav Tab navigation gives error when using react-navigation-tabs. The following is the test code running in a Next.js page. It gives error while in the Expo Mobile app (or web version with standard webpack works).

```
import * as React from 'react';
import { Text, View } from 'react-native';
import {createAppContainer, createSwitchNavigator} from 'react-navigation';
import {createBottomTabNavigator} from "react-navigation-tabs";

function HomeScreen() {
    return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            <Text>Home!</Text>
        </View>
    );
}

function SettingsScreen() {
    return (
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
            <Text>Settings!</Text>
        </View>
    );
}

const TabNavigation = createBottomTabNavigator(
    {
        Home: HomeScreen,
        Settings: SettingsScreen,
    }
);

export default createAppContainer(TabNavigation);
```

## Observed Behavior

```
Unhandled Runtime Error
ReferenceError: setImmediate is not defined

Call Stack
AnimatedOperator.__markUpdated
node_modules/react-native-reanimated/src/core/AnimatedNode.js (138:6)
AnimatedOperator.__dangerouslyRescheduleEvaluate
node_modules/react-native-reanimated/src/core/AnimatedNode.js (132:9)
AnimatedParam.__addChild
node_modules/react-native-reanimated/src/core/AnimatedNode.js (182:12)
AnimatedOperator.__attach
node_modules/react-native-reanimated/src/core/AnimatedNode.js (98:17)
AnimatedOperator.__addChild
node_modules/react-native-reanimated/src/core/AnimatedNode.js (174:11)
AnimatedCond.__attach
node_modules/react-native-reanimated/src/core/AnimatedNode.js (98:17)
AnimatedCond.__addChild
node_modules/react-native-reanimated/src/core/AnimatedNode.js (174:11)
AnimatedFunction.__attach
node_modules/react-native-reanimated/src/core/AnimatedNode.js (98:17)
new AnimatedFunction
node_modules/react-native-reanimated/src/core/AnimatedFunction.js (23:9)
_construct
node_modules/@babel/runtime/helpers/construct.js (19:0)
createAnimatedFunction
node_modules/react-native-reanimated/src/core/AnimatedFunction.js (42:19)
eval
node_modules/react-native-reanimated/src/derived/interpolate.js (17:43)
Module../node_modules/react-native-reanimated/src/derived/interpolate.js
.next/static/development/pages/index.js (2714:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
webpack-internal:///./node_modules/react-native-reanimated/src/core/AnimatedValue.js (14:78)
Module../node_modules/react-native-reanimated/src/core/AnimatedValue.js
.next/static/development/pages/index.js (2558:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
webpack-internal:///./node_modules/react-native-reanimated/src/core/AnimatedEvent.js (22:73)
Module../node_modules/react-native-reanimated/src/core/AnimatedEvent.js
.next/static/development/pages/index.js (2426:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
node_modules/react-native-reanimated/src/base.js (1:0)
Module../node_modules/react-native-reanimated/src/base.js
.next/static/development/pages/index.js (2282:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
webpack-internal:///./node_modules/react-native-reanimated/src/Easing.js (7:63)
Module../node_modules/react-native-reanimated/src/Easing.js
.next/static/development/pages/index.js (2115:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
webpack-internal:///./node_modules/react-native-reanimated/src/Animated.js (11:65)
Module../node_modules/react-native-reanimated/src/Animated.js
.next/static/development/pages/index.js (2091:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
webpack-internal:///./node_modules/react-navigation-tabs/lib/module/views/CrossFadeIcon.js (17:81)
Module../node_modules/react-navigation-tabs/lib/module/views/CrossFadeIcon.js
.next/static/development/pages/index.js (4789:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
webpack-internal:///./node_modules/react-navigation-tabs/lib/module/views/BottomTabBar.js (24:73)
Module../node_modules/react-navigation-tabs/lib/module/views/BottomTabBar.js
.next/static/development/pages/index.js (4777:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
webpack-internal:///./node_modules/react-navigation-tabs/lib/module/navigators/createBottomTabNavigator.js (22:78)
Module../node_modules/react-navigation-tabs/lib/module/navigators/createBottomTabNavigator.js
.next/static/development/pages/index.js (4718:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
fn
.next/static/runtime/webpack.js (151:20)
eval
index.tsx (4:0)
Module../node_modules/react-navigation-tabs/lib/module/index.js
.next/static/development/pages/index.js (4706:1)
__webpack_require__
/_next/static/runtime/webpack.js (863:31)
```

**Comment by EvanBacon** [comment] 2020-05-21 17:38
This is a problem with Next.js. Duplicate of https://github.com/expo/expo/issues/7996

**Closed by EvanBacon** 2020-05-21 17:38 UTC
