### ISSUE TITLE
transportMode is an experimental option, meaning its usage could potentially change without warning Web Bundling JavaScript [======= ] 10%Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by Rayhan0Islam0Shagor** [expo/expo-cli#4607] opened 2022-11-24 06:50 UTC
### Summary

When I run for the web this throw this kind of error.

### Environment

![image](https://user-images.githubusercontent.com/67514865/203713624-08059148-5a65-4fee-ac0b-7a73d5cd2fad.png)

### Please specify your device/emulator/simulator platform, model and version

Node V18.12.1

### Error output

![image](https://user-images.githubusercontent.com/67514865/203713242-9a32baec-dfbd-46d1-8c57-2088914064a2.png)

### Reproducible demo or steps to reproduce from a blank project

sdas

**Comment by vijeethLooperex** [comment] 2022-11-24 08:52
I also got same problem

**Comment by byCedric** [comment] 2022-11-24 16:15
Closing, duplicate of https://github.com/expo/expo-cli/issues/4575#issuecomment-1295006089

**Closed by byCedric** 2022-11-24 16:15 UTC
Labels: needs review
