### ISSUE TITLE
Error: Invalid sdkVersion

### ISSUE THREAD

**Issue by caelistic** [expo/expo-cli#1632] opened 2020-03-03 10:00 UTC
## Description

When I start my project via `expo start` I get the following error: `Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 33.0.0, 7.0.0, 8.0.0, 9.0.0`.
I just created a new project with the latest expo-cli version (SDK 36).

## Expected Behavior

I started the project via `expo start` and exptected that I can start the expo app on my device.

## Observed Behavior

I got and invalid sdkError.

```
Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 33.0.0, 7.0.0, 8.0.0, 9.0.0
```

## Environment

  Expo CLI 3.13.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD

Samsung and/or Android Emulator, Galaxy S9 

package.json:

```
{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-gesture-handler": "~1.5.0",
    "react-native-reanimated": "~1.4.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-unimodules": "~0.7.0",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "~7.6.0",
    "@types/react": "~16.9.0",
    "@types/react-native": "~0.60.23",
    "babel-preset-expo": "~8.0.0",
    "jest-expo": "~36.0.1",
    "typescript": "~3.6.3"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

app.json:

```
{
  "name": "test",
  "displayName": "test",
  "expo": {
    "name": "test",
    "slug": "test",
    "privacy": "unlisted",
    "sdkVersion": "36.0.0",
    "version": "1.0.0",
    "entryPoint": "node_modules/expo/AppEntry.js",
    "platforms": [
      "ios",
      "android",
      "web"
    ]
  }
}
```

I un- and reinstalled nodejs and nvm. Deleted all cache folders. Started expo with `-c` command.
This error only occurs on my laptop and not on my azure VM or any other computer.

## Reproducible Demo

Just initialize a new project via `expo init`, select the `minimal (typescript)` template, install everything and start the project. It always fails with the mentioned error.

**Comment by jkhales** [comment] 2020-03-10 23:54
Hi, there were a few issues with this in the last week that have been fixed. Can you confirm whether this is still causing you difficulty?

**Comment by caelistic** [comment] 2020-03-11 07:51
Hi @jkhales, after deleting node_modules and installing expo-cli 3.13.5 everything seems to work properly again.
Thank you very much!
What was the cause?

**Comment by jkhales** [comment] 2020-03-11 12:09
That's fantastic to hear, @caelistic. I'd have to know more information in order to diagnose the exact problem.

Thanks for working with us!

**Comment by gustavomr** [comment] 2020-03-11 12:33
I'm getting the same error.

How I did:

Installed from npm install --global expo-cli
Then expo init my-project
Then expo start

Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 3

Doing expo-cli --version 
3.13.5

**Comment by jkhales** [comment] 2020-03-11 12:38
Hi, thanks for letting us know. 

Couldn't reproduce this just now on a fresh install. 

Is there anything else you can tell us about your setup that maybe impacting the issue? Are you on OSX?

**Comment by gustavomr** [comment] 2020-03-11 13:05
> Hi, thanks for letting us know.
> 
> Couldn't reproduce this just now on a fresh install.
> 
> Is there anything else you can tell us about your setup that maybe impacting the issue? Are you on OSX?

I'm using Ubuntu 18 and did it on a fresh install.

**Comment by jkhales** [comment] 2020-03-11 14:43
We tried it on an ubuntu dist as well and couldn't repro it. Are you connected to the internet? One possibility is that the cache isn't refreshing.

**Comment by gustavomr** [comment] 2020-03-11 14:47
> We tried it on an ubuntu dist as well and couldn't repro it. Are you connected to the internet? One possibility is that the cache isn't refreshing.

Yes, I'm connected on internet. Maybe firewall? Cache? How can I force update cache?

Thanks.

**Comment by wkozyra95** [comment] 2020-03-11 15:22
Can you run `expo doctor`?
If it won't fix that problem, please post the output of that command here.

**Comment by gustavomr** [comment] 2020-03-11 16:04
> Can you run `expo doctor`?
> If it won't fix that problem, please post the output of that command here.

expo doctor
Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 33.0.0, 7.0.0, 8.0.0, 9.0.0

**Comment by gustavomr** [comment] 2020-03-11 17:23
I manually copy this file:

https://github.com/expo/expo-cli/blob/master/packages/xdl/caches/versions.json

And put on my .cache/expo directory and worked. I don't know why.

**Comment by gustavomr** [comment] 2020-03-12 14:53
I fixed it partially. I can run my expo app in 36.0.0 and still getting this error. 

What I did was exclude the expo app on my simulator device and install again.

**Comment by jmongtalvof** [comment] 2020-03-12 18:52
I am Having the same issue:


Installed from npm install --global expo-cli
Then expo init my-project
Then expo start

Error: Invalid sdkVersion. Valid options are 10.0.0, 11.0.0, 12.0.0, 13.0.0, 14.0.0, 15.0.0, 16.0.0, 17.0.0, 18.0.0, 19.0.0, 20.0.0, 21.0.0, 22.0.0, 23.0.0, 24.0.0, 25.0.0, 26.0.0, 27.0.0, 28.0.0, 29.0.0, 30.0.0, 31.0.0, 32.0.0, 33.0.0, 7.0.0, 8.0.0, 9.0.0

expo-cli --version
3.13.6

yarn -v
1.21.1

npm -v
6.13.7

node -v
v13.10.1

Expo CLI 3.13.6 environment info:
System:
OS: OSX Mojave 10.14.6
npmPackages:
expo: ~36.0.0
react: 16.8.3,
react-native": https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz

**Comment by brentvatne** [comment] 2020-03-12 18:54
@jmongtalvof - can you share the contents of the `~/.expo/cache` directory please?

**Comment by jmongtalvof** [comment] 2020-03-12 18:56
inside `~/.expo/cache` There is a Json file: `versions.json`

**Comment by jmongtalvof** [comment] 2020-03-12 18:58
@brentvatne  Here is what's inside of it `{"androidUrl":"https://d1ahtucjixef4r.cloudfront.net/Exponent-2.11.2.apk","androidVersion":"2.11.2","iosUrl":"https://dpq5q02fu5f55.cloudfront.net/Exponent-2.11.1.tar.gz","iosVersion":"2.11.1","sdkVersions":{"10.0.0":{"expoReactNativeTag":"sdk-10.0.0","exponentReactNativeTag":"sdk-10.0.0","facebookReactNativeVersion":"0.33.0","isDeprecated":true},"11.0.0":{"expoReactNativeTag":"sdk-11.0.0","exponentReactNativeTag":"sdk-11.0.0","facebookReactNativeVersion":"0.36.0","isDeprecated":true},"12.0.0":{"expoReactNativeTag":"sdk-12.0.0","exponentReactNativeTag":"sdk-12.0.0","facebookReactNativeVersion":"0.37.0","isDeprecated":true},"13.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.12.1-sdk13.0.0-f2251910-2ae0-4cc9-9cd0-4c28771fef12.tar.gz","androidExponentViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.12.1-sdk13.0.0-f2251910-2ae0-4cc9-9cd0-4c28771fef12.tar.gz","expoReactNativeTag":"sdk-13.0.0","exponentReactNativeTag":"sdk-13.0.0","facebookReactNativeVersion":"0.40.0","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.12.2-sdk13.0.0-15988a32-c353-4625-a704-a430f509f621.tar.gz","iosExponentViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.12.2-sdk13.0.0-15988a32-c353-4625-a704-a430f509f621.tar.gz","isDeprecated":true},"14.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.13.2-sdk14.0.0-5d431a7c-7837-4793-96f3-a1a131b6eadf.tar.gz","androidExponentViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.13.2-sdk14.0.0-5d431a7c-7837-4793-96f3-a1a131b6eadf.tar.gz","expoReactNativeTag":"sdk-14.0.0","exponentReactNativeTag":"sdk-14.0.0","facebookReactNativeVersion":"0.41.0","facebookReactVersion":"~15.4.0","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.13.1-sdk14.0.0-06dab271-a23b-436f-a19e-1c86c16067b9.tar.gz","iosExponentViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.13.1-sdk14.0.0-06dab271-a23b-436f-a19e-1c86c16067b9.tar.gz","isDeprecated":true},"15.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.14.0-sdk15.0.0-c07a9392-71db-4330-8452-98080b6b52f1.tar.gz","expoReactNativeTag":"sdk-15.0.0","facebookReactNativeVersion":"0.42.0","facebookReactVersion":"~15.4.0","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.14.3-sdk15.0.0-9cc802d5-6c7b-4b26-8495-bd86d1450edf.tar.gz","isDeprecated":true},"16.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.15.1-sdk16.0.0-2448b7f4-9b6a-4fd0-906d-8bd7da336bd7.tar.gz","expoReactNativeTag":"sdk-16.0.0","facebookReactNativeVersion":"0.43.0","facebookReactVersion":"16.0.0-alpha.6","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.15.2-sdk16.0.0-df18e714-3618-4db8-81db-48efa205fba6.tar.gz","iosVersion":"1.15.2","isDeprecated":true},"17.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.16.1-sdk17.0.0-87570a36-13ff-4017-9b89-6c9930b78572.tar.gz","expoReactNativeTag":"sdk-17.0.0","facebookReactNativeVersion":"0.44.0","facebookReactVersion":"16.0.0-alpha.6","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.16.2-sdk17.0.0-b5bce87c-1a42-4b6d-888f-877f855c9680.tar.gz","iosVersion":"1.16.2","isDeprecated":true},"18.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.17.0-sdk18.0.0-4680412d-04c4-47ed-9161-88e01d76be96.tar.gz","expoReactNativeTag":"sdk-18.0.0","facebookReactNativeVersion":"0.45.0","facebookReactVersion":"16.0.0-alpha.12","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.17.0-sdk18.0.0-b4aff885-a9a8-4733-9fa9-ec28bef01e15.tar.gz","iosVersion":"1.17.0","isDeprecated":true},"19.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.18.4-sdk19.0.0-3fb414c9-8696-4966-a0ac-9ca424242424.tar.gz","expoReactNativeTag":"sdk-19.0.0","facebookReactNativeVersion":"0.46.1","facebookReactVersion":"16.0.0-alpha.12","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.18.2-sdk19.0.0-3fabbbb7-61b3-4a1e-9932-12d0aa6af276.tar.gz","iosVersion":"1.18.2","isDeprecated":true},"20.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.19.1-sdk20.0.0-5b613054-1239-439f-9c3a-0aad67cbe39a.tar.gz","expoReactNativeTag":"sdk-20.0.0","facebookReactNativeVersion":"0.47.1","facebookReactVersion":"16.0.0-alpha.12","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.19.2-sdk20.0.0-71c3afdd-3b31-4722-9657-bbf07ea645d8.tar.gz","iosVersion":"1.19.2","isDeprecated":true,"releaseNoteUrl":"https://blog.expo.io/expo-sdk-v20-0-0-is-now-available-79f84232a9d1"},"21.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v1.20.0-sdk21.0.0-38791499-fe99-4600-950d-cf7e2e85cea9.tar.gz","expoReactNativeTag":"sdk-21.0.0","facebookReactNativeVersion":"0.48.4","facebookReactVersion":"16.0.0-alpha.12","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v1.20.5-sdk21.0.0-11e2eb3f-807e-48d4-8685-b0694f874637.tar.gz","iosVersion":"1.20.5","isDeprecated":true,"releaseNoteUrl":"https://blog.expo.io/expo-sdk-21-0-0-is-now-available-be33b79921b7"},"22.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.0.0-sdk22.0.0-7432f75c-05a1-4826-a456-02875e338222.tar.gz","expoReactNativeTag":"sdk-22.0.0","facebookReactNativeVersion":"0.49.3","facebookReactVersion":"16.0.0-beta.5","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.0.4-sdk22.0.0-10110e7c-e9b1-43e6-b7e0-8a0e971480e8.tar.gz","iosVersion":"2.0.4","isDeprecated":true,"releaseNoteUrl":"https://blog.expo.io/expo-sdk-v22-0-0-is-now-available-7745bfe97fc6"},"23.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.1.2-sdk23.0.0-d47f172b-1ed3-4c8f-9e48-239052c678b6.tar.gz","expoReactNativeTag":"sdk-23.0.0","facebookReactNativeVersion":"0.50.3","facebookReactVersion":"16.0.0","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.1.4-sdk23.0.0-f67c5bc3-4a27-40f6-8686-91e8f868a145.tar.gz","iosVersion":"2.1.4","isDeprecated":true,"releaseNoteUrl":"https://blog.expo.io/expo-sdk-v23-0-0-is-now-available-be0a8c655414"},"24.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.2.0-sdk24.0.0-16620828-4df4-4e2d-b0af-5dc1352b82cb.tar.gz","expoReactNativeTag":"sdk-24.0.0","facebookReactNativeVersion":"0.51.0","facebookReactVersion":"16.0.0","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.2.1-sdk24.0.0-36ff2264-629d-44df-a819-8c982454e5e8.tar.gz","iosVersion":"2.2.1","isDeprecated":true,"releaseNoteUrl":"https://blog.expo.io/expo-sdk-v24-0-0-is-now-available-bfcac3b50d51"},"25.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.3.0-sdk25.0.0-0c32461b-a7c6-4ddc-b85b-32a80c4f18d9.tar.gz","expoReactNativeTag":"sdk-25.0.0","facebookReactNativeVersion":"0.52.0","facebookReactVersion":"16.2.0","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.3.3-sdk25.0.0-e7a4361a-631d-4caf-9692-1880d71c394a.tar.gz","iosVersion":"2.3.3","isDeprecated":true,"releaseNoteUrl":"https://blog.expo.io/expo-sdk-v25-0-0-is-now-available-714d10a8c3f7"},"26.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.4.0-sdk26.0.0-e63d9209-070c-4118-b06b-c60e82da0b66.tar.gz","expoReactNativeTag":"sdk-26.0.0","facebookReactNativeVersion":"0.54.2","facebookReactVersion":"16.3.0-alpha.1","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.4.4-sdk26.0.0-3bd935c7-cdd3-4002-8e44-4df857a675f2.tar.gz","iosVersion":"2.4.4","releaseNoteUrl":"https://blog.expo.io/expo-sdk-v26-0-0-is-now-available-2be6d9805b31"},"27.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.5.3-sdk27.0.0-408c8d77-8d1f-4784-b7b4-93826250663a.tar.gz","expoReactNativeTag":"sdk-27.0.0","facebookReactNativeVersion":"0.55.2","facebookReactVersion":"16.3.1","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.5.10-sdk27.0.0-7e6dd135-e649-48e2-ab7c-e76521ce6259.tar.gz","iosVersion":"2.5.10","releaseNoteUrl":"https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4"},"28.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.6.4-sdk28.0.0-9ba3198a-7d95-4769-9e16-178a37a70cae.tar.gz","expoReactNativeTag":"sdk-28.0.0","facebookReactNativeVersion":"0.55.4","facebookReactVersion":"16.3.1","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.6.8-sdk28.0.0-d3178d29-6e12-458b-bfeb-8b7538943b48.tar.gz","iosVersion":"2.6.8","releaseNoteUrl":"https://blog.expo.io/expo-sdk-v28-0-0-is-now-available-f30e8253b530"},"29.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.7.2-sdk29.0.0-54e8f46d-36a6-460f-b0f9-e1043f28b215.tar.gz","expoReactNativeTag":"sdk-29.0.0","expokitNpmPackage":"expokit@1.5.0","facebookReactNativeVersion":"0.55.4","facebookReactVersion":"16.3.1","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.7.8-sdk29.0.0-02bd60c8-f134-4f5e-b5c0-1898ffb57231.tar.gz","iosVersion":"2.7.8","releaseNoteUrl":"https://blog.expo.io/expo-sdk-v29-0-0-is-now-available-f001d77fadf"},"30.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.8.1-sdk30.0.0-0fde103b-be3d-43f9-bc48-3035aa136971.tar.gz","expoReactNativeTag":"sdk-30.0.0","expokitNpmPackage":"expokit@1.8.0","facebookReactNativeVersion":"0.55.4","facebookReactVersion":"16.3.1","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.8.4-sdk30.0.0-3de13133-1adc-4ba1-8569-a84011e570b4.tar.gz","iosVersion":"2.8.4","releaseNoteUrl":"https://blog.expo.io/expo-sdk-30-0-0-is-now-available-e64d8b1db2a7"},"31.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.9.2-sdk31.0.0-f0c63b44-0556-45f2-b4b9-ff5082f9ef72.tar.gz","expoReactNativeTag":"sdk-31.0.0","expokitNpmPackage":"expokit@31.1.0","facebookReactNativeVersion":"0.57.1","facebookReactVersion":"16.5.0","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.9.0-sdk31.0.0-250a3991-b623-4f9c-b07f-0b9ed7e8c4c9.tar.gz","iosVersion":"2.9.0","releaseNoteUrl":"https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49"},"32.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.10.8-sdk32.0.0-bca0f957-de78-44c8-91ed-f3151372d79d.tar.gz","expoReactNativeTag":"sdk-32.0.0","expokitNpmPackage":"expokit@32.1.1","facebookReactNativeVersion":"0.57.1","facebookReactVersion":"16.5.0","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.10.6-sdk32.0.0-e50ee83a-41bd-4965-b067-4c815a3b3fcc.tar.gz","iosVersion":"2.10.6","releaseNoteUrl":"https://blog.expo.io/expo-sdk-v32-0-0-is-now-available-6b78f92a6c52"},"33.0.0":{"androidExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/android-v2.11.2-sdk33.0.0-14eac386-52d3-401f-9daa-8f93307457f9.tar.gz","expoReactNativeTag":"sdk-33.0.0","expokitNpmPackage":"expokit@33.0.2","facebookReactNativeVersion":"0.59.8","facebookReactVersion":"16.8.3","iosExpoViewUrl":"https://s3.amazonaws.com/exp-exponent-view-code/ios-v2.11.0-sdk33.0.0-4b05019b-b5d6-454b-8350-09c2187b9f91.tar.gz","iosVersion":"2.11.0","packagesToInstallWhenEjecting":{"react-native-unimodules":"^0.4.0"}},"7.0.0":{"expoReactNativeTag":"sdk-7.0.0","exponentReactNativeTag":"sdk-7.0.0","facebookReactNativeVersion":"0.27.0","isDeprecated":true},"8.0.0":{"expoReactNativeTag":"sdk-8.0.0","exponentReactNativeTag":"sdk-8.0.0","facebookReactNativeVersion":"0.31.0","isDeprecated":true},"9.0.0":{"expoReactNativeTag":"sdk-9.0.0","exponentReactNativeTag":"sdk-9.0.0","facebookReactNativeVersion":"0.31.0","isDeprecated":true}},"starterApps":{"default":{"description":"Basic app with tab navigation.","version":"1.5.1"}},"templates":[{"description":"The Blank project template includes the minimum dependencies to run and an empty root component.","iconUrl":"https://d306o6r76fnu7o.cloudfront.net/template_icon_blank.png","id":"blank","name":"Blank","url":"https://d306o6r76fnu7o.cloudfront.net/blank-17.0.1.tar.gz","version":"17.0.1"},{"description":"The Tab Navigation project template includes several example screens.","iconUrl":"https://d306o6r76fnu7o.cloudfront.net/template_icon_tabs.png","id":"tabs","name":"Tab Navigation","url":"https://d306o6r76fnu7o.cloudfront.net/tabs-17.0.1.tar.gz","version":"17.0.1"}],"templatesv2":[{"description":"The Blank project template includes the minimum dependencies to run and an empty root component.","iconUrl":"https://d306o6r76fnu7o.cloudfront.net/template_icon_blank.png","id":"blank","name":"Blank","url":"https://d306o6r76fnu7o.cloudfront.net/blank-31.0.1.tar.gz","version":"31.0.1"},{"description":"The Tab Navigation project template includes several example screens.","iconUrl":"https://d306o6r76fnu7o.cloudfront.net/template_icon_tabs.png","id":"tabs","name":"Tab Navigation","url":"https://d306o6r76fnu7o.cloudfront.net/tabs-31.0.1.tar.gz","version":"31.0.1"}],"turtleSdkVersions":{"android":"33.0.0","ios":"33.0.0"}}
`

**Comment by jmongtalvof** [comment] 2020-03-12 19:10
Update: 

I fixed it by: 

to fix the issue:  
1. npm uninstall -g expo-cli --save
2. npm install -g expo-cli --save 
3. cd ~/.expo/cache
4. rm -rf everything that is in there
5. go back to your project
6. run expo start

**Comment by brentvatne** [comment] 2020-03-16 18:59
thanks @jmongtalvof for the update.

see this related issue: https://github.com/expo/expo-cli/issues/1632

**Closed by brentvatne** 2020-03-16 18:59 UTC
Labels: needs more info
