### ISSUE TITLE
Expo crashing on every file change

### ISSUE THREAD

**Issue by Arlen22** [expo/expo-cli#1258] opened 2019-11-22 19:32 UTC
## Description

I'm trying to setup an expo web project and I've gotten pretty far, although it's taken a while, but now I'm running into a snag where every time I save a file, the whole thing crashes and exits to terminal. 

```
TypeError: compilation.getPathWithInfo is not a function
    at /Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/node_modules/webpack/lib/HotModuleReplacementPlugin.js:287:26
    at SyncHook.eval (eval at create (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:16:1)
    at SyncHook.lazyCompileHook (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1361:37
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1304:27)
    at /Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:665:18
    at /Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1224:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/webpack/lib/Compilation.js:1216:28)
    at /Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/webpack/lib/Compiler.js:662:17
    at _done (eval at create (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:22)
    at /Users/arlen/.npm-packages/lib/node_modules/expo-cli/node_modules/react-dev-utils/ModuleNotFoundPlugin.js:114:15
```

## Environment

  Expo CLI 3.8.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.13.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.12.1 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: ^16.8.23 => 16.9.11 
      @types/react-native: ^0.57.65 => 0.57.65 
      expo: ^35.0.0 => 35.0.1 
      react: 16.8.3 => 16.8.3 
      react-native: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz => 0.59.8 
    npmGlobalPackages:
      expo-cli: 3.8.0

## Reproducible Demo

I'm pretty sure I just did expo init and chose the blank typescript template (if that's even a thing, not sure if I'm getting it mixed up with CRA). But I don't think I changed anything, and I just installed expo-cli globally yesterday.

**Comment by Arlen22** [comment] 2019-11-22 23:51
I'm literally just using it anyway, because this is the first time I've actually gotten my expo and native base code to work in anything "react native web".

**Comment by brentvatne** [comment] 2019-11-22 23:55
@EvanBacon - any idea about this error?

**Comment by Arlen22** [comment] 2019-11-23 01:19
The only problems I ever have with Expo and React dev servers always seem to somehow involve HMR. Last time it was wrapping my classes _before_ the static properties were assigned outside of the class (since Typescript doesn't compile using the static keyword) and I had to target ES5 to solve that because ES5 classes are typeof "function", so HMR doesn't wrap it.

**Comment by Smarticles101** [comment] 2019-11-23 05:54
duplicate of #1256

**Comment by Arlen22** [comment] 2019-11-23 18:50
Please see my comment there: https://github.com/expo/expo-cli/issues/1256#issuecomment-557822183

**Comment by EvanBacon** [comment] 2019-11-25 21:18
Sorry I missed this, investigating now.

**Closed** 2019-11-25 22:53 UTC
