### ISSUE TITLE
Expo-CLI not displaying log output in terminal (Mac/Windows)

### ISSUE THREAD

**Issue by Slapbox** [expo/expo-cli#990] opened 2019-09-05 22:37 UTC
## Description

`console.log` and other statements are not output to terminal in any environment

## Expected Behavior

`console.log` would write to the terminal where `expo-cli` was run

## Observed Behavior

I see 2 initial warnings about require cycles, but then nothing. I only see log statements when I enable remote debugging.

## Environment

**Mac**
  Expo CLI 3.0.10 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.11.2 - /usr/local/bin/npm
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      @tippy.js/react: ^2.2.0 => 2.2.0 
      react: ^16.8.6 => 16.8.6 
    npmGlobalPackages:
      expo-cli: 3.0.10

**Windows**
  Expo CLI 3.0.10 environment info:
    System:
      OS: Windows 7
    Binaries:
      Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.2.0 - C:\Users\Remie\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  2.3.0.0 AI-162.3871768

## Also specify:

- Phone/emulator/simulator platform, model and version: N/A

I have `console.disableYellowBox = true` and the require cycles, those are the only things that occur to me as even possibly relevant. I'm not sure what could cause this across platforms like this. I've tried `cmd` and `PowerShell` on Windows 7, but the behavior is the same on both.

**Comment by Slapbox** [comment] 2019-09-06 20:32
Update: I was wrong, it doesn't work in debuggers either. I cannot log from Expo no matter what I do, which has brought development to a standstill.

**Comment by bamne123** [comment] 2019-12-09 19:41
Any update on this?

**Comment by Slapbox** [comment] 2019-12-09 23:40
We've barely touched our mobile app in months because it's all but impossible to work with. Debugger is spotty (not an Expo issue) and CLI outputs absolutely nothing - (is an Expo issue.)

It seems to have mysteriously appeared between SDK releases, I'd have to guess in some release of `expo-cli`.

**Comment by brentvatne** [comment] 2019-12-09 23:49
@Slapbox - is this issue not a duplicate of https://github.com/expo/expo-cli/issues/373?

require cycle warnings were introduced in react-native 0.57 and we muted them in expo-cli. see https://github.com/facebook/metro/issues/287 for context

**Comment by Slapbox** [comment] 2019-12-10 00:33
Hey @brentvatne thanks for the reply! It's similar, but not the same. My issue is that I see no log statements with Android or iOS, independent of phone name, emulator versus physical, or the OS I'm running `expo-cli` on. Unfortunately it even affects debuggers.

I mention require cycles only because I couldn't find any directions to explore to find an underlying cause, and I couldn't remove all require cycles without a lot of work, which left me unable to rule out that (extremely unlikely) culprit.

I wonder if maybe the issue started in `expo-cli@3.x.x`, which came out only a short time before this issue. I have to imagine I tried reverting to `2.x.x`, but perhaps I didn't make the connection, because I didn't document any attempt.

----
By the way is there a way to *re-enable* warnings about require cycles? Cycles seemed to make loading in `dev` slow, and it made sense to me why they might, but that could be placebo.

**Closed** 2020-04-22 04:27 UTC
