### ISSUE TITLE
App no longer reloads (production mode) with Expo CLI v2

### ISSUE THREAD

**Issue by incorelabs** [expo/expo-cli#67] opened 2018-10-03 05:33 UTC
## Description

I had been religiously using Create React Native App but then yesterday I thought of migrating to Expo since I read on the [official create react native app repository](https://github.com/react-community/create-react-native-app) that,

> Note: Create React Native App has been merged with Expo CLI You can now use expo init to create your project. See Quick Start in the Expo documentation for instructions on getting started using Expo CLI.

## Expected Behavior

Things that I considered normal while developing,

1. When I change the contents of any file and save it, app should refresh with the updated contents whether it is Production mode or Development mode.
2. Switching between development and production mode used to actually work and changes used to be reflected in the app.

## Observed Behavior

Currently, the following happen:

1. The app does not refresh any more when changes are done in production mode and even after closing it on Android it is after many desperate tries that it changes its content (that may range from 10 to infinity).
2. Once in production mode, it is literally impossible to go back to development mode even though I've tried switched the toggle on the Dev tools which pop up in the browser and also by pressing the designated button on the CLI, it just does not go back from production to development, and sometimes vice-versa.

There are no errors messages as such but it shows, __DEV__ = false, even though the when I press the "?' it says it is in development mode.

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Environment:
  OS: Windows 10
  Node: 8.12.0
  Yarn: Not Found
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5014246

Packages: (wanted => installed)
  expo: ^30.0.1 => 30.0.1
  react: 16.3.1 => 16.3.1
  react-native: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz => 0.55.4

Diagnostics report:
  https://exp-xde-diagnostics.s3.amazonaws.com/incorelabs-00b725ba-171c-472b-b646-46a847c85c31.tar.gz

Also specify:

* Phone/emulator/simulator platform, model and version:

Pixel XL 2. Android.

## Reproducible Demo

There is no specific scenario for this. I tried creating a new app using,

```
expo init my-app
cd my-app
expo start
```

**Comment by timbrandin** [comment] 2018-12-16 18:44
Can also confirm that expo does not want to go back from production mode, I get the updates though when I save files.

**Comment by timbrandin** [comment] 2018-12-16 18:47
I managed to go back by running `expo start -c` rather than pressing `shift-r` in the bundler.

**Comment by cek-cek** [comment] 2019-02-26 07:42
The only thing that worked for me was to wipe the app data of the Expo app on Android.

**Comment by brentvatne** [comment] 2019-12-07 02:09
hey! this should be resolved in sdk 36 with the following changes:

- `expo start` will always default to development mode
- refreshing an app in expo client will always refresh from manifest, so it will update the dev mode

sorry for no reply on this, i'm glad folks were able to workaround this when they encountered it

**Closed by brentvatne** 2019-12-07 02:09 UTC

**Comment by raRaRa** [comment] 2020-01-17 14:53
> hey! this should be resolved in sdk 36 with the following changes:
> 
> * `expo start` will always default to development mode
> * refreshing an app in expo client will always refresh from manifest, so it will update the dev mode
> 
> sorry for no reply on this, i'm glad folks were able to workaround this when they encountered it

Didn't work for me :( Just started working with Expo few days ago. Had to delete the app data. Thanks for the work around @cek-cek

**Comment by DarkoKolak** [comment] 2020-04-13 19:35
I have a simmiliar issue, When i open the app in the Browser changes that i done are there, but when i open the app on my android Phone it opens the app in production mode and without the changes that i done. This happend after i published my app on expo. i tried the solutions above but none of them works for me....

**Comment by dnr** [comment] 2020-04-14 03:17
Just another report that this does not appear to be fixed. I switched to production mode and was unable to switch back to development mode and reload my app. Tried `expo start --dev` and force-killing the Android app. I eventually did "clear app data" on the expo app and it worked again.

Using SDK 37, expo-cli 3.17.18, Android app 2.15.0.

**Comment by brentvatne** [comment] 2020-04-16 21:25
hi! can someone help me reproduce this? please let me know the exact steps to follow, i have been unable to get into the same situation.

**Comment by dnr** [comment] 2020-04-17 02:18
Well, I just tried again, documenting each step, and was not able to reproduce it: I could easily switch back and forth between modes this time. So it might be that something occasionally gets stuck in a bad state? Oh well, hopefully it won't happen again.

**Comment by brentvatne** [comment] 2020-04-17 02:21
if it does happen again and you remember the steps then let me know! :)

**Comment by EdilsonVieira** [comment] 2020-04-22 20:25
Deleting Expo cache on Android did work for me.
