### ISSUE TITLE
Warning given about Expo Constants when my project isn't using them

### ISSUE THREAD

**Issue by zaytrix** [expo/expo-cli#682] opened 2019-06-07 22:20 UTC
## Description

After upgrading to `Expo SDK v33.0.0` and `expo-cli v2.19.4`, when I run `expo start` and open my project in the Expo app, the console warns me about `Constants` being deprecated and to update my imports for it, on almost every screen I switch to in my project. However, I am not using `Constants` anywhere in my app.

## Expected Behavior

My project is not using `Constants`, so I'm not sure why it's polluting my console with this message. Perhaps one of my dependencies is using it? Not as far as I can tell, however.

## Observed Behavior

Here is the message that's being spammed in the console:
```console
The following APIs have moved to separate packages and importing them from the "expo" package is deprecated: Constants.

1. Add correct versions of these packages to your project using:

   expo install expo-constants

   If "install" is not recognized as an expo command, update your expo-cli installation.

2. Change your imports so they use specific packages instead of the "expo" package:

 - import { Constants } from 'expo' -> import Constants from 'expo-constants'
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

```console
Expo CLI 2.19.4 environment info:
    System:
      OS: macOS 10.14.5
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.3.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^33.0.0 => 33.0.3
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.0 => 3.11.0
    npmGlobalPackages:
      expo-cli: 2.19.4
```

Here's my list of dependencies as well:
```json
"dependencies": {
    "@babel/core": "^7.0.0-0",
    "@expo/react-native-responsive-image": "^2.0.0",
    "axios": "^0.18.0",
    "babel-plugin-module-resolver": "^3.1.1",
    "expo": "^33.0.0",
    "expo-linear-gradient": "~5.0.1",
    "expo-permissions": "~5.0.1",
    "prop-types": "^15.6.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
    "react-native-animatable": "^1.3.1",
    "react-native-collapsible": "^1.4.0",
    "react-native-elements": "^1.1.0",
    "react-native-transformable-image-next": "^0.0.20",
    "react-native-xml2js": "^1.0.3",
    "react-navigation": "^3.11.0",
    "recyclerlistview": "^1.3.4",
    "tinycolor2": "^1.4.1"
  },
```

Running the Expo app on an Android phone

**Comment by cruzach** [comment] 2019-06-08 00:10
Hey @zaytrix- does this happen on a blank `expo init` project?

**Comment by zaytrix** [comment] 2019-06-08 00:37
I have just tested it on an `expo init` project using `expo-template-tabs`, and I'm getting the same issue with that. Will try with the blank template as well.

**Comment by zaytrix** [comment] 2019-06-08 00:51
It does not happen on a `expo-template-blank` project @cruzach

**Comment by cruzach** [comment] 2019-06-09 14:36
I just tried reproducing on `expo-template-tabs`, and this isn't happening to me (same Expo CLI version)

**Comment by cruzach** [comment] 2019-06-09 14:38
Closing, duplicate of #681

**Closed by cruzach** 2019-06-09 14:38 UTC
