### ISSUE TITLE
No matching version found for @expo/config@3.2.1.

### ISSUE THREAD

**Issue by aziz4980** [expo/expo-cli#2099] opened 2020-05-11 09:32 UTC
**HELLO! i am facing this issue while installing the expo cli. can you please suggest me the remedy!**

![image](https://user-images.githubusercontent.com/31212073/81546444-cef72380-9393-11ea-9148-03926fe9f06e.png)

**Comment by fson** [comment] 2020-05-11 15:12
Closing this as a duplicate of #2097. This possibly seems like a temporary problem with the npm registry. See https://github.com/expo/expo-cli/issues/2097#issuecomment-626764391 for more information that you could send to help narrow down the issue.

**Closed by fson** 2020-05-11 15:12 UTC
