### ISSUE TITLE
yarn expo run:ios does not launch simulator or go beyond installing

### ISSUE THREAD

**Issue by Akumzy** [expo/expo-cli#4480] opened 2022-07-25 07:34 UTC
### Summary

Running `yarn expo run:ios` will build the app but will not launch the simulator or go beyond installing

### Environment

  expo-env-info 1.0.5 environment info:
    System:
      OS: macOS 12.5
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.14.0 - ~/.volta/tools/image/node/16.14.0/bin/node
      Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
      npm: 8.3.1 - ~/.volta/tools/image/node/16.14.0/bin/npm
    Managers:
      CocoaPods: 1.11.2 - /usr/local/bin/pod
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
      Android SDK:
        API Levels: 31, 32
        Build Tools: 30.0.2, 31.0.0, 32.0.0, 32.1.0, 33.0.0
        System Images: android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64
    IDEs:
      Android Studio: 2021.1 AI-211.7628.21.2111.8139111
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^46.0.0-beta.6 => 46.0.0-beta.6 
      react: 18.0.0 => 18.0.0 
      react-dom: 18.0.0 => 18.0.0 
      react-native: 0.69.1 => 0.69.1 
      react-native-web: ~0.18.7 => 0.18.7 
    Expo Workflow: bare

### Please specify your device/emulator/simulator platform, model and version

Simulator, iPhone 13, iOS 15.5

### Reproducible demo or steps to reproduce from a blank project

Run `yarn expo run:ios`

**Comment by brentvatne** [comment] 2022-07-25 21:23
can you share a screenshot or more information about the output that you see?

**Comment by Akumzy** [comment] 2022-07-26 17:58
Here is a screenshot @brentvatne, it just stays there nothing else happens 
![Screenshot 2022-07-26 at 6 54 54 PM](https://user-images.githubusercontent.com/25849232/181077779-6eabb458-e184-4ee5-bc9c-5b1c95686d58.png)

**Comment by EvanBacon** [comment] 2022-10-18 01:21
If anyone is still having this issue, please run with `EXPO_DEBUG=1` (environment variable) so we can get more visibility into what's happening.

**Comment by EvanBacon** [comment] 2022-10-27 01:54
Closing as I cannot reproduce. My best guess is that the machine is really slow to startup the simulator app, manually opening Simulator.app should unblock.

**Closed by EvanBacon** 2022-10-27 01:54 UTC
Labels: needs review
