### ISSUE TITLE
NCC Expo CLI

### ISSUE THREAD

**Issue by EvanBacon** [expo/expo-cli#1979] opened 2020-04-24 16:19 UTC
Because TS doesn't minify libraries, we need to minify the end result of our packages which in this case is expo-cli.

**Comment by fson** [comment] 2020-07-03 12:16
I evaluated this in #2168, but because of the large size of the codebase and its dependencies, I wasn't able to work around the increased time to interaction caused by bundling all this code into a large single file that needs to be parsed before the command does anything (see https://github.com/expo/expo-cli/pull/2168#issuecomment-648221147).

`ncc` currently does *not* appear to have an option for using dynamic imports as code splitting points (similar to https://webpack.js.org/guides/code-splitting/#dynamic-imports), which would have been useful for solving this problem.

`ncc` does support multiple entry points with a shared "common bundle", which could be useful, but moving every command to be a separate entry point would be a major project and possibly require custom code for argument parsing and `--help` to work.

I'm closing this issue for now, but I think it would be worth it to re-evaluate, if ncc at some points gains more capabilities for code-splitting or if we decide to extract smaller parts of Expo CLI into separate tools that we could compile with `ncc`.

**Closed by fson** 2020-07-03 12:16 UTC
Labels: enhancement
