### ISSUE TITLE
permission denied on npm install -g expo-cli

### ISSUE THREAD

**Issue by leebenalal** [expo/expo-cli#969] opened 2019-08-28 13:41 UTC
hi,
I’m trying to update my expo client to version 34.0.0 and I saw that i’m supposed to run again npm install -g expo-cli. However, I’m getting an error:

npm ERR! path C:\Users\Yarden\AppData\Roaming\npm\node_modules\expo-cli\node_modules@expo.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink ‘C:\Users\Yarden\AppData\Roaming\npm\node_modules\expo-cli\node_modules@expo.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll’
npm ERR! { [Error: EPERM: operation not permitted, unlink ‘C:\Users\Yarden\AppData\Roaming\npm\node_modules\expo-cli\node_modules@expo.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll’]
npm ERR! cause:
npm ERR! { Error: EPERM: operation not permitted, unlink ‘C:\Users\Yarden\AppData\Roaming\npm\node_modules\expo-cli\node_modules@expo.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll’
npm ERR! errno: -4048,
npm ERR! code: ‘EPERM’,
npm ERR! syscall: ‘unlink’,
npm ERR! path:
npm ERR! ‘C:\Users\Yarden\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll’ },
npm ERR! stack:
npm ERR! ‘Error: EPERM: operation not permitted, unlink ‘C:\Users\Yarden\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll’’,
npm ERR! errno: -4048,
npm ERR! code: ‘EPERM’,
npm ERR! syscall: ‘unlink’,
npm ERR! path:
npm ERR! ‘C:\Users\Yarden\AppData\Roaming\npm\node_modules\expo-cli\node_modules\@expo\.xdl.DELETE\binaries\windows\adb\AdbWinApi.dll’,
npm ERR! parent: ‘expo-cli’ }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It’s possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Yarden\AppData\Roaming\npm-cache_logs\2019-08-28T13_31_31_467Z-debug.log

I have tried using administrator mode with no success.
Any ideas?
Thank you!!

**Comment by roeniss** [comment] 2019-08-28 16:06
I think this is not a 'expo' issue. Can you try this [solution](https://stackoverflow.com/questions/30860795/fail-to-install-npm-package-npm-err-errno-4048)?

**Comment by raajnadar** [comment] 2019-09-22 10:08
1) The solution is press CTR + ALT + DEL (Open task manager)
2) In the processes search for adb.exe in background processes right click and end task.
3) Now try to install again it will surely work..!

Root cause the expo-cli does not end the task after the expo server is stopped. I am experiencing this issue for a long time.

**Comment by jkhales** [comment] 2019-10-14 22:51
Closing as the issue seems resolved.

**Closed by jkhales** 2019-10-14 22:51 UTC
Labels: Installation, OS: Windows
