### ISSUE TITLE
error registering "js" asset extension

### ISSUE THREAD

**Issue by pgte** [expo/expo-cli#1507] opened 2020-02-02 15:17 UTC
## Description

I'm trying to include an asset that has a ".js" extension (to be used inside a webview).
To do this I'm adding an extension to the metro config (since `packagerOpts` does not seam to be working for this) that adds that asset extension.

My `metro.config.json` is this:

```js
{
  "resolver": {
    "assetExts": ["ttf", "png", "css", "html", "js"]
  }
}
```

## Expected Behavior

I expected metro to successfully bundle the "js" file so that it would be available to the webview.

## Observed Behavior

Instead, I get the following error:

```
Unhandled JS Exception: undefined is not a function (near '...stry").registerAsset({...')

http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:1289:190
loadModuleImplementation@http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:14
http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:1278:31
loadModuleImplementation@http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:14
guardedLoadModule@http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:163:47
global code@http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:1299:4

loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:14
loadModuleImplementation
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:271:14
guardedLoadModule
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:163:47
global code
    AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false:1299:4
```

<img width="838" alt="iPhone_11_Pro_Max_—_13_3" src="https://user-images.githubusercontent.com/47910/73610275-672f8080-45cd-11ea-977c-c07c300ba2e7.png">

## Environment

`expo diagnostics` output:

```
  Expo CLI 3.11.7 environment info:
    System:
      OS: macOS 10.15.2
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v12.14.1/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
    npmGlobalPackages:
      expo-cli: 3.11.7
```

Also specify:

- Phone/emulator/simulator platform, model and version:
Iphone 11 Pro Max  — 13.3

## Reproducible Demo

I tried but couldn't reproduce this in a minimal snack, since I'm getting another error, also related to bundling:

https://snack.expo.io/@pgte/shallow-cookies

## More info

If I remove the "js" extension from the metro config, there is no such error (but obviously the webview fails because it can't find the script).

**Comment by fson** [comment] 2020-02-06 15:42
I think adding `js` to `assetExts` won't work correctly, because then many modules that should be treated as JS modules (e.g. React Native and Expo SDK internals) will be treated as an asset.

Could you try using a different extension for the webview code that you want to keep as-is, for example `webview.js` and only add *that* to `assetExts`?

**Comment by pgte** [comment] 2020-02-06 16:29
I tried that but unfortunately that doesn't work, the `webview.js` file is not added to the bundle.
(I guess it assumes that the extension is the string after the last point.)

**Comment by brentvatne** [comment] 2020-02-27 22:37
hey @pgte! you can't use .js as an asset extension because it is a [source extension](https://facebook.github.io/metro/docs/en/configuration#sourceexts). you could use any other arbitrary file type like `.webviewjs` and that should work fine. what are you using the file in webview for? the `injectJavaScript` method or?

**Comment by brentvatne** [comment] 2020-02-27 22:37
closing because this is expected behavior and not an issue with expo-cli, however i am certainly interested in hearing more and helping you figure out how to get what you need to do working

**Comment by drager** [comment] 2020-05-06 08:43
@brentvatne Doing ```"packagerOpts": {
      "assetExts": ["webviewjs"]
    },```

does nothing, still getting:
```Error: 'assets/web/file.webviewjs' cannot be loaded as its extension is not registered in assetExts```

**Comment by brentvatne** [comment] 2020-05-08 06:30
you are correct, we are passing the `assetExts` through but react-native-cli is ignoring them.

you can install `@expo/metro-config` in your project and create the following metro.config.js in your project root:

```
const { getDefaultConfig } = require("metro-config");

module.exports = (async () => {
  let defaultConfig = await getDefaultConfig();

  return {
    resolver: {
      assetExts: [...defaultConfig.resolver.assetExts, "webview"],
    },
  };
})();
```

here's a full working example for you: https://github.com/brentvatne/asset-exts-example

here's where we import the asset then read it: https://github.com/brentvatne/asset-exts-example/blob/6964ad62cc27d734fbc3174a5bc04b51db3c1aed/App.tsx#L7-L24

**Comment by brentvatne** [comment] 2020-05-08 06:31
cc @fson we desperately need a guide for this in docs, along with an explanation of how to use `@expo/metro-config`

**Comment by brentvatne** [comment] 2020-05-08 06:37
sorry i confused myself and meant to reopen and reply to only https://github.com/expo/expo-cli/issues/2077

**Closed by brentvatne** 2020-05-08 06:38 UTC
