### ISSUE TITLE
macOS Catalina: "Could not find transporter". Xcode 11 doesn't include the Transporter application anymore.

### ISSUE THREAD

**Issue by evanheckert** [expo/expo-cli#927] opened 2019-08-12 02:49 UTC
## Description

Attempted my normal pattern of `expo build:ios`, followed by` expo upload:ios`.

`upload:ios` fails with the error: 

```
Failed to upload the standalone app to the app store.
Could not find transporter at /Applications/Xcode-beta.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation.
Set EXPO_DEBUG=true in your env to view the stack trace.
```
A google search lead to this: https://stackoverflow.com/questions/56504929/bitrise-could-not-find-transporter-at-applications-xcode-beta-app-contents-devel

I can jump over to my other system with Mojave to upload, but didn't see any mention of this on the repo so thought I should submit this.
 
## Environment
```
> expo diagnostics
  Expo CLI 3.0.9 environment info:
    System:
      OS: macOS 10.15
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.17.3 - /usr/local/bin/yarn
      npm: 6.10.3 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.0/11M336w - /usr/bin/xcodebuild
    npmPackages:
      expo: ^34.0.4 => 34.0.4
      react: 16.8.3 => 16.8.3
      react-native: https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz => 0.59.8
      react-navigation: ^3.11.1 => 3.11.1
    npmGlobalPackages:
      expo-cli: 3.0.9

```

**Comment by nickhough** [comment] 2019-09-18 20:01
@AdamJNavarro Did you ever figure out a solution?

**Comment by switz** [comment] 2019-09-19 05:52
Also running into this.. couldn't find a solution

**Comment by jacinto123** [comment] 2019-09-21 20:57
I am running to this as well, it seems xcode 11 also took away application loader so I currently have no way to release my new build

**Comment by switz** [comment] 2019-09-21 20:59
For whatever it's worth, I spent a few hours trying to get transporter set up manually.. it didn't work. I had to install the previous XCode and now it's working fine. A bit inconvenient, but at least I could release a build. If you have the free space, I recommend doing that until a new solution is found.

**Comment by NTag** [comment] 2019-09-21 21:37
It's not only macOS Catalina: I'm still on Mojave, and XCode just updated itself to XCode 11 without asking me. And I get the exact same error. Apple says that:
> Xcode supports uploading apps from the Organizer window or from the command line with xcodebuild or xcrun altool. Application Loader is no longer included with Xcode. (29008875)

I guess an update of expo-cli is required.

**Comment by NTag** [comment] 2019-09-21 21:52
In the meantime, you can download the ipa, and use `xcrun altool --upload-app -f pathtothefile.ipa -u youremail@apple.com` to upload it to Apple Connect. The password you will be asked for is an application password if you have two-factors enabled on your Apple account.

**Comment by wodin** [comment] 2019-09-22 00:05
See also: https://github.com/fastlane/fastlane/issues/14955

the following claims that upgrading fastlane solves the problem:
https://stackoverflow.com/a/57754715/495319

**Comment by CodingItWrong** [comment] 2019-09-23 10:23
Updating Fastlane and `xcrun altool` didn't work for me, but re-downloading Xcode 10.3 did. You can get it from Apple's [More Downloads for Apple Developers page](https://developer.apple.com/download/more/).

**Comment by derkweijers** [comment] 2019-09-23 18:57
> Updating Fastlane and `xcrun altool` didn't work for me, but re-downloading Xcode 10.3 did. You can get it from Apple's [More Downloads for Apple Developers page](https://developer.apple.com/download/more/).

For xcrun altool, make sure you generate an application password if you have 2FA enabled. The tool can't handle 2FA. You can do it here: https://appleid.apple.com/ -> Generate app specific password.

**Comment by FeboApp** [comment] 2019-09-23 23:07
Could you guys provide a step by step solution to this? I really need to upload an update to my app asap :c

**Comment by derkweijers** [comment] 2019-09-24 06:58
1. If you have 2FA enabled, generate an app password from https://appleid.apple.com/
2. Build your app with `expo build:ios` and download the archive when it's finished
3. run `xcrun altool --upload-app -f pathtothefile.ipa -u youremail@apple.com` from the command line to upload the archive to Apple. You won't see any progress and it might take awhile so you might need to be a little patient :)

**Comment by serhiipalash** [comment] 2019-09-24 12:14
> In the meantime, you can download the ipa, and use `xcrun altool --upload-app -f pathtothefile.ipa -u youremail@apple.com` to upload it to Apple Connect.

Doesn't work for us. Fails with error `We are unable to create an authentication session. Unable to validate your application.`

**Comment by hasis** [comment] 2019-09-24 12:43
Try and generate an app specific password from https://appleid.apple.com/account/manage and use that with `xcrun altool ...` -- should get you past the `Unable to validate your application` error.

**Comment by xiCO2k** [comment] 2019-09-24 13:15
Worked for me

**Comment by FeboApp** [comment] 2019-09-24 16:03
Worked like a charm! Thank you so much

**Comment by xiCO2k** [comment] 2019-09-24 16:18
:)

**Comment by chandlervdw** [comment] 2019-09-24 19:50
Thanks @derkweijers!

**Comment by ioness** [comment] 2019-09-27 20:55
Worked for me!

**Comment by TranDinhKhang** [comment] 2019-09-28 16:40
thanks, it worked for me

**Comment by mauriciord** [comment] 2019-09-30 02:29
Thank you @derkweijers , worked for me.

**Comment by 67millwood** [comment] 2019-10-01 13:18
seemed to upload with no errors.  but maybe i'm missing a step.  don't see any builds under TestFlight after going through this....

**Comment by 67millwood** [comment] 2019-10-01 13:23
> seemed to upload with no errors. but maybe i'm missing a step. don't see any builds under TestFlight after going through this....

nvmd.  now shows in 'processing'

**Comment by jason-evt** [comment] 2019-10-01 15:50
this is a workaround until the issue is fixed within fastlane? Thanks!

**Comment by rusyurchenko** [comment] 2019-10-02 09:38
+1

**Comment by rnavedojr** [comment] 2019-10-02 16:26
> 1. If you have 2FA enabled, generate an app password from https://appleid.apple.com/
> 2. Build your app with `expo build:ios` and download the archive when it's finished
> 3. run `xcrun altool --upload-app -f pathtothefile.ipa -u youremail@apple.com` from the command line to upload the archive to Apple. You won't see any progress and it might take awhile so you might need to be a little patient :)

Hi there, when you download the file from the expo build, where are you supposed to save it to run the command? Please advise.

**Comment by derkweijers** [comment] 2019-10-02 16:44
Doesn’t really matter, since you specify the path with the -f argument.

**Comment by rnavedojr** [comment] 2019-10-03 00:39
But I mean, you just open the downloaded file in VS Code and run the commands?

**Comment by rnavedojr** [comment] 2019-10-03 00:40
https://github.com/expo/expo-cli/issues/927#issuecomment-537579899

But I mean you just download the file, open in VS Code and run the commands?

**Comment by rnavedojr** [comment] 2019-10-03 01:54
I dont understand the 2FA.  I generate a password, but where to place that in the command?  At the end, the beginning, can somebody advise?  Thanks.

**Comment by squatto** [comment] 2019-10-03 05:57
@rnavedojr the command will ask you for your password if you don't provide it directly to the command (which you **should not do** in a console command because your password will be logged to your console's history file)

**Comment by squatto** [comment] 2019-10-03 05:59
There are multiple ways to provide your password to the `xcrun` command. You can learn more about them by running `xcrun altool --help`:

```
Authentication: Most commands require authorization.
                There are two methods available: user name with password, and apiKey with apiIssuer.

                -u, --username <username> Username. Required to connect for validation, upload, and notarization.
                -p, --password <password> Password. Required if username specified and apiKey/apiIssuer are not.
                                          If this argument is not supplied on the command line, it will be read from stdin.
                                          Alternatively to entering <password> in plaintext, it may also be specified using a '@keychain:'
                                          or '@env:' prefix followed by a keychain password item name or environment variable name.
                                          Example: '-p @keychain:<name>' uses the password stored in the keychain password item named <name>.
                                                                         You can create and update keychain items with the
                                                                         --store-password-in-keychain-item command.
                                          Example: '-p @env:<variable>'  uses the value in the environment variable named <variable>
```

**Comment by rnavedojr** [comment] 2019-10-03 11:36
It actually didn’t asked me for a password I tried and review the command several time and just didn’t work somehow.  I just downgraded to XCode 10.3 and ran expo upload:ios.  It worked fine. Thanks.

Kind regards,
Rey

________________________________

**Comment by squatto** [comment] 2019-10-03 13:25
@rnavedojr Did you see my second reply with instructions on how to provide your password to the tool? You shouldn't need to downgrade to get it to work.

**Comment by fson** [comment] 2019-10-09 15:20
This should be fixed in the latest version of `expo-cli`. However, please open an issue if you're still experiencing problems with Xcode 11 and the `expo build:ios` or `expo upload:ios` commands!

**Closed by fson** 2019-10-09 15:20 UTC
Labels: OS: macOS

**Comment by dkumarx** [comment] 2019-10-17 00:40
Hi there,

I am not seeing the latest build file after uploading to app store with XCode 11.0+ version. 

Has anyone experienced an issue on "App Store Connect"?

I have followed all instructions and build successfully via latest "expo-cli v3.4.0.

I would much appreciate it if anyone can help me to proceed further. I was trying couple of days but no success :( 

Thanks in advance

**Comment by dkumarx** [comment] 2019-10-17 04:46
> Hi there,
> 
> I am not seeing the latest build file after uploading to app store with XCode 11.0+ version.
> 
> Has anyone experienced an issue on "App Store Connect"?
> 
> I have followed all instructions and build successfully via latest "expo-cli v3.4.0.
> 
> I would much appreciate it if anyone can help me to proceed further. I was trying couple of days but no success :(
> 
> Thanks in advance

Resolved :

upgraded "EXPO-CLI to 3.4.0" and uploaded package file to app store via "Transformer"

I've found another way to push .ipa file to app store using "Transformer"

https://apps.apple.com/us/app/transporter/id1450874784?mt=12

**Comment by anton-kulikalov** [comment] 2019-10-22 16:29
I stuck at "Assets verification" stage with this error:
```
Communication error. Please use diagnostic mode to check connectivity.
```
[Here is full description](https://stackoverflow.com/questions/58355195/cant-upload-ipa-file-communication-error-please-use-diagnostic-mode-to-check)

Any ideas, guys? I think I've tried everything...

**Comment by wodin** [comment] 2019-10-22 20:27
Hi. I'm not sure what's going wrong for you, but have you tried installing the latest version of expo-cli and running `expo upload:ios`?

**Comment by anton-kulikalov** [comment] 2019-10-22 20:42
@wodin i've just updated expo and got the same issue.

**Comment by wodin** [comment] 2019-10-23 10:36
@anton-kulikalov could you clarify what you mean by "the same issue"? Do you mean you still get an error saying "Communication error. Please use diagnostic mode to check connectivity." when running `expo upload:ios`?

And just to be sure, does `expo --version` return `3.4.1`?

**Comment by anton-kulikalov** [comment] 2019-10-23 14:04
the same issue: https://github.com/expo/expo-cli/issues/927#issuecomment-545045625

I've identified the root cause of the issue. This part of the `app.json` was causing it: `ios.associatedDomains`.

**Comment by Dsantacruz** [comment] 2019-10-30 18:06
upgrade to latest expo-cli, this worked for me.

**Comment by owencm** [comment] 2019-11-19 02:35
FYI docs still say this is broken, probably need updating: https://docs.expo.io/versions/latest/distribution/uploading-apps/#2-start-the-upload

**Comment by hasis** [comment] 2019-11-23 01:52
FWIW, Apple also released a new version of Transporter. Works very well for those uncomfortable with the CLI.

**Comment by Santiago0412** [comment] 2020-04-07 06:00
https://stackoverflow.com/a/61073622/2515665
