### ISSUE TITLE
expo upload:ios iTMSTransporter error

### ISSUE THREAD

**Issue by jonsamp** [expo/expo-cli#2192] opened 2020-05-27 14:47 UTC
## Description

I am attempting to use `expo upload:ios` to upload my latest build to testflight.

## Expected Behavior

I expect this to download my latest build on Expo's servers, then upload it to testflight.

## Observed Behavior

The build downloads fine, but then there's an error with `iTMSTransporter`. Here's the full output after running `expo upload:ios`: 

(I have REDACTED some parts for privacy)

```
Downloading build from https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/REDACTED...baa281427504-archive.ipa
Downloading [================================================================================================================================================] 100% 0.0s
Resolving the ITC team ID...
ITC team ID is 2131102
Ensuring the app exists on App Store Connect, this may take a while...

+----------------+---------------------+
|     Summary for produce 2.141.0      |
+----------------+---------------------+
| app_identifier | com.REDACTED |
| app_name       | Gray One            |
| username       | REDACTED   |
| language       | English             |
| sku            | REDACTED          |
| platform       | ios                 |
| skip_itc       | false               |
| skip_devcenter | false               |
+----------------+---------------------+

[22:46:40]: [DevCenter] App 'com.REDACTED' already exists, nothing to do on the Dev Center
[22:46:42]: App 'com.REDACTED' already exists (REDACTED), nothing to do on App Store Connect
Uploading the app to Testflight, hold tight...
[22:46:44]: Login to App Store Connect (REDACTED)
[22:46:54]: Login successful
[22:46:55]: Ready to upload new build to TestFlight (App: REDACTED)...
[22:46:57]: [iTMSTransporter] -Djava.ext.dirs=/usr/local/itms/java/lib/ext is not supported.  Use -classpath instead.

[22:46:57]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.

[22:46:57]: [iTMSTransporter] Error: A fatal exception has occurred. Program will exit.

[22:46:57]: iTunes Transporter output above ^
[22:46:57]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[22:46:57]: Going to upload updated app to App Store Connect
[22:46:57]: This might take a few minutes. Please don't interrupt the script.
[22:46:57]: [iTMSTransporter] -Djava.ext.dirs=/usr/local/itms/java/lib/ext is not supported.  Use -classpath instead.

[22:46:57]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.

[22:46:57]: [iTMSTransporter] Error: A fatal exception has occurred. Program will exit.

[22:46:57]: iTunes Transporter output above ^
[22:46:57]: The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
Failed to upload the standalone app to the app store.
Error uploading ipa file, for more information see above
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/pilot/lib/pilot/build_manager.rb:37:in `upload'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:20:in `block in <main>'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:12:in `<main>'
Error: Error uploading ipa file, for more information see above
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/vendor/ruby/2.2.0/gems/fastlane-2.141.0/pilot/lib/pilot/build_manager.rb:37:in `upload'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:20:in `block in <main>'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/funcs.rb:4:in `with_captured_stderr'
    /Users/jon/.npm-packages/lib/node_modules/expo-cli/node_modules/@expo/traveling-fastlane-darwin/dist/lib/app/pilot_upload.rb:12:in `<main>'
    at runFastlaneAsync (/Users/jon/.npm-packages/lib/node_modules/expo-cli/src/commands/upload/utils.ts:84:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at IOSUploader._uploadToTheStore (/Users/jon/.npm-packages/lib/node_modules/expo-cli/src/commands/upload/IOSUploader.ts:227:5)
    at IOSUploader.upload (/Users/jon/.npm-packages/lib/node_modules/expo-cli/src/commands/upload/BaseUploader.ts:32:5)
    at /Users/jon/.npm-packages/lib/node_modules/expo-cli/src/commands/upload.ts:110:7
    at Command.<anonymous> (/Users/jon/.npm-packages/lib/node_modules/expo-cli/src/exp.ts:82:7)
```

## Environment

  Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.2 - ~/.volta/tools/image/node/12.16.2/bin/node
      Yarn: 1.22.4 - ~/.volta/tools/image/yarn/1.22.4/bin/yarn
      npm: 6.14.4 - ~/.volta/tools/image/node/12.16.2/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6392135
      Xcode: 11.5/11E608c - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.12
      react: ~16.9.0 => 16.9.0
      react-dom: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4
      react-native-web: ~0.11.7 => 0.11.7
    npmGlobalPackages:
      expo-cli: 3.20.9

## Reproducible Demo

I'm not sure how to create a reproducible demo, or how to figure out if this is an issue related to my computer's environment. I'm happy to remove expo/reinstall it, or anything else you think that might help narrow down what's going on here.

**Comment by brentvatne** [comment] 2020-05-27 19:22
waiting to hear back from @jonsamp about whether updating to latest expo-cli resolved the issue

**Comment by jonsamp** [comment] 2020-05-27 21:25
Updated to the latest expo cli version and still seeing this issue. I can investigate it more later this week.

**Comment by sshaw** [comment] 2020-05-28 22:26
> [22:46:57]: [iTMSTransporter] -Djava.ext.dirs=/usr/local/itms/java/lib/ext is not supported.  Use -classpath instead.

Sarting at JDK 9 `java.ext.dirs` [has been removed](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-7744EF96-5899-4FB2-B34E-86D49B2E89B6)

**Comment by jonsamp** [comment] 2020-05-30 21:01
I got to a resolution. I tracked it down through this fastlane issue: https://github.com/fastlane/fastlane/issues/16234

It seems xcode was using an old directory. I fixed this by renaming the **itms** directory: 

```bash
cd /usr/local
sudo mv itms old.itms
```

**Comment by brentvatne** [comment] 2020-05-30 22:15
maybe there is something that we can do to detect this, leaving it open for future reference

**Comment by webjay** [comment] 2020-09-18 14:34
I'm using expo-cli 3.27.4 and it ends here:

[iTMSTransporter] -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext is not supported.  Use -classpath instead.

[16:31:53]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.


I've tried moving `itms` but then it just can't find Java.

**Comment by webjay** [comment] 2020-09-18 16:08
I got around it on another Mac with Xcode 10.1

**Comment by dmckinney1229** [comment] 2020-09-18 18:26
I'm having the same issue with expo-cli 3.27.4 and Xcode 12.0 versions.

**Comment by salalaslam** [comment] 2020-09-21 06:19
I had the same issue and was also looking for solution, so instead of waiting for it I tried something.
1. Installed "Transporter" app from the App Store.
2. Opened Expo Dashboard and downloaded the .ipa from Build Artifact section of the project.
<img width="292" alt="Screen Shot 2020-09-21 at 11 15 34 AM" src="https://user-images.githubusercontent.com/2707973/93737129-cba25d00-fbfb-11ea-9f7e-67fbb39c0230.png">
3. Uploaded the .ipa to Transporter.
<img width="952" alt="Screen Shot 2020-09-21 at 11 16 55 AM" src="https://user-images.githubusercontent.com/2707973/93737187-f7bdde00-fbfb-11ea-9a27-d0a798449c5a.png">
4. The app started appearing in the TestFlight section of the app in the App Store Connect.

**Comment by hardcodet** [comment] 2020-09-21 23:59
Same issue as webjay here (itms path below Xcode) - will have to try to manually upload...

> 
> I'm using expo-cli 3.27.4 and Xcode 12.0 (12A7209) and it ends here:
> 
> [iTMSTransporter] -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext is not supported. Use -classpath instead.
> 
> [16:31:53]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.
> 
> I've tried moving itms but then it just can't find Java.

**Comment by brentvatne** [comment] 2020-09-22 00:29
i'd recommend using Transporter.app instead if you're having issues.

we're going to move ios submissions to a hosted service at some point in the future in order to eliminate issues around different system environments, but until then your safest bet is to use Transporter.app

**Comment by LinusU** [comment] 2020-09-29 14:28
@brentvatne I think that the problem is that `@expo/traveling-fastlane-darwin` is bundling Fastlane `2.146.1`, and this problem was fixed in Fastlane 2.150 (ref: https://github.com/fastlane/fastlane/issues/15323)

Would it be possible to upgrade the traveling fastlane to latest version? We are working with ~50 apps, and manually uploading them via Transporter.app isn't really a good solution for us 😅 

If there is anything I can do to help with this process I'd be happy to!

**Comment by LinusU** [comment] 2020-09-29 15:07
For anyone that needs to work around this in the meantime, it seems like this little script that rewrites the parameters sent to iTMSTransporter works:

https://github.com/dannys42-contrib/fastlane_workaround

I used it something like this:

```
git clone git@github.com:dannys42/fastlane_workaround.git /Users/linus/coding/fastlane_workaround
export FASTLANE_ITUNES_TRANSPORTER_PATH="/Users/linus/coding/fastlane_workaround"
expo upload:ios
```

**Comment by karanmartian** [comment] 2020-09-29 20:38
@brentvatne Transporter app has issues. Cannot sign into it using app specific password. Running Xcode 12 beta.

**Comment by LinusU** [comment] 2020-09-30 07:26
@karanmartian did you try the workaround that I posted?

**Comment by karanmartian** [comment] 2020-09-30 08:21
@LinusU Yes I did. It asks for Transporter app specific password which it accepts and after that it is stuck endlessly at the line that says Do not disturb the script or something like that. So I am almost there but not able to see what the script is doing or is it bush uploading. I waited for almost 15 mins but still stuck while with xcrun altool it takes no more than 4 mins. Is there a way to see the log output of the script?

**Comment by karanmartian** [comment] 2020-09-30 08:24
Also I am on the Big Sur 8 beta and XCode 12 beta. There are public posts available which you can find on Apple forums regarding Transporter sign in issues with these.

**Comment by LinusU** [comment] 2020-09-30 09:42
> I waited for almost 15 mins but still stuck

In my experience this takes ~25 minutes. It doesn't print any output, but it seems that it works if you let it run.

> while with xcrun altool it takes no more than 4 mins.

As I remember it, `altool` also took quite long, but was more stable. I've been wondering why `altool` wasn't used by Expo 🤔 

> to see the log output of the script?

My guess is that it's just waiting for things to happen on Apples server, so there is no more log output.

> XCode 12 beta

Xcode 12 have had a (two in fact) stable release now, so I would recommend using that instead of the beta.

**Comment by karanmartian** [comment] 2020-09-30 18:06
> > I waited for almost 15 mins but still stuck
> 
> 
> 
> In my experience this takes ~25 minutes. It doesn't print any output, but it seems that it works if you let it run.
> 
> 
> 
> > while with xcrun altool it takes no more than 4 mins.
> 
> 
> 
> As I remember it, `altool` also took quite long, but was more stable. I've been wondering why `altool` wasn't used by Expo 🤔 
> 
> 
> 
> > to see the log output of the script?
> 
> 
> 
> My guess is that it's just waiting for things to happen on Apples server, so there is no more log output.
> 
> 
> 
> > XCode 12 beta
> 
> 
> 
> Xcode 12 have had a (two in fact) stable release now, so I would recommend using that instead of the beta.

Yes Transporter works fine now, with Xcode 12 and MacOS Sur Beta 9

**Comment by bookofdom** [comment] 2020-10-01 02:52
I used transporter with good results. Catalina 10.15.7, XCode 12.0.1. 

It sure would be nice if the expo upload:ios worked though!

**Comment by rusakovic** [comment] 2020-10-06 16:23
Confirm the issue:
XCode 12.0.1 (12A7300)
expo-cli 3.27.12

```[18:59:29]: This might take a few minutes. Please don't interrupt the script.
[18:59:29]: [iTMSTransporter] -Djava.ext.dirs=/Applications/Xcode.app/Contents/SharedFrameworks/ContentDeliveryServices.framework/Versions/A/itms/java/lib/ext is not supported.  Use -classpath instead.

[18:59:29]: [iTMSTransporter] Error: Could not create the Java Virtual Machine.

[18:59:29]: [iTMSTransporter] Error: A fatal exception has occurred. Program will exit.```

**Comment by brentvatne** [comment] 2020-10-06 17:27
we have updated expo-cli to advise that you use Transporter.app in the event that `expo upload:ios` fails. the mechanism we depended on for that command has become very flakey recently and so Transporter.app is often a better choice instead.

related, we are working on a hosted upload service where we control the execution environment, so it will work much better than depending on tools on your machine. closing this issue because we don't plan on improving the local upload command and instead suggest you use Transporter.app for now. https://apps.apple.com/us/app/transporter/id1450874784?mt=12

**Closed by brentvatne** 2020-10-06 17:27 UTC
Labels: enhancement, expo upload

**Comment by LinusU** [comment] 2020-10-08 10:00
@brentvatne any plans to upgrade Fastlane in the traveling-fastlane package to `2.150`? I think that that would fix this specific problem for us ☺️

**Comment by celoprd** [comment] 2020-10-14 23:28
this works for me, without transporter

`curl $(expo url:ipa) --output MyApp.ipa`
`xcrun altool --upload-app -f MyApp.ipa -t ios -u <APPLE_ID> -p <APP_SPECIFIC_PASSWORD>`

**Comment by proevilz** [comment] 2020-10-15 19:48
> xcrun altool --upload-app -f MyApp.ipa -t ios -u <APPLE_ID> -p <APP_SPECIFIC_PASSWORD>

How do you specify the app name with this? By that I mean the same thing as `--app-name=` with the expo:upload command

**Comment by brentvatne** [comment] 2020-10-15 21:58
@LinusU - we can't do upgrade fastlane unfortunately. we depend on traveling-ruby to provide a portable ruby runtime to run fastlane, but traveling-ruby is no longer maintained and fastlane no longer supports the version of ruby that traveling-ruby last released with. so we are stuck with a version from april for now. we are doing a couple things to improve the situation, which i think are ultimately much better solutions overall:

1) rewriting parts of fastlane that we use in node/typescript.
2) building a hosted service for uploading ios apps to apple. this way we don't need to install anything on the developer's machine, and it can also work if the developer sends the upload request from windows, mac, iphone, windows phone (?), xbox, a fridge, a toaster, whatever (as opposed to only working on macos).

**Comment by chgsantos** [comment] 2020-10-15 23:04
@brentvatne awesome news! It's already amazing on Android, so will be on iOS too.

Do you have an expected date to release this hosted service?

**Comment by brentvatne** [comment] 2020-10-16 00:03
we're working on it but i don't have an eta at the moment

**Comment by kevindavis** [comment] 2020-10-29 22:57
@brentvatne great to hear - I think that will help with reliability here a ton. Is there somewhere we can follow progress on that project?

**Comment by brentvatne** [comment] 2020-10-29 22:59
@kevindavis - we'll have some updates for you before dec 15

**Comment by jjborie** [comment] 2020-12-11 01:15
Hi, we are almost dec 15, I was using a manual fix, any update? thanks for your great work on expo!

**Comment by brentvatne** [comment] 2020-12-11 01:38
yes! the update is that it's not dec 15 yet! but it almost is! just a bit longer 😆

**Comment by brentvatne** [comment] 2020-12-15 23:16
hey folks! check out this blog post for some info on "EAS Submit" - a hosted service for submitting apps: https://blog.expo.io/expo-application-services-eas-build-and-submit-fc1d1476aa2e

because it's a hosted service, it doesn't really matter what xcode or ruby version or whatever you have installed on your machine, and it also doesn't matter if you are using windows, macos, linux, or fuschia - as long as you can run `eas-cli` it will work.

the tradeoff is that because it's a hosted service it costs us money to run on our mac server infrastructure. currently EAS Submit is available to people who have subscribe to the [priority plan](https://expo.io/pricing) (which gives access to preview features). we'll roll it out later in 2021 to a more broad audience and with a free tier. check out http://docs.expo.io/submit/ios/ for more info!

if you don't want to use a hosted service, you can install fastlane or use transporter.app as usual. `expo upload:ios` has not been working well for a while now, and we don't plan to fix the command because upgrading fastlane within expo-cli would be an incredibly time consuming task upfront and require constant engineering time to maintain. additionally, bundling both a portable ruby runtime and all of fastlane inside of expo-cli makes it take a lot longer to install expo-cli. hopefully the options that i have presented here work for you! if you have any concerns, please feel free to reach out to me in twitter dms: https://twitter.com/notbrent

**Comment by LinusU** [comment] 2020-12-17 18:56
@brentvatne As I have understood it, we can only use "EAS Submit" with ejected or bare React Native apps (because we can only use "EAS Build" with ejected or bare apps). Is that understanding correct, or have I missed something?

We are on the priority plan and would love to do the submitting on a hosted service, but we currently have no plans to eject or ditch Expo...

**Comment by brentvatne** [comment] 2020-12-17 19:29
@LinusU - you can use EAS Submit with the "classic" Expo build service too: https://docs.expo.io/submit/classic-builds/

**Comment by LinusU** [comment] 2020-12-18 08:43
That's amazing!! Thank you for the quick response

**Comment by mymattcarroll** [comment] 2021-02-01 23:07
@brentvatne `expo upload:ios` has been marked as deprecated however `expo upload:android` has had `--use-submission-service` flag added. What is the future of the `expo upload:android` command? Will it also be deprecated as well?

I know this is a long shot but it would be absolutely amazing if the `expo upload:ios` had the `--use-submission-service` flag added as well and then used the same hosted service that is being used by the `eas submit` command. If this is technically possible, I would gladly open a pull request with the required changes.

**Comment by brentvatne** [comment] 2021-02-02 22:08
@mymattcarroll - `expo upload:android` now just always uses submission service, which is EAS Submit. we're likely going to remove both of these commands from expo-cli and refer people to eas-cli instead in the future - we'll do this when we have rolled out the EAS free tier

**Comment by leoskyrocker** [comment] 2021-02-05 08:36
@brentvatne when will the free tier be rolled out? While we appreciate the effort you guys have put in, and it has all been an amazing experience. It's not easy to convince a small company with limited usage to be paying the plans that offers way more usage. We have been using `expo upload:ios` for free, and really appreciated that you guys have enabled our business to be more sustainable as a startup! Now that `expo upload:ios` has only started failing (a few days back) and there's no clear way of fixing it because it's "deprecated" - we're kinda stuck.

**Comment by brentvatne** [comment] 2021-02-06 20:01
@leoskyrocker - we'll likely roll out the eas free tier within a few months, but we don't have an exact timeline. sorry that this change has caused you some inconvenience! a big difference between `eas submit` and `expo upload:ios` is that because it is hosted, the meaningful parts of the `eas submit` command run on **our mac infrastructure**, not on your computer, and this costs us money and requires us to ensure that we have enough macs available to handle peak load without creating long queues. as the service evolves over the coming months we'll be in a better place to expose this to all developers.

> Now that expo upload:ios has only started failing (a few days back) and there's no clear way of fixing it because it's "deprecated" - we're kinda stuck.

so you are using a version of expo-cli that still includes `expo upload:ios` but it's failing? you can use an old version of expo-cli as long as that works for you, but we are unable to continue to update the fastlane version in expo-cli because it depends on shipping a self contained ruby binary, and the tool we used for this - traveling-ruby - is no longer maintained and doesn't work with the new versions of fastlane. it would be a significant cost to us to have to take on responsibility for maintaining this package.

it's also would not be too useful for us to do that. the binary produced by `expo build:ios` can be uploaded to apple using any of the typical ways you would upload apps to the app store. **`expo upload:ios` is just `fastlane deliver` using a vendored version of fastlane**. we don't do anything special around uploading your app, `expo upload:ios` was always just a convenience wrapper around fastlane. if you want to keep using this same approach (eg: if you're submitting your app from CI) you can get your build url from `expo url:ipa`, download it with `curl`, then use [`fastlane deliver`](https://docs.fastlane.tools/actions/upload_to_app_store/) to submit it.

i'd recommend using [Transporter.app](https://apps.apple.com/us/app/transporter/id1450874784?mt=12) though. just download the app, then run `expo build:ios`, then download your build, drag and drop it into Transporter.app.

<hr />

we prefer to have a longer deprecation cycle than this but in this case we didn't properly anticipate the complications that would arise from depending on traveling-ruby and the resulting inability to update fastlane. the new `eas submit` command is completely different in its implementation, it's a hosted service and it works for macos, windows, linux, and really any platform that can submit http requests. it also fixes a number of issues that developers encountered, like when the developer had an older version of xcode on their machine leading to apple rejecting their submission with an opaque error message. i'm looking forward to rolling this out to free tier users soon, but until then you still have plenty of good options between `fastlane deliver` and Transporter.app :)

**Comment by ide** [comment] 2021-02-06 22:19
Expo apps for iOS are regular IPAs and you submit them for app review the exact same way you’d submit any other iOS app. There’s no lock-in and you can use your own computer with Transporter or Fastlane. There’s probably some way to get Xcode to discover the IPA and upload it (it might just use Transporter behind the scenes, not sure).

For existing CI pipelines one thing you can do is lock to an older version of Expo CLI if you need the old command until you’re able to switch over to Fastlane, EAS CLI, or something else on your own schedule.

**Comment by leoskyrocker** [comment] 2021-02-10 03:21
> so you are using a version of expo-cli that still includes expo upload:ios but it's failing?

@brentvatne Thanks Brent! I initially thought this is an issue that happens on expo-cli without any version changes, but it turns out someone in our team upgraded the expo version from 3.20.3 to 3.28.0. Now it seems to be working again after I downgraded the expo-cli. Sorry for the confusion and thank you so much for your time and the detailed response. Simply above and beyond! 🚀  and thank you and your team for providing a free tier for small business that are in need as well!

**Comment by misraelson** [comment] 2021-04-17 03:00
Anyone coming here in 2021, use expo build:ios, download your .ipa and upload via transporter. Works fine

**Comment by LinusU** [comment] 2021-04-19 13:57
You can also use `eas submit`:

```sh
eas submit --platform ios --url $(expo url:ipa) --apple-team-id XXXXX
```
