### ISSUE TITLE
outgoing TCP requests start failing 30 minutes after running "expo start"

### ISSUE THREAD

**Issue by kaitlynbrown** [expo/expo-cli#2195] opened 2020-05-28 00:32 UTC
## Description
Whenever I run `expo start`, roughly 30 minutes later, all outgoing tcp packets start being dropped.
Once this happens, I am unable to navigate to any website. Any music I have streaming will continue to play indefinitely. I can receive messages on Slack, but can't send them, or change channels. I can send pings to other devices on my network, to 8.8.8.8 and to google.ca, but `curl google.ca` fails. I can't even make requests to servers running on localhost.

No other devices on my network have internet connectivity issues. I tried unplugging/plugging the router, and the ethernet cable connected to my PC. I tried flushing my dns, I tried changing the dns to 8.8.8.8, I tried resetting winsock, I tried scanning my disk for corrupt system files, but none of these things resolved the issue. The only thing that "fixes" it is restarting my PC, however it still happens again 30 minutes after I run expo start.

The reason I believe this to be an issue with Expo is that it started happening yesterday morning when I started working on a mobile app that I hadn't worked on in a couple of months. It consistently happens roughly 30 minutes after I first run "expo start", which meant that it happened about every 35-40 minutes yesterday while I was trying to work on the app, which was extremely disruptive, to say the least. In the evening, when I took a break and wasn't using expo, my internet connection held up fine, and I had no issues. Later, when I started working on the app again and running `expo start`, it started happening again. Today, I was working on the web app for most of the day, and my internet connection was fine. But an hour ago I started working on an issue in the app, ran expo start, and sure enough, 30 minutes later my outgoing connections dropped.

## Expected Behavior

Using Expo should not have any effect on my connection to the internet or other devices on my network

## Observed Behavior

Expo causes outgoing TCP connections to fail 30 minutes after `expo start` is run.

## Environment

  Expo CLI 3.20.9 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.19.1 - /mnt/c/Users/katie/AppData/Roaming/npm/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    npmPackages:
      expo: ^37.0.0 => 37.0.12
      react: 16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
      react-navigation: 4.x => 4.3.9
    npmGlobalPackages:
      expo-cli: 3.20.9

Note that the system is actually Windows 10 (version 1903, build 18362.836), and expo is running in WSL

**Comment by cnx-piyush** [comment] 2020-05-30 16:12
Yes I am also facing this issue ,  this is troubling me for quite a long time

**Comment by piyusharorawork** [comment] 2020-05-30 16:42
@kaitlynbrown  
Actually I just found out that it is the duplicate of this issue

https://github.com/expo/expo-cli/issues/99

Looks like it is a bug in WSL and the easy fix for this to avoid restart is 
I found a palliative solution not to restart the machine:

1 - WIN+R -> services.msc
2 - Find LxssManager
3 - Right-click -> Restart

https://github.com/expo/expo-cli/issues/99#issuecomment-470803549

This should restart the WSL service, normalizing the network.

**Comment by byCedric** [comment] 2020-06-01 13:13
WSL2 is just released as generally available for non-insiders builds 😄 I would _heavily_ recommend switching to WSL2. [Here is a guide for that](https://ubuntu.com/blog/ubuntu-on-wsl-2-is-generally-available)! Let me know if that worked for you @kaitlynbrown 😄

**Comment by brentvatne** [comment] 2020-07-16 22:59
information about how to work around this wsl bug is available in https://github.com/expo/expo-cli/issues/99#issuecomment-562804479

**Closed** 2020-07-16 22:58 UTC
