### ISSUE TITLE
Expo publish problem

### ISSUE THREAD

**Issue by collaorodrigo7** [expo/expo-cli#1854] opened 2020-04-10 07:27 UTC
## Description
I tried using `expo publish`, and the cli says it all work fine, however when I go to the published url, and scan the QR to open the app it does not work.
Just to clarify, I am not sure whether this is an issue with Expo it self, with the CLI or the expo client app.
I assumed expo CLI was a good starting point.  
_EDIT: On second thought, this may not be an issue with CLI since CLI says it all worked fine. I reported it on main expo repo as well https://github.com/expo/expo/issues/7793 but I will keep this issue open just in case_

Here is the output of my `expo publish`

```
PS D:\> expo publish
Publishing to channel 'default'...
Building iOS bundle
Building Android bundle
Analyzing assets
Uploading assets
No assets changed, skipped.
Processing asset bundle patterns:
- D:\rctest\**\*
Uploading JavaScript bundles
Published
Your URL is

https://exp.host/@rcollao/rctest
```

## Expected Behavior
App should work after scanning the QR from the provided link on the CLI, https://expo.io/@user/APP_NAME

## Observed Behavior

App will not load, the expo client app shows:
```There was a problem loading the requested app.
exp://exp.host/@user/APP_NAME
Could not load exp://exp.host/@user.APP_NAME
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:
```
Expo CLI 3.17.21 environment info:
    System:
      OS: Windows 10 10.0.18362
    Binaries:
      Node: 12.16.2 - C:\Program Files\nodejs\node.EXE
      npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
    npmPackages:
      expo: ~36.0.0 => 36.0.2
      react: ~16.9.0 => 16.9.0
      react-native: https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz => 0.61.4
      react-navigation: ^4.2.2 => 4.3.7
```

Also specify:

- Phone/emulator/simulator platform, model and version:
I tried this on iPhone XR, 11 v13.3.1 and Samsung Galaxy J7 Android V 6.0.1
## Reproducible Demo

Just create a new app using Expo cli, start the app, and run expo publish.
Here is a published app not working: https://expo.io/@rcollao/rctest

Here is a sample repo just in case:
https://github.com/collaorodrigo7/expo-publish-fail

**Comment by cruzach** [comment] 2020-04-10 13:43
duplicate of https://github.com/expo/expo/issues/7793

@collaorodrigo7 please refrain from opening the same issue in different repositories

**Closed by cruzach** 2020-04-10 13:43 UTC

**Comment by davidmfry** [comment] 2020-06-01 15:20
I am having the same issue. I even created a brand new blank app and I get the same thing when trying to open the published app on the Expo client app on iOS and Android devices.

**Comment by jonkootje** [comment] 2020-10-20 09:56
I am also having the same issue. When I publish an app and set the privacy to public, I can still only open it when I'm logged in. When I logout of my expo account it starts giving me errors.
