### ISSUE TITLE
Expo build:android error

### ISSUE THREAD

**Issue by jimyu2006** [expo/expo-cli#580] opened 2019-05-07 01:36 UTC
### Please note that Expo CLI issues opened in the core Expo repository will be closed.

With virtual device open, then I run expo build:android generate issues as below:

C:\exec\react-native\test2>expo build:android
Checking if there is a build in progress...

Request failed with status code 400
Error: Request failed with status code 400
    at createError (C:\Dev\nvm\v10.15.1\node_modules\expo-cli\node_modules\xdl\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Dev\nvm\v10.15.1\node_modules\expo-cli\node_modules\xdl\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Dev\nvm\v10.15.1\node_modules\expo-cli\node_modules\xdl\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Same 400 issue when trying to click the "Run on android device/emulator" button in the expo browser window:
INFO12:44   Downloading latest version of Expo
ERROR 12:44  Couldn't start project on Android: Error running adb: Request failed with status code 400

Any ideas/help?

**Comment by jolocity** [comment] 2019-06-03 20:31
+1

**Comment by BridgeEast** [comment] 2019-06-26 04:22
+1

**Comment by AdrianRealDevs** [comment] 2019-10-04 07:04
Same issue here, just i made update at Expo, version 3.2.2. Any solution?

**Comment by glautrou** [comment] 2019-10-04 14:23
> Solution: downgrade to version 3.1.2

After downgrading and executing the command "`expo build:android`" in VS Code Terminal I had the following error:
```
Publishing to channel 'default'...
Building iOS bundle
connect ECONNREFUSED 127.0.0.1:19001
```
I don't know why it is building iOS instead of Android and what is this new issue.

Anyway, I then tried in the Windows cmd.exe and there it works like a charm.

**Comment by EtoileFilante** [comment] 2019-10-04 17:31
Same problem, and same error as @glautrou :/

**Comment by cruzach** [comment] 2019-10-11 17:15
Can either of you run `expo publish` with EXPO_DEBUG=true? I wasn't able to repro this and would like to find the root cause

This can usually happen when publishing without ever having run expo start, also it's a good idea to run rm -rf .expo to clear your local state

(The reason I ask for a way for me to repro is we can probably do a better job with this and intercept the error message to provide better feedback)

**Comment by cruzach** [comment] 2019-11-08 16:17
closing this in favor of https://github.com/expo/expo-cli/issues/1186 since the `econrefused` error was reported more succinctly there, and it seems the original issue is resolved in a newer version of `expo-cli`

**Closed by cruzach** 2019-11-08 16:17 UTC
Labels: question
