### ISSUE TITLE
[dev-tools] update graphql dependency

### ISSUE THREAD

**Issue by dacevedo12** [expo/expo-cli#2025] opened 2020-04-28 12:45 UTC
## Description

In projects that use modern versions of graphql js there's a conflict that will make devtools fail to load since it uses an outdated version.

## Expected Behavior

Devtools loading properly

## Observed Behavior

No error in terminal or console, just:
![image](https://user-images.githubusercontent.com/29694570/80488417-ec53d880-8923-11ea-9387-ad2b72fddaef.png)

## Environment

Expo CLI 3.19.2 environment info:
    System:
      OS: Linux 4.15 Deepin 15 15.11
      Shell: 4.4.12 - /bin/bash
    Binaries:
      Node: 10.20.1 - /usr/bin/node
      npm: 6.14.4 - /usr/bin/npm
    npmPackages:
      expo: 37.0.8 => 37.0.8 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4

**Comment by jkhales** [comment] 2020-04-30 13:10
Hi! Thanks for writing in. In order to address this bug we need a reproducible example. Would you be able to provide us with link to a github repo that illustrates this issue?

**Comment by arlyon** [comment] 2020-05-21 16:57
I am also interested in this issue but for another reason. graphql 0.13 causes issues with expo web, a bug that was fixed in 14.x

While this may not contribute directly, it is one of 2 packages that provides 0.13 (the other being aws-appsync).

**Comment by diegolaciar** [comment] 2020-07-08 02:46
I just did the upgrade from expo 37 to expo 38 

I get the same black screen with the message "Error loading DevTools".


```bash
  Expo CLI 3.22.0 environment info:
    System:
      OS: macOS 10.15.5
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      npm: 6.14.5 - ~/.nvm/versions/node/v12.16.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      @expo/webpack-config: ^0.12.16 => 0.12.18
      expo: ^38.0.0 => 38.0.8
      react: 16.11.0 => 16.11.0
      react-dom: 16.11.0 => 16.11.0
      react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
      react-native-web: ~0.11.7 => 0.11.7
```

**Comment by brentvatne** [comment] 2020-07-16 23:19
can someone please provide a reproducible example of this?

**Comment by dacevedo12** [comment] 2021-06-03 20:13
Hey @brentvatne, you can reproduce it in a blank project just by installing graphql@latest

This is a common use case for projects who use apollo or other graphql clients for their app

1. npx expo-cli init test --template blank && cd test
2. npm install --save-exact graphql@15.5.0 expo-cli@4.5.2
3. npx expo-cli start

**Comment by brentvatne** [comment] 2021-06-03 20:16
please don't install expo-cli to your project dependencies. it's intended to be installed globally.

**Closed by brentvatne** 2021-06-03 20:16 UTC
Labels: needs more info

**Comment by LinusU** [comment] 2021-08-31 12:05
> you should always use the latest version of expo-cli so there will not a problem with conflicting versions across projects

@brentvatne does this mean that you the project is officially committing to never making any breaking changes and always work with older `app.json` iterations, SDK versions, and command line flags/arguments?

Because I don't really see how this is going to work with CI/CD, multiple developers, multiple projects, and older versions of the same project. To put it into some more concrete questions:

1. Are we supposed to always install the latest version of `expo-cli` on our CI?
1. When a breaking change is made to `expo-cli`, are we supposed to not be able to build any old commits/branches?
1. Does this mean that reproducible builds are explicitly not supported?

-----

Also, what is the motivation for this. Is it only because peer dependencies might conflict with others? I believe that that is technically possible in global installs as well, no?

I've been meaning to submit another proposal for an improvement, which would actually solve this as well. Using [vercel/ncc](https://github.com/vercel/ncc) or a similar tool to package the cli into one file before shipping it. I think that this is a great approach for CLIs since you get 100% control over exactly all dependencies, and the installation and startup time should be greatly decreased!

If this is something that could be of interest I'd be happy to open a separate issue to discuss that.

**Comment by brentvatne** [comment] 2021-11-25 20:39
1. yes, this is recommended. i think it is also reasonable to bump the version every time you do an sdk update. occasionally there may be breaking changes in the network calls that interact with expo servers which require an update. this is one of the main reasons we ask people to stay up to date to latest.
2. you can use an older version of expo-cli if your app is impacted by a breaking change somehow. we only aim to provide support for the 4 most recent sdk versions. keep in mind that if you are not using one of the most recent sdks your project may not even build with the latest versions of the underlying tools like xcode, and may not work with the latest version of the corresponding operating system.
3. for our supported sdk versions, yes. i'll outline below where we're moving with expo-cli.

> Also, what is the motivation for this. Is it only because peer dependencies might conflict with others? I believe that that is technically possible in global installs as well, no?

dependencies can conflict with others, yes. in theory you are right but we have seen this occur frequently with local installs and zero times with global installs (except in the case of yarn and eas-cli, but that's a different story).

> I've been meaning to submit another proposal for an improvement, which would actually solve this as well. Using vercel/ncc or a similar tool to package the cli into one file before shipping it.

@EvanBacon has explored this in depth and it's not currently practical for us to use ncc on expo-cli, he can elaborate on that when he has some time.

### plan for expo-cli

the direction we are heading in is to split out anything necessary to run your app out of expo-cli and into a versioned package that is installed directly to your project. this will mean that anything needed to create a reproducible build with expo's tooling will be encapsulated in your package.json.

expo-cli a year from now will be a very different package as we [sunset "expo build" and replace it entirely with EAS Build](https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60), which allows us to move most interaction with our services away from expo-cli and related tools.
