### ISSUE TITLE
the experience you requested requires a newer version of the expo client app

### ISSUE THREAD

**Issue by superandrew** [expo/expo-cli#2984] opened 2020-12-02 21:48 UTC
## Description
When upgrading to expo 39 from 38, everything was fine, but in app.json the indicated SDK version was 40.0.0. This triggered the error:
the experience you requested requires a newer version of the expo client app both on phone and simulator.

## Expected Behavior
Upgrade works

## Observed Behavior
The wrong version is reported in app.json

```
the experience you requested requires a newer version of the expo client app
```

## Environment

❯ expo diagnostics

  Expo CLI 4.0.7 environment info:
    System:
      OS: macOS 11.0.1
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 7.0.10 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    Managers:
      CocoaPods: 1.10.0 - /Users/superandrew/.rvm/gems/ruby-2.6.5/bin/pod
    SDKs:
      iOS SDK:
        Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    IDEs:
      Android Studio: 4.1 AI-201.8743.12.41.6858069
      Xcode: 12.2/12B45b - /usr/bin/xcodebuild
    npmPackages:
      expo: ^39.0.0 => 39.0.5 
      react: 16.13.1 => 16.13.1 
      react-dom: 16.13.1 => 16.13.1 
      react-native: https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz => 0.63.2 
      react-native-web: ~0.13.7 => 0.13.18 
      react-navigation: ^4.3.9 => 4.4.0 
    npmGlobalPackages:
      expo-cli: 4.0.7
    Expo Workflow: managed

## Reproducible Demo

Sorry, I cannot provide a reproducible demo.

**Comment by brentvatne** [comment] 2020-12-02 22:21
hi there! can you clarify what you did exactly? we need a concrete set of steps

**Comment by brentvatne** [comment] 2020-12-02 22:23
i tried upgrading an sdk 38 project to sdk 39 and it worked as expected:

```
╭─~/code
╰─$ expo init blanky -t blank@sdk-38
✔ Downloaded and extracted project files.

🧶 Using Yarn to install packages. You can pass --npm to use npm instead.

✔ Installed JavaScript dependencies.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd blanky
- yarn start # you can open iOS, Android, or web from here, or run them directly with the commands below.
- yarn android
- yarn ios
- yarn web
╭─~/code
╰─$ cd blanky
╭─~/code/blanky ‹master›
╰─$ ls
App.js          app.json        assets          babel.config.js node_modules    package.json    yarn.lock
╭─~/code/blanky ‹master›
╰─$ vim package.json
╭─~/code/blanky ‹master›
╰─$ expo upgrade
Your git working tree is clean
To revert the changes after this command completes, you can run the following:
  git clean --force && git reset --hard

✔ You are currently using SDK 38.0.0. Would you like to update to the latest version, 39.0.0? … yes

✔ Would you like to upgrade the Expo app in the iOS simulator? … no

✔ Would you like to upgrade the Expo app in the Android emulator? … no

✔ Installed expo@^39.0.0
✔ Validated configuration.
✔ No additional changes necessary to app.json config.
✔ Updated known packages to compatible versions.
✔ Cleared packager cache.

👏 Automated upgrade steps complete.
...but this doesn't mean everything is done yet!

✅ The following packages were updated:
expo-status-bar, react-native, react, react-dom, react-native-web, babel-preset-expo, expo

🚨 The following packages were not updated. You should check the READMEs for those repositories to determine what version is compatible with your new set of packages:
@babel/core

Please refer to the release notes for information on any further required steps to update and information about breaking changes:
https://dev.to/expo/expo-sdk-39-is-now-available-1lm8
```

app.json:

```
{
  "expo": {
    "name": "blanky",
    "slug": "blanky",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  }
}
```

package.json:

```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^39.0.0",
    "expo-status-bar": "~1.0.2",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-39.0.3.tar.gz",
    "react-native-web": "~0.13.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "^8.3.0"
  },
  "private": true
}
```

**Comment by brentvatne** [comment] 2020-12-02 22:24
closing until you can provide more info

**Comment by superandrew** [comment] 2020-12-02 22:24
sure, I hope.

I was in a expo 38 project and just did expo upgrade and then wait for it to finish.

When the project didn't run on my simulator I found the reason watching a git diff.

I thought I did something wrong like installing the expo 40 beta, so I stashed and restarted and in the end the 40 version was still there on app.json. 

Changed to 39 and everything was working as expected.

**Closed by brentvatne** 2020-12-02 22:24 UTC

**Comment by superandrew** [comment] 2020-12-02 22:27
@brentvatne you can close it if you want, in my case I fixed it locally, however there's a bug somewhere I guess because the sdk version to 40 wasnt upgraded by anyone but the expo-cli.

Sorry but I'm not sure how to reproduce it. But it does it every time.

**Comment by superandrew** [comment] 2020-12-02 22:29
I honestly brought this issue here for the benefit of others finding this problem in the future because I already solved it locally.

Also, two notes: I answered yes wether to upgrade the ios app in the simulator. Maybe the problem could be there?

**Comment by brentvatne** [comment] 2020-12-02 22:35
> Sorry but I'm not sure how to reproduce it. But it does it every time.

it'd be helpful to give me more information on how i could re-create your initial conditions, given that in a blank new sdk-38 project upgrading to sdk-39 this doesn't happen.

further, if i add `"sdkVersion": "38.0.0"` to app.json then this will just be removed when you upgrade, because this property is not used anymore.

> Also, two notes: I answered yes wether to upgrade the ios app in the simulator. Maybe the problem could be there?

tried that, worked as expected on my side

> I thought I did something wrong like installing the expo 40 beta, so I stashed and restarted and in the end the 40 version was still there on app.json.

do you possibly have an older version of expo-cli installed in your project dependencies that is being used when you run `expo upgrade`?

**Comment by brentvatne** [comment] 2020-12-02 22:36
> I honestly brought this issue here for the benefit of others finding this problem in the future because I already solved it locally.

that's appreciated! from my point of view, we need to have steps to reproduce outlined in issues, because if we can't reproduce the problem then it's often just a user error.

**Comment by superandrew** [comment] 2020-12-02 22:40
> further, if i add `"sdkVersion": "38.0.0"` to app.json then this will just be removed when you upgrade, because this property is not used anymore.

Didn't know that but now that you told me, I first noticed that the version was deleted in app.json, then when I restarted with expo r and watched again the sdk 40.0.0 was there. So maybe the problem is there, I'll look into it.

> do you possibly have an older version of expo-cli installed in your project dependencies that is being used when you run `expo upgrade`?

I will check that as well, even if before upgrading I did a `npm install -g expo-cli` so it is unlikely.

**Comment by superandrew** [comment] 2020-12-02 22:41
> that's appreciated! from my point of view, we need to have steps to reproduce outlined in issues, because if we can't reproduce the problem then it's often just a user error.

I think it's safe to keep the issue closed and in case someone pops out with the same error, maybe that would help. However if I find anything useful I will report it back here.

**Comment by brentvatne** [comment] 2020-12-02 22:44
if you can reproduce this reliably could you rollback and run the command again and paste the full output of the upgrade command here?
