### ISSUE TITLE
expo-cli 3.19.2|3.20.0 - expo:build:ios failing on certs 

### ISSUE THREAD

**Issue by 1337LutZ** [expo/expo-cli#2046] opened 2020-04-29 15:41 UTC
## Description
Upgrading to latest expo (3.19.2 and 3.20.0) breaks our CI --non-interactie build.

## Expected Behavior
Reverting back to expo 3.18.6 shows the correct behavior.

```
[15:31:26] Authenticating to Apple Developer Portal...
[15:31:31] Authenticated with Apple Developer Portal successfully!
[15:31:31] Using Apple Team with ID: REDACTED
[15:31:31] Fetching available credentials
- Ensuring App ID exists on Apple Developer Portal...
✔ App ID found on Apple Developer Portal.
- Checking validity of distribution certificate on Apple Developer Portal...
- Getting Distribution Certificates from Apple...
✔ Getting Distribution Certificates from Apple...
✖ The Distribution Certificate is no longer valid on the Apple Developer Portal
[15:31:40] Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:
[15:31:40]
[15:31:40] Project Credential Configuration:
[15:31:40]   Experience: REDACTED, bundle identifier: REDACTED
[15:31:40]     Provisioning profile (ID: ---------)
[15:31:40]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[15:31:40]
[15:31:40]   Distribution Certificate - Certificate ID: -----
[15:31:40]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[15:31:40]     used by
      REDACTED
[15:31:40]   Push Notifications Key - Key ID: REDACTED
[15:31:40]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[15:31:40]     used by
      REDACTED
[15:31:40] Looking for releases...
[15:31:40] Using existing release on channel "REDACTED":
REDACTED
[15:31:40] Checking if this build already exists...
[15:31:42] Build started, it may take a few minutes to complete.
[15:31:42] You can check the queue length at https://expo.io/turtle-status
```
## Observed Behavior
When using expo-cli 3.19.2 and 3.20.0 it will always fail on checking the certificate. Please ignore `✖ The Distribution Certificate is no longer valid on the Apple Developer Portal`, it seems that this is incorrect as all the certificates have been tested. It seems to be a false positive since when building in the older expo-cli version it all works regardless.

When using the default interactive mode locally it however works after assigning all the certs manually.

```
[15:11:06] Fetching available credentials
- Ensuring App ID exists on Apple Developer Portal...
✔ App ID found on Apple Developer Portal.
- Checking validity of distribution certificate on Apple Developer Portal...
- Getting Distribution Certificates from Apple...
✔ Getting Distribution Certificates from Apple...
✖ The Distribution Certificate is no longer valid on the Apple Developer Portal
[15:11:14] Failed to set up Distribution Certificate
[15:11:14] Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:
[15:11:14]
[15:11:14] Project Credential Configuration:
[15:11:14]   Experience: REDACTED, bundle identifier: REDACTED
[15:11:14]     Provisioning profile (ID: ---------)
[15:11:14]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[15:11:14]
[15:11:14]   Distribution Certificate - Certificate ID: -----
[15:11:14]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[15:11:14]     used by
      REDACTED
[15:11:14]   Push Notifications Key - Key ID: REDACTED
[15:11:14]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[15:11:14]     used by
      REDACTED
[15:11:14] Cannot validate uploaded Distribution Certificate
[15:11:14] Error: Cannot validate uploaded Distribution Certificate
    at useDistCertFromParams (/Users/vagrant/.config/yarn/global/node_modules/expo-cli/src/credentials/views/IosDistCert.ts:685:11)
```

## Environment
Production
on Bitrise CI Mac OS Catalina xCode 11.4.x

## Reproducible Demo
```
expo build:ios --release-channel [REDACTED] --non-interactive --no-publish --apple-id [REDACTED] --team-id [REDACTED] --dist-p12-path [REDACTED] --push-id REDACTED --push-p8-path [REDACTED] --provisioning-profile-path [REDACTED]
```

I can see that there are multiple commits that are supposed to fix credential handling in non-interactive mode. My guess is that this broke it.
For instance: https://github.com/expo/expo-cli/commit/c94638e57d3b4df3b9eb256c07e2b8d9f031b3cd#diff-d46165831c897488fae75813f947e880

**Comment by quinlanj** [comment] 2020-04-29 21:39
@1337LutZ Does the build end up succeeding? I'm seeing the error message `The Distribution Certificate is no longer valid on the Apple Developer Portal`

**Comment by 1337LutZ** [comment] 2020-04-30 06:55
Hi Quin,

No, it does not succeed in the latest version. In the old one it does.

The certificates have all been checked and verified we even generated new ones. 

As I described, without `--non-interactive` it works. It is only erroring and failing on the non-interactive mode.

**Comment by quinlanj** [comment] 2020-04-30 18:27
@1337LutZ to help root cause the problem could you send your username/email to secure@expo.io along with the relevant build links? thanks!

**Comment by quinlanj** [comment] 2020-04-30 19:31
Also, could you try running the build command in non-interactive mode without any of the other build flags and report back whether that build succeeds?
```
expo build:ios --non-interactive
```

**Comment by 1337LutZ** [comment] 2020-04-30 19:37
> @1337LutZ to help root cause the problem could you send your username/email to [secure@expo.io](mailto:secure@expo.io) along with the relevant build links? thanks!

There are no build links to be shared, as it already errors in the cli. Nothing has been pushed to the Expo build street.

> Also, could you try running the build command in non-interactive mode without any of the other build flags and report back whether that build succeeds?

It only happens on when we use our store release channel. Without flags or other channels it wont fail. Could it be related to something else in that case? As the credentials/certs that are being used in that channel are created by us, however the account where we created the credentials for merely gave us access?

See ticket: https://github.com/expo/expo-cli/pull/1941

**Comment by quinlanj** [comment] 2020-05-01 23:31
My hypothesis is that you've got a valid set of credentials for your project stored on our servers, but are passing in an invalid set in the build flags. Build flags should always take precedence, and in the old cli, we should have errored fatally (we fixed this in the 3.19.2). Once the request got to our servers to build the ipa, we used the valid set of credentials we have stored on the servers. 

Regarding the builds not working in the other account, this issue should be fixed in 3.19.2 and above. Make sure you have the `owner` field set to the proper account. 

Really sorry you've run into all these issues :( Happy to help you debug in real time on the developers slack to help fix your build issue if you want, would get you unblocked quicker that way

**Comment by 1337LutZ** [comment] 2020-05-02 09:05
Hi Quin,

Thanks for all your help! Locally it seems to work with non-interactive mode, after I removed and reuploaded some certs.

Is there a way to remove all the certs for a specific project? Im not sure how the --clear-credentials and --clear-dist works. Does it remove ALL of my Expo credentials or just for the specific project?

**Comment by 1337LutZ** [comment] 2020-05-02 18:23
Just ran it again on the CI since I had to do a release and got the same error:

```
- Ensuring App ID exists on Apple Developer Portal...
✔ App ID found on Apple Developer Portal.
- Checking validity of distribution certificate on Apple Developer Portal...
- Getting Distribution Certificates from Apple...
✔ Getting Distribution Certificates from Apple...
✖ The Distribution Certificate is no longer valid on the Apple Developer Portal
[18:12:32] Failed to set up Distribution Certificate
[18:12:32] Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:
[18:12:32]
[18:12:32] Project Credential Configuration:
[18:12:32]   Experience: REDACTED, bundle identifier: REDACTED
[18:12:32]     Provisioning profile (ID: ---------)
[18:12:32]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[18:12:32]
[18:12:32]   Distribution Certificate - Certificate ID: -----
[18:12:32]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[18:12:32]     used by
      REDACTED
[18:12:32]   Push Notifications Key - Key ID: REDACTED
[18:12:32]     Apple Team ID: REDACTED,  Apple Team Name: ---------
[18:12:32]     used by
      REDACTED
[18:12:32] Cannot validate uploaded Distribution Certificate
[18:12:32] Error: Cannot validate uploaded Distribution Certificate
    at useDistCertFromParams (/Users/vagrant/.config/yarn/global/node_modules/expo-cli/src/credentials/views/IosDistCert.ts:685:11)
|                                                                              |
```

The keys being presented by CLI are however correct. When switching to 3.18.6 it works.

**Comment by soconrep** [comment] 2020-05-04 04:04
I have same issue 

expo build:ios --push-id REDACTED --push-p8-path REDACTED --apple-id REDACTED --team-id REDACTED --dist-p12-path REDACTED --provisioning-profile-path REDACTED
? Choose the build type you would like: archive

Checking if there is a build in progress...

Configuring credentials for mappsolazu in project mAPP
Authenticating to Apple Developer Portal...
Authenticated with Apple Developer Portal successfully!
Using Apple Team with ID: REDACTED
Fetching available credentials
✔ App ID found on Apple Developer Portal.
✔ Getting Distribution Certificates from Apple...
✖ The Distribution Certificate is no longer valid on the Apple Developer Portal
Failed to set up Distribution Certificate
Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:

Project Credential Configuration:
  Experience: REDACTED, bundle identifier: REDACTED
    Provisioning profile is missing. It will be generated during the next build

  Distribution Certificate - Certificate ID: -----
    Apple Team ID: REDACTED,  Apple Team Name: ---------
    used by
      REDACTED
Cannot validate uploaded Distribution Certificate
Error: Cannot validate uploaded Distribution Certificate
    at useDistCertFromParams (/usr/local/lib/node_modules/expo-cli/src/credentials/views/IosDistCert.ts:685:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by quinlanj** [comment] 2020-05-04 22:46
@1337LutZ @soconrep Can you use this alpha version of the cli i published:`expo-cli@3.20.2-alpha.0`? I'm unable to repro your problem on my end, and it'd be immensely helpful if you could let me know whether the debug logs look right to you. In particular, when you run `expo-cli@3.20.2-alpha.0`, you should see this:

```
✔ Getting Distribution Certificates from Apple...
[15:38:15] ==== Hello! Thank you for running this debug version of expo-cli ====
[15:38:15] We've received these distribution certificates from your Apple Account: 
[15:38:15] [THE DIST CERTS ON YOUR APPLE ACCOUNT SHOULD BE SHOWN HERE]
[15:38:15] We've received these distribution certificates as input from you: 
[15:38:15] [THE DIST CERT YOU UPLOADED SHOULD BE SHOWN HERE]
[15:38:15] Failed to set up Distribution Certificate
 ....
[15:38:15] **** Please update https://github.com/expo/expo-cli/issues/2046 with your findings ****
```
In particular, the serial numbers of the distribution certificates should match up.

**Comment by soconrep** [comment] 2020-05-05 02:58
@quinlanj  I try your version but diff error occurs.  Check info below.



> expo diagnostics
>   Expo CLI 3.20.2-alpha.0 environment info:
>     System:
>       OS: macOS 10.15.4
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.17.0 - /usr/local/opt/node@10/bin/node
>       Yarn: 1.19.2 - /usr/local/bin/yarn
>       npm: 6.11.3 - /usr/local/opt/node@10/bin/npm
>     IDEs:
>       Android Studio: 3.5 AI-191.8026.42.35.5977832
>       Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ~37.0.3 => 37.0.8 
>       react: ~16.9.0 => 16.9.0 
>       react-dom: ~16.9.0 => 16.9.0 
>       react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
>       react-native-web: ~0.11.7 => 0.11.7 
>     npmGlobalPackages:
>       expo-cli: 3.20.2-alpha.0
> 
> expo build:ios --push-id REDACTED --push-p8-path REDACTED --team-id REDACTED --apple-id l REDACTED --dist-p12-path REDACTED --provisioning-profile-path REDACTED
> ? Choose the build type you would like: archive
> 
> Checking if there is a build in progress...
> 
> Configuring credentials for mappsolazu in project REDACTED
> Authenticating to Apple Developer Portal...
> Available session is not valid any more. Continuing with normal login.
> Authentication with Apple Developer Portal failed!
> Reason: Invalid credentials, raw: "Invalid username and password combination. Used 'REDACTED' as the username."
> Error: Reason: Invalid credentials, raw: "Invalid username and password combination. Used 'REDACTED' as the username."
    at runAction (/usr/local/lib/node_modules/expo-cli/src/appleApi/fastlane.ts:28:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

is there issue between apple portal and fastlane?

**Comment by bayoremit** [comment] 2020-05-08 12:12
+1

Except i am letting Expo fully manage the apple creds

**Diag**
```
Expo CLI 3.19.1 environment info:
System:
    OS: macOS 10.15.3
    Shell: 5.7.1 - /bin/zsh
Binaries:
    Node: 12.16.2 - ~/.nvm/versions/node/v12.16.2/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.2/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
npmPackages:
    expo: 37.0.8 => 37.0.8 
    react: 16.9.0 => 16.9.0 
    react-native: https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz => 0.61.4 
npmGlobalPackages:
    expo-cli: 3.20.1
```

**Error**
```
Authenticating to Apple Developer Portal...
Authenticated with Apple Developer Portal successfully!
Only 1 team associated with your account, using Apple Team with ID: REDACTED
Fetching available credentials
✔ App ID found on Apple Developer Portal.
Failed to set up Distribution Certificate
Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:

Project Credential Configuration:
  Experience: REDACTED, bundle identifier: REDACTED
    Provisioning profile (ID: REDACTED)
    Apple Team ID: REDACTED,  Apple Team Name: ---------

  Distribution Certificate - Certificate ID: REDACTED
    Apple Team ID: REDACTED,  Apple Team Name: ---------
    used by
      REDACTED (REDACTED)
  Push Notifications Key - Key ID: REDACTED
    Apple Team ID: REDACTED,  Apple Team Name: ---------
    used by
      REDACTED (REDACTED)
In order to provide a Distribution Certificate through the CLI parameters, you have to pass --dist-p12-path parameter, --team-id parameter and set EXPO_IOS_DIST_P12_PASSWORD environment variable.
Error: In order to provide a Distribution Certificate through the CLI parameters, you have to pass --dist-p12-path parameter, --team-id parameter and set EXPO_IOS_DIST_P12_PASSWORD environment variable.
    at getDistCertFromParams (/Users/server/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/credentials/views/IosDistCert.ts:665:11)
    at IOSBuilder._setupDistCert (/Users/server/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:175:40)
    at IOSBuilder.produceCredentials (/Users/server/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:258:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at IOSBuilder.prepareCredentials (/Users/server/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:130:7)
    at IOSBuilder.run (/Users/server/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/build/ios/IOSBuilder.ts:51:7)
    at IOSBuilder.command (/Users/server/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/commands/build/BaseBuilder.ts:29:7)
    at Command.<anonymous> (/Users/server/.nvm/versions/node/v12.16.2/lib/node_modules/expo-cli/src/exp.ts:85:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bayoremit** [comment] 2020-05-08 12:19
Umm seems this is because i have EXPO_IOS_DIST_P12_PASSWORD set as an env for when i use turtle-cli for builds. Is the solution here to not set those env vars?

**Comment by 1337LutZ** [comment] 2020-05-08 12:59
@bayoremit I think it says you are missing them. My issue isnt with turtle-cli, but when you use custom certificates you also need to provide the matching ENV variables as the error describes.

**Comment by bayoremit** [comment] 2020-05-08 13:08
Thanks @1337LutZ I rely on Expo to manage my certs so i never provide them, I setup turtle as a backup when the expo servers are down and with the latest update, it seems having them in my ENV vars conflicts with having Expo manage the build process + certs. Looks like with the latest update, i will need to unset the ENV vars to ensure expo build (fully managed) works

**Comment by 1337LutZ** [comment] 2020-05-08 13:31
That's weird. I tried the turtle CLI on Expo 3.20.x and there i had to set the vars.
Since the error also says this on your end: `In order to provide a Distribution Certificate through the CLI parameters, you have to pass --dist-p12-path parameter, --team-id parameter and set EXPO_IOS_DIST_P12_PASSWORD environment variable.`

Maybe your build task doesn't have these vars available?

**Comment by bayoremit** [comment] 2020-05-08 13:34
Potentially... Thanks for checking

**Comment by 1337LutZ** [comment] 2020-05-16 13:41
Hi @quinlanj,
Sorry for my late response. In the end we did what you suggested and used `expo credentials:manager` to manage our credentials. I have removed all the cert flags from the build and now Expo handles everything (using our uploaded certs). 

Thanks again for your help!

**Comment by soconrep** [comment] 2020-05-18 04:37
I still can not build with iOS 

``` expo diagnostics

  Expo CLI 3.20.9 environment info:
    System:
      OS: macOS 10.15.4
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.20.1 - /usr/local/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.14.4 - /usr/local/bin/npm
    IDEs:
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.10 
      react: ~16.9.0 => 16.9.0 
      react-dom: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
      react-native-web: ~0.11.7 => 0.11.7 
    npmGlobalPackages:
      expo-cli: 3.20.9
```
```
 expo build:ios --push-id REDACTED --apple-id REDACTED --team-id REDACTED --dist-p12-path REDACTED.p12 --provisioning-profile-path REDACTED.mobileprovision
⚠️  expo build:ios currently only supports managed workflow apps.
If you proceed with this command, we can run the build for you but it will not include any custom native modules or changes that you have made to your local native projects.
Unless you are sure that you know what you are doing, we recommend aborting the build and doing a native release build through Xcode.
? Would you like to proceed? Yes
? Choose the build type you would like: archive

Checking if there is a build in progress...

Configuring credentials for REDACTED in project REDACTED
Authenticating to Apple Developer Portal...
Authenticated with Apple Developer Portal successfully!
Using Apple Team with ID: REDACTED
Fetching available credentials
✔ App ID found on Apple Developer Portal.
✔ Getting Distribution Certificates from Apple...
✖ The Distribution Certificate is no longer valid on the Apple Developer Portal
Failed to set up Distribution Certificate
Failed to prepare all credentials. 
The next time you build, we will automatically use the following configuration:

Project Credential Configuration:
  Experience: @ REDACTED, bundle identifier: REDACTED
    Provisioning profile is missing. It will be generated during the next build

Cannot validate uploaded Distribution Certificate
Error: Cannot validate uploaded Distribution Certificate
    at useDistCertFromParams (/usr/local/lib/node_modules/expo-cli/src/credentials/views/IosDistCert.ts:684:11)
    at process._tickCallback (internal/process/next_tick.js:68:7).
```

**Comment by 1337LutZ** [comment] 2020-05-18 06:43
> I still can not build with iOS
> 
> ```
> 
>   Expo CLI 3.20.9 environment info:
>     System:
>       OS: macOS 10.15.4
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 10.20.1 - /usr/local/bin/node
>       Yarn: 1.19.1 - /usr/local/bin/yarn
>       npm: 6.14.4 - /usr/local/bin/npm
>     IDEs:
>       Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
>     npmPackages:
>       expo: ~37.0.3 => 37.0.10 
>       react: ~16.9.0 => 16.9.0 
>       react-dom: ~16.9.0 => 16.9.0 
>       react-native: ~0.61.5 => 0.61.5 
>       react-native-web: ~0.11.7 => 0.11.7 
>     npmGlobalPackages:
>       expo-cli: 3.20.9
> ```
> 
> ```
>  expo build:ios --push-id REDACTED --apple-id REDACTED --team-id REDACTED --dist-p12-path REDACTED.p12 --provisioning-profile-path REDACTED.mobileprovision
> ⚠️  expo build:ios currently only supports managed workflow apps.
> If you proceed with this command, we can run the build for you but it will not include any custom native modules or changes that you have made to your local native projects.
> Unless you are sure that you know what you are doing, we recommend aborting the build and doing a native release build through Xcode.
> ? Would you like to proceed? Yes
> ? Choose the build type you would like: archive
> 
> Checking if there is a build in progress...
> 
> Configuring credentials for REDACTED in project REDACTED
> Authenticating to Apple Developer Portal...
> Authenticated with Apple Developer Portal successfully!
> Using Apple Team with ID: REDACTED
> Fetching available credentials
> ✔ App ID found on Apple Developer Portal.
> ✔ Getting Distribution Certificates from Apple...
> ✖ The Distribution Certificate is no longer valid on the Apple Developer Portal
> Failed to set up Distribution Certificate
> Failed to prepare all credentials. 
> The next time you build, we will automatically use the following configuration:
> 
> Project Credential Configuration:
>   Experience: @ REDACTED, bundle identifier: REDACTED
>     Provisioning profile is missing. It will be generated during the next build
> 
> Cannot validate uploaded Distribution Certificate
> Error: Cannot validate uploaded Distribution Certificate
>     at useDistCertFromParams (/usr/local/lib/node_modules/expo-cli/src/credentials/views/IosDistCert.ts:684:11)
>     at process._tickCallback (internal/process/next_tick.js:68:7).
> ```

Try to use the expo credentials:manager and just run the build with Expo managing the correct certs after uploading them manually once.

Command should look something like this:
``` 
expo build:ios --apple-id REDACTED --team-id REDACTED
```
**Note** You will need to remove the P12 password ENV var, but leave the APPLE_PASSWORD in place.

**Comment by soconrep** [comment] 2020-05-18 14:51
@1337LutZ thanks for reply. 
my certificate is 
`Apple Distribution
Sign your apps for submission to the App Store or for Ad Hoc distribution. For use with Xcode 11 or later.` and cannot upload to expo server.
While i also try with `iOS Distribution (App Store and Ad Hoc)
Sign your iOS app for submission to the App Store or for Ad Hoc distribution.` , and success upload to expo server .
I don't understand the difference between them. because I use turtle-cli  build in my pc . and it cannot build with iOS Distribution

**Comment by 1337LutZ** [comment] 2020-05-18 14:53
@soconrep What does your `turtli-cli` command look like? (redact any privacy sensitive information)

**Comment by soconrep** [comment] 2020-05-18 15:30
@1337LutZ 
my turtle-cli command: `turtle build:ios --team-id REDACTED --public-url REDACTED --dist-p12-path ios-mapps.p12 --provisioning-profile-path ios.mobileprovision` . and error below:
```
May 18 22:16:31 turtle[15130] INFO:     from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.0/bin/fastlane:23:in `<top (required)>'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
May 18 22:16:31 turtle[15130] INFO:     from /usr/local/bin/fastlane:23:in `load'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
May 18 22:16:31 turtle[15130] INFO:     from /usr/local/bin/fastlane:23:in `<main>'
  platform: "ios"
  buildPhase: "building and signing IPA"
  source: "stderr"
May 18 22:16:31 turtle[15130] INFO:  removed provisioning profile from the home directory
  platform: "ios"
  buildPhase: "building and signing IPA"
May 18 22:16:31 turtle[15130] ERROR: Error: fastlane exited with non-zero code: 1
    at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Pipe._handle.close (net.js:607:12)
    ...
    at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
    at spawnAsyncThrowError (/@expo/xdl@57.8.30/src/detach/ExponentTools.ts:100:19)
    at runFastlane (/@expo/xdl@57.8.30/src/detach/IosCodeSigning.js:324:9)
    at Object.buildIPA (/@expo/xdl@57.8.30/src/detach/IosCodeSigning.js:137:11)
    at Object.build (/@expo/xdl@57.8.30/src/detach/IosIPABuilder.js:67:28)
  platform: "ios"
May 18 22:16:31 turtle[15130] INFO:  delete keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
May 18 22:16:31 turtle[15130] INFO:  deleting keychain...
  platform: "ios"
  buildPhase: "deleting keychain"
May 18 22:16:39 turtle[15130] INFO:  done deleting keychain
  platform: "ios"
  buildPhase: "deleting keychain"
May 18 22:16:39 turtle[15130] ERROR: Failed to build standalone app
  err: Error: fastlane exited with non-zero code: 1
      at ChildProcess.completionListener (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:65:13)
      at Object.onceWrapper (events.js:286:20)
      at ChildProcess.emit (events.js:198:13)
      at ChildProcess.EventEmitter.emit (domain.js:448:20)
      at maybeClose (internal/child_process.js:982:16)
      at Socket.stream.socket.on (internal/child_process.js:389:11)
      at Socket.emit (events.js:198:13)
      at Socket.EventEmitter.emit (domain.js:448:20)
      at Pipe._handle.close (net.js:607:12)
      ...
      at spawnAsync (/usr/local/lib/node_modules/turtle-cli/node_modules/@expo/spawn-async/src/spawnAsync.ts:26:19)
      at spawnAsyncThrowError (/@expo/xdl@57.8.30/src/detach/ExponentTools.ts:100:19)
      at runFastlane (/@expo/xdl@57.8.30/src/detach/IosCodeSigning.js:324:9)
      at Object.buildIPA (/@expo/xdl@57.8.30/src/detach/IosCodeSigning.js:137:11)
      at Object.build (/@expo/xdl@57.8.30/src/detach/IosIPABuilder.js:67:28)
  platform: "iOS"
```
version turtle-cli : 0.14.12
Type certificate is iOS Distribution (App Store and Ad Hoc)  always error. But if I change certification is Apple Distribution build OK . Please check help me.

**Closed** 2020-06-19 15:34 UTC
Labels: needs more info

**Comment by Teracius** [comment] 2020-08-25 03:04
Hi, i had the same problem "the distribution certificate is no longer valid on the apple developer portal", 

**i solve** my problem using a different certificate in Apple, i used that on that have the name "iOS Distribution (App Store and Ad Hoc)" i got to that conclution because when you let expo manage the certificates, in Apple expo create one certificate that have that type, so i made one by myself with the same type, i downloaded and then i export it to be a file ".p12" next i put in the terminal and it worked, i hope this help.
