### ISSUE TITLE
expo-cli tunnel issues on Ubuntu

### ISSUE THREAD

**Issue by brentvatne** [expo/expo-cli#196] opened 2018-01-05 00:03 UTC
> Has anyone had luck using expo on Ubuntu. I’ve tried on the same network with no firewalls enabled the normal exp://localhost:19001 and exp://192.xx with a usb connected android, but get random java errors about not finding react-native/node_modules on exp://192.168.1 and the ngrok tunnel option straight up fails every time.
Everything works on my Mac but Linux is so much cooler, so would like to get it going.

> 14:45:39 Tunnel connected.
> 14:45:39 Project opened! You can now use the “Share” or “Device” buttons to view your project.
> 14:45:39 Switched to a LAN URL because the tunnel appears to be down. Only devices in the same network can access the app. You can restart the project to try reconnecting.

> I’ve tested ngrok (outside of expo) on a regular website and it works fine

**Comment by jakubste** [comment] 2018-11-27 14:52
From what I'm seeing it was a long time ago and not necessarily caused by expo. I'm going to close this, feel free to reopen if the issue still occurs.

**Closed by jakubste** 2018-11-27 14:52 UTC
Labels: transferred
