### ISSUE TITLE
Downloading JavaScript bundle gets stuck at 100.00%

### ISSUE THREAD

**Issue by rjkz808** [expo/expo-cli#2010] opened 2020-04-27 12:21 UTC
## Description

`expo start` in a clean project created by `expo init` gets stuck at `Downloading JavaScript bundle 100.00%` when running on Android Emulator.

I've created new expo app by running

```bash
expo init myapp
```

Then I've started expo UI with:

```bash
cd myapp
expo start
```

Then in expo UI I've pressed `Run on Android device/emulator`. It has opened Expo Client on my AVD, but it just got stuck. I haven't changed anything related to configuration and application source code, I've started expo app right after it has been initialized.

`package.json` content:

```json
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~37.0.3",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "babel-preset-expo": "~8.1.0",
    "@babel/core": "^7.8.6"
  },
  "private": true
}
```

`App.js` content:

```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default function App() {
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

## Expected Behavior

I've expected that created app will be launched on my AVD.

## Observed Behavior

![image](https://user-images.githubusercontent.com/38258624/80370945-c255d400-8899-11ea-8c38-39a7ba051b02.png)

## Environment

Output of `expo diagnostics`:

```
Expo CLI 3.19.2 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.13.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.6 AI-192.7142.36.36.6308749
      Xcode: /undefined - /usr/bin/xcodebuild
```

My AVD is `Nexus 6 API 29`, with `Android 10.0 (Google APIs)` created by Android Studio.

**Comment by brentvatne** [comment] 2020-04-28 04:24
this seems to be specific to your machine, could you try creating a new emulator?

**Comment by brentvatne** [comment] 2020-04-29 20:11
closing but if you have more info please let me know. unable to reproduce this

**Closed by brentvatne** 2020-04-29 20:11 UTC

**Comment by ElsonMds** [comment] 2020-08-07 01:50
I run on a moto g and have the same issue :(
half an hour coding and 4 hours trying to solve this problem, no success!

**Comment by mivd7** [comment] 2020-08-27 15:18
I now have the same issue on my react native project. I have this error both when trying to run in xcode simulator and on a real iPhone scanning the QR-code. It was working fine a couple of days ago, but now even when I try to revert my commits to that point it still gets stuck at 'Downloading JavaScript bundle 100.00%'

**Comment by whiteKhoukha** [comment] 2020-09-21 12:34
I am also having the same issue, any fixes?

**Comment by inimist** [comment] 2020-10-02 11:35
I am having same issue. Developing in Ubuntu 18 with iPhone 8 with iOS version 13.3.1. I was following this tutorial to build my first app but it struck.

**Comment by seanraad123** [comment] 2020-11-18 17:12
I'm also running into this issue while I'm running on the device. I can actually use the app but the 'Downloading Javascript bundle 100.00%' is always stuck at the bottom of the screen. IOS 14.0.1, expo-cli 3.28.5, node 15.1.0, react-native 39.0.3.

**Comment by MarcusSorealheis** [comment] 2020-11-22 01:49
often the same here.

**Comment by kpose** [comment] 2020-12-03 07:09
same here  as @seanraad123 mentioned. App builds but still have 'Downloading Javascript bundle 100.00%' hanging at the bottom

**Comment by thekosmix** [comment] 2020-12-18 09:06
same here :-( 
anyone solved this?

**Comment by brentvatne** [comment] 2020-12-21 19:53
@kpose @thekosmix - this could happen because your app errors before the splash screen is hidden, and so nothing is rendered and it stays up indefinitely. you should use the normal debugging techniques that you would use to find out where the problem is coming from in your app

**Comment by Olabisim** [comment] 2022-05-22 00:18
I am in full support with @brentvatne, I just encountered the error and looked everywhere could not find the solution too, but I first did was to update expo on playstore, then i started commenting my code from the app then it working fine, then i walked down my tree till I found the error.
