### ISSUE TITLE
expo init - doesn't fetch packages from private registry (EAI_AGAIN registry.npmjs.org)

### ISSUE THREAD

**Issue by RonAmihai** [expo/expo-cli#1622] opened 2020-03-02 17:17 UTC
## Description

I'm working on a private network (**without internet connection**) with [Verdaccio](https://github.com/verdaccio/verdaccio) server as NPM registry instead of npmjs.

Let's assume my Verdaccio server is running on `http://10.0.0.63:4873`. 

I've configured all my network's workstations to use the custom registry (using `npm config set registry http://10.0.0.63:4873` and `yarn config set registry http://10.0.0.63:4873`). 

Of course I've brought all the required packages of expo-cli to my registry. 
(It doesn't have any access to npmjs or any of the worldwide internet, I'm bringing packages manually using cache or/and [npm-offline-packager](https://www.npmjs.com/package/npm-offline-packager))

Installing packages from the registry works well when installing packages directly with `npm install` / `yarn add`. 

However, when I'm trying to run `expo init`, after selecting the desired template - it tries to fetch the template packages from `https://registry.npmjs.org` and not from my registry (`http://10.0.0.63:4873`).

## Expected Behavior

expo-cli should install packages from my custom registry (`http://10.0.0.63:4873`).

## Observed Behavior

expo-cli tries to install packages from `https://registry.npmjs.org`, and fails with the following error:

```
request to https://registry.npmjs.org/expo-template-bare-typescript failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
FetchError: request to https://registry.npmjs.org/expo-template-bare-typescript failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
    at ClientRequest.<anonymous> (C:\Users\ron.a\AppData\Roaming\npm\node_modules\expo-cli\node_modules\node-fetch-npm\src\index.js:68:14)
    at ClientRequest.emit (events.js:311:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## Environment

```
  Expo CLI 3.13.1 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
```

**Comment by brentvatne** [comment] 2020-03-10 23:48
duplicate of https://github.com/expo/expo-cli/issues/1586

**Closed by brentvatne** 2020-03-10 23:48 UTC
