### ISSUE TITLE
`expo export` is not producing consistent assets

### ISSUE THREAD

**Issue by guanw** [expo/expo-cli#2129] opened 2020-05-15 12:10 UTC
## Description

Not sure if this is a problem for expo or travis ci instead but want to give it a shot here first.

It seems `expo export` is not producing consistent size of assets.
e.g our travis ci job runs expo export and the total size of exported folder is 134.5MB (754 objects). But when I do this from my mac, the total size of exported folder is more than 300MB (exact 754 objects again)

![image](https://user-images.githubusercontent.com/7311035/82002897-06343180-962d-11ea-9377-4136dc08b827.png)

![image](https://user-images.githubusercontent.com/7311035/82003117-89558780-962d-11ea-82bf-54602f4f1c61.png)

I'm pretty confused about this weird behavior and curious Is there anyway that could help debug this? 

## Expected Behavior

Two exports are of same/similar size around 300MB

## Observed Behavior

Two exports are not of same size.

## Environment

travis ci:
```
  Expo CLI 3.20.6 environment info:
    System:
      OS: macOS Mojave 10.14.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.20.6

```

my own local mac:
```
  Expo CLI 3.20.1 environment info:
    System:
      OS: macOS 10.15.3
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5977832
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      expo: ^37.0.0 => 37.0.3 
      react: 16.9.0 => 16.9.0 
      react-native: https://github.com/expo/react-native/archive/sdk-37.0.0.tar.gz => 0.61.4 
    npmGlobalPackages:
      expo-cli: 3.20.1

```

**Comment by brentvatne** [comment] 2020-05-15 19:17
can you share the output?

**Comment by guanw** [comment] 2020-05-15 19:43
hi, got some updates on my side. Was able to get around this by building it in a linux vm with travis ci and `expo export` produces the right size of bundle. 

For output you mean logs?

**Comment by brentvatne** [comment] 2020-05-15 21:05
ideally the output directory rather than the logs

**Comment by brentvatne** [comment] 2020-05-21 17:55
i'll close this because we can't act on it without more information, but if you can provide me with the output results and/or a way to reproduce this reliably we would be eager to investigate!

**Closed by brentvatne** 2020-05-21 17:55 UTC
