### ISSUE TITLE
New Windows install, command not found

### ISSUE THREAD

**Issue by OliverCole** [expo/expo-cli#430] opened 2019-03-17 17:23 UTC
## Description

New Windows install of `expo-cli`. The `expo` command is not found in the PATH, and project init doesn't work.

## Expected Behavior

1. Install
2. Run

```
C:\Users\Oliver
λ npm install expo-cli --global
C:\Users\Oliver\AppData\Roaming\npm\expo -> C:\Users\Oliver\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js
C:\Users\Oliver\AppData\Roaming\npm\expo-cli -> C:\Users\Oliver\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js
npm WARN ... [snip]

+ expo-cli@2.11.9
updated 1 package in 89.211s

C:\Users\Oliver
λ expo
```

## Observed Behavior

What actually happened when you performed the above actions?

```
λ expo
'expo' is not recognized as an internal or external command,
operable program or batch file.
```

Further:

```C:\Users\Oliver
λ node C:\Users\Oliver\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js init
? Choose a template: expo-template-tabs
√ Please enter a few initial configuration values.
  Read more: https://docs.expo.io/versions/latest/workflow/configuration/ · 100% completed
? Yarn v1.13.0 found. Use Yarn to install dependencies? Yes
Extracting project files...
Customizing project...
Initialized a git repository.
Installing dependencies...
yarn install v1.13.0
info No lockfile found.
[snip yarn...]

success Saved lockfile.
Done in 168.93s.

Your project is ready at C:\Users\Oliver\fuse-v3

To get started, you can type:

  cd fuse-v3
  yarn start

C:\Users\Oliver
λ cd fuse-v3\

C:\Users\Oliver\fuse-v3 (master)
λ yarn start
yarn run v1.13.0
$ expo start
'expo-cli' is not recognized as an internal or external command,
operable program or batch file.
This command requires Expo CLI.
Do you want to install it globally [Y/n]?
Installing the package 'expo-cli'...
Expo CLI installed. You can run `expo --help` for instructions.
'expo-cli' is not recognized as an internal or external command,
operable program or batch file.
This command requires Expo CLI.
Do you want to install it globally [Y/n]?
```

(Continues infinitely...)

## Environment

```
λ node C:\Users\Oliver\AppData\Roaming\npm\node_modules\expo-cli\bin\expo.js diagnostics

  Expo CLI 2.11.9 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
```

## Reproducible Demo

N/A

**Comment by thg303** [comment] 2019-04-01 17:39
please try installing **expo-cli** globally.
`yarn add expo-cli -g`
or 
`npm install expo-cli -g`

if you couldn't run it after installation was done, try opening a new terminal and try it there.

**Comment by OliverCole** [comment] 2019-04-01 18:28
Already tried both of those things.

**Comment by kitkay** [comment] 2019-05-07 23:46
same problem here....

**Comment by thg303** [comment] 2019-05-08 07:12
please provide the output of this command and the way you've installed the node on windows.
`echo $PATH`

**Comment by OliverCole** [comment] 2019-05-08 19:27
Rather than documenting an attack surface for my PC, perhaps you could tell me what you're looking for in `PATH` ?
I note it contains `C:\Program Files\nodejs\`, but no reference to `node_modules` anywhere.

```
λ node --version
v8.11.2
```

**Comment by omar-bakhsh** [comment] 2019-05-10 20:22
try on Node.js Command 
type : npm install expo-cli -g

**Comment by OliverCole** [comment] 2019-05-10 20:24
Was that for me? That's the command in my original bug report.

**Comment by thg303** [comment] 2019-05-14 14:48
@OliverCole  honestly, your problem is not about this library (or caused by it). you may solve it by fixing your node js installation. wish you luck!

ps: your PC is not as valuable to us as you might think!

> Rather than documenting an attack surface for my PC, perhaps you could tell me what you're looking for in `PATH` ?
> I note it contains `C:\Program Files\nodejs\`, but no reference to `node_modules` anywhere.
> 
> ```
> λ node --version
> v8.11.2
> ```

**Comment by OliverCole** [comment] 2019-05-14 14:54
Not you guys, but it’s a public forum :)

@kitkay did you have any luck?

**Comment by adenekan41** [comment] 2019-06-11 21:10
this issues happened to me as well @OliverCole if you are installing the package very correctly then you might have to check if the global variable installs in the `bin` folder if not just reset you npm globally like this 

```
echo "" > $(npm config get globalconfig)
npm config --global edit
```

let me know if that works for you

**Comment by em9790** [comment] 2019-06-14 16:18
If you still have this problem, try to uninstall expo-cli or delete expo-cli folder in this path %USERPROFILE%\AppData\Roaming\npm\node_modules and then try to install it again

**Comment by satore11** [comment] 2019-06-26 18:49
Hi everyone,
I solved it this way, follow the step:

1. In Search, search for and then select: environment variables
2. Click on "Edit the system environment variables"
3. select "Advanced" tab and click on "Environment Variables"
3. In the section **User Variables for <_USERNAME_>**, find the PATH variable and select it. Click **Edit**. If the PATH variable does not exist, click **New**
4. In the **Edit System Variable** (or **New System Variable**) window, specify the value of the PATH environment variable, in my case ( C:\Users\ _Salvatore_\AppData\Roaming\npm ) change _Salvatore_ with your windows user name. Click OK. Close all remaining windows by clicking OK
5. **Reopen** Command prompt window, and run your npm global tools installed.

after this command like ```expo --version``` works fine.

I hope it's useful

**Comment by plunex** [comment] 2019-07-08 20:28
I uninstalled nodejs and re installed it.
Then run `expo --version`

**Comment by Anzormumladze** [comment] 2019-09-03 11:53
you need to install 12.9.1 version of node.js

**Comment by EricMcWinNer** [comment] 2019-09-20 00:58
> Hi everyone,
> I solved it this way, follow the step:
> 
> 1. In Search, search for and then select: environment variables
> 2. Click on "Edit the system environment variables"
> 3. select "Advanced" tab and click on "Environment Variables"
> 4. In the section **User Variables for <_USERNAME_>**, find the PATH variable and select it. Click **Edit**. If the PATH variable does not exist, click **New**
> 5. In the **Edit System Variable** (or **New System Variable**) window, specify the value of the PATH environment variable, in my case ( C:\Users\ _Salvatore_\AppData\Roaming\npm ) change _Salvatore_ with your windows user name. Click OK. Close all remaining windows by clicking OK
> 6. **Reopen** Command prompt window, and run your npm global tools installed.
> 
> after this command like `expo --version` works fine.
> 
> I hope it's useful

This worked for me

**Comment by jkhales** [comment] 2019-10-14 22:40
Closing as the issues seems resolved.

**Closed by jkhales** 2019-10-14 22:40 UTC
Labels: Installation, OS: Windows

**Comment by Peteryar** [comment] 2019-11-17 11:33
am having this issue everything said here, i have done also but still not working

**Comment by EhteshamAnwar** [comment] 2020-02-26 10:01
> am having this issue everything said here, i have done also but still not working

Same situation

**Comment by nortimg** [comment] 2020-04-04 03:24
> > am having this issue everything said here, i have done also but still not working
> 
> Same situation, any help?

I also have the same situation. Did you solve it?

**Comment by EhteshamAnwar** [comment] 2020-04-07 23:49
> > Same situation, any help?
> 
> I also have the same situation. Did you solve it?

these are the things that solve my problem, 
1.Add  %USERPROFILE%\AppData\Roaming\npm to "Path" system Variable
2.Add a new 'user variable' **NODE_PATH**  set it to %AppData%\npm\node_modules
3.Add %USERPROFILE%\AppData\Roaming\npm\node_modules\expo to "Path" system variable
**If you still have this error** 
there are 2 problems: 
1. your expo in not being installed in %USERPROFILE%\AppData\Roaming\npm\node_modules\expo , then this has to do with the temp varible in npm config. 
2. I have this problem with my computer that when I restart my computer and run expo start, I get command not found error, to get it working I only add %USERPROFILE%\AppData\Roaming\npm\node_modules\expo to Path in system variable removing previous same entry. And Expo starts working. (I know this is a workaround of this problem but it works, **if anyone knows the real solution to this particular problem please tell** )


![github answer](https://user-images.githubusercontent.com/16754151/78729174-cd7caa80-7952-11ea-87cc-89baf48080b4.png)

**Comment by AmanullaChishty** [comment] 2020-10-05 11:20
I don't know how but after breaking my head for the whole day doing this resolved the issue

yarn global add expo-cli
