### ISSUE TITLE
Cant authenticate apple developer account with expo

### ISSUE THREAD

**Issue by simdanonline** [expo/expo-cli#1927] opened 2020-04-18 21:13 UTC
While running expo build:ios
After entering Apple ID verification Code, I still get Authentication with Apple Developer Portal Failed.
Reason: unknown reason, raw: 'unathorized Access'
Set expo_debug = true in env file to view stack trace

**Comment by brentvatne** [comment] 2020-04-20 16:22
perhaps related https://github.com/fastlane/fastlane/issues/16108

**Comment by quinlanj** [comment] 2020-04-28 06:29
looks like a duplicate of https://github.com/expo/expo-cli/issues/1631 . Closing this issue so we can track any updates in the original issue

**Closed by quinlanj** 2020-04-28 06:29 UTC
Labels: 🔐 Credentials
