### ISSUE TITLE
expo ios build 2 factor pin verification invalid code

### ISSUE THREAD

**Issue by UmairSoftEngr** [expo/expo-cli#3370] opened 2021-04-07 10:58 UTC
### Summary

I have been trying to build ipa from expo cli, recently it started asking for 2 factor verification code for apple id, i have entered correct code several times from past 3 days but it gives error INVALID CODE .

note: recently i have shifted my apple developer account from individual to organisation after that it started behaving like this

### Environment

Expo CLI 4.3.4 environment info:
  System:
     OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
     Shell: 4.3.48 - /bin/bash
  Binaries:
     Node: 14.7.0 - ~/Apps/node-v14.7.0-linux-x64/bin/node
     Yarn: 1.22.5 - /usr/bin/yarn
     npm: 6.14.7 - ~/Apps/node-v14.7.0-linux-x64/bin/npm
  npmPackages:
     expo: ~38.0.8 => 38.0.11
     react: ~16.11.0 => 16.11.0
     react-dom: ~16.11.0 => 16.11.0
     react-native: https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz => 0.62.2
     react-navigation: ^4.4.0 => 4.4.4
   Expo Workflow: managed

### Please specify your device/emulator/simulator platform, model and version

expo cli

### Error output

✔ Choose the build type you would like: › archive

Checking if there is a build in progress...

Accessing credentials for ******** in project ********
✔ Do you have access to the Apple account that will be used for submitting this app to the App Store? … yes

› Log in to your Apple Developer account to continue
✔ Apple ID: … ********@*******.com
› The password is only used to authenticate with Apple and never stored on EAS servers
  Learn more: https://bit.ly/2VtGWhU
✔ Password (for ********@*******.com): … *************
› Saving Apple ID password to the local Keychain
  Learn more: https://docs.expo.io/distribution/security#keychain
✔ Logged in, verify your Apple account to continue
Two-factor Authentication (6 digit code) is enabled for ********@*******.com. Learn more: https://support.apple.com/en-us/HT204915

✔ Please enter the 6 digit code you received at +92 •••• •••••48: … ******
✖ Invalid code
Two-factor Authentication (6 digit code) is enabled for ********@*******.com. Learn more: https://support.apple.com/en-us/HT204915

✔ Please enter the 6 digit code you received at +92 •••• •••••48: … ******
✖ Invalid code
Two-factor Authentication (6 digit code) is enabled for ********@*******.com. Learn more: https://support.apple.com/en-us/HT204915

✔ Please enter the 6 digit code you received at +92 •••• •••••48: … ******
✖ Invalid code
Two-factor Authentication (6 digit code) is enabled for ********@*******.com. Learn more: https://support.apple.com/en-us/HT204915

✔ Please enter the 6 digit code you received at +92 •••• •••••48:

**Comment by aruneko** [comment] 2021-04-22 04:50
I have same error. In addition, expo-cli ignores the `FASTLANE_SESSION` environment variable because of this authentication failure.

**Comment by aruneko** [comment] 2021-05-12 03:43
I've tried the `--skip-credentials-check`  flag commented on #3432 , then resolved the problem.

**Comment by EvanBacon** [comment] 2021-08-22 23:07
This is almost exclusively caused by Apple servers, so there isn't really anything that we can do. We are working on adding App Store Connect API support to EAS Build though, but we probably won't be adding it to `expo build` since it uses a different credential system internally.

**Closed by EvanBacon** 2021-08-22 23:07 UTC
Labels: bug

**Comment by sean-repository** [comment] 2022-03-24 16:29
I've had the same issue. I went in to my apple id account and changed the mobile number on the account. Then it worked.

**Comment by Cephas-k** [comment] 2022-05-04 14:04
adding --skip-credentials-check to the build command works.
