### ISSUE TITLE
expo start crashes on Windows when system32 not present in PATH

### ISSUE THREAD

**Issue by snagu** [expo/expo-cli#403] opened 2019-03-02 18:13 UTC
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- Post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/help
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

1-2 sentences describing the problem you're having or the feature you'd like to request

## Expected Behavior

What action did you perform, and what did you expect to happen?

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
Error text goes here!
```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by bunyaminmrcn** [comment] 2019-03-03 00:24
Cross-spawn module needs to an update newer. Latest version original cross-spawn is 6.0.5 but expo-cli uses 5.0.1.
 Similar issue with that module #346

**Comment by snagu** [comment] 2019-03-06 15:43
> Cross-spawn module needs to an update newer. Latest version original cross-spawn is 6.0.5 but expo-cli uses 5.0.1.
> Similar issue with that module #346

i have even updated cross-spawn module also but it puts me a same error

**Comment by snagu** [comment] 2019-03-07 09:39
node -v
v10.15.2

npm -v
6.8.0

expo --version
2.11.6

**Comment by fson** [comment] 2019-03-08 16:58
@snagu please fill in all the information asked in the issue template and also include the steps you did or commands you ran before getting this error. This will make it a lot easier to help you!

**Comment by msalman95** [comment] 2019-05-05 11:35
![image](https://user-images.githubusercontent.com/39700096/57193339-883c4580-6f57-11e9-99f1-dc5c3e260e54.png)
Getting the same error...

![image](https://user-images.githubusercontent.com/39700096/57193353-b91c7a80-6f57-11e9-9b69-203109f36511.png)

All i did was expo init myApp

**Comment by jinhale** [comment] 2019-10-15 15:53
This is my exact issue as well - down to the character numbers. It showed up after updating npm, expo-cli, and yarn.  I only get this problem on Windows. The same projects on Linux and Macintosh work without incident. 

  Expo CLI 3.3.0 environment info:
    System:
      OS: Windows 10
    Binaries:
      Yarn: 1.19.1 - C:\Users\jhale\AppData\Roaming\npm\yarn.CMD
      npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: AI-191.8026.42.35.5791312

   "cross-spawn": { "version": "6.0.5", ...

I have tried to reinstall node, expo, & yarn. I have tried to make new projects like others have done: `expo init AwesomeApp`. I have tried `expo update`, and `expo start -c` as well. I have removed the `node_modules` folder and then used `npm i`. 

Is there anything more to try? Are there any other diagnostic data points to gather?

**Comment by jinhale** [comment] 2019-10-16 14:48
I still have the same problem after removing NPM, NodeJS, Yarn, and anything so names in  `%USERPROFIE%\AppData\{self, Local\, Local\Temp\}`.

Here is the logging information after trying another AwesomeProject:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 info lifecycle @~start: @
7 verbose lifecycle @~start: unsafe-perm in lifecycle true
8 verbose lifecycle @~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jhale\AwesomeProject\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\java-1.8.0-openjdk-1.8.0.222-4.b10.redhat.windows.x86_64\bin;C:\Program Files\Java\jdk1.8.0_221\bin;C:\Users\jhale\AppData\Local\Android\Sdk\platform-tools\;C:\Program Files\;C:\Program Files (x86)\;C:\Users\jhale\AppData\Local\Android\Sdk\tools\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files\Calibre2\;C:\Program Files (x86)\Vim\vim81\;C:\Program Files\nodejs\;C:\Users\jhale\AppData\Local\Microsoft\WindowsApps;C:\Users\jhale\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\jhale\AppData\Local\Programs\Git\cmd;C:\Users\jhale\.dotnet\tools;C:\Users\jhale\AppData\Roaming\npm13
9 verbose lifecycle @~start: CWD: C:\Users\jhale\AwesomeProject
10 silly lifecycle @~start: Args: [ '/d /s /c', 'expo start' ]
11 silly lifecycle @~start: Returned: code: 1  signal: null
12 info lifecycle @~start: Failed to exec start script
13 verbose stack Error: @ start: `expo start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd C:\Users\jhale\AwesomeProject
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ start: `expo start`
22 error Exit status 123 error Failed at the @ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by jinhale** [comment] 2019-10-16 20:11
The solution suggested on [StackOverflow](https://stackoverflow.com/questions/53456639/error-spawn-cmd-enoent-in-expo-init-project) works for me. This issue should be closed, but some documentation could help keep this from appearing again.

**Comment by brentvatne** [comment] 2019-12-08 01:28
@jinhale - do you know what the root cause of the problem is? I'd love to document this or perhaps even add some automated warning to expo-cli but I want to understand why adding the solution from stackoverflow fixes it, and why this only happens for some people

inlining the solution here:

> I solved my error using this. "%SystemRoot%\system32;" in the PATH variable.

**Comment by jinhale** [comment] 2019-12-10 12:49
> @jinhale - do you know what the root cause of the problem is? I'd love to document this or perhaps even add some automated warning to expo-cli but I want to understand why adding the solution from stackoverflow fixes it, and why this only happens for some people
> 
> inlining the solution here:
> 
> > I solved my error using this. "%SystemRoot%\system32;" in the PATH variable.

Sadly, I leave my workstation running for days at a time and my background is not in IT so tracing the problem would be difficult at best for me. My best _guess_ is that I deleted it from the path when I was removing Chocolatey stuff and hubris got the best of me. I was trying to do some periodic cleanup days or weeks before the incident and I vaguely remember removing what _looked_ like redundant variables. I suspect that I didn't notice this problem because I simply didn't restart until just before the error. 

My guess is that users are deleting it from path and thinking all is well because the error is only noticed until after either a full restart or after restarting a CLI.

**Comment by brentvatne** [comment] 2019-12-11 23:24
thanks a lot for the follow up @jinhale! i'll close this issue for now, if anyone else encounters it again please create a new issue and i'd love it if you can provide as much context as possible, keeping in mind that windows is not my area of expertise :)

**Closed** 2019-12-11 23:24 UTC
Labels: needs more info
