### ISSUE TITLE
Could not load expo Network response timed out

### ISSUE THREAD

**Issue by masoud-moghini** [expo/expo-cli#134] opened 2018-11-01 14:03 UTC
expo version 2.2.5
react-native-cli 2.0.1
react-native 0.55.4

by following guide that came in [react native formal guide](https://facebook.github.io/react-native/) I got the following error on my personal phone:

![screenshot_20181101-172108](https://user-images.githubusercontent.com/17137345/47856057-7f798400-ddfb-11e8-9897-3c3914be463d.jpg)
and here is my `ipconfig`
![capture](https://user-images.githubusercontent.com/17137345/47858549-9622d980-de01-11e8-8c44-57277e22f3a0.PNG)

googling lead to nothing and I just found [create react native app](https://github.com/react-community/create-react-native-app/issues/144)
but that didn't get me anything too.
does that relates to my country which is included in OFAC list (IRAN)?

**Comment by edzillion** [comment] 2018-11-01 20:04
Not sure this is relevant, but I had this same problem after updating to the expo-cli. Turned out it was a firewall issue.

**Comment by masoud-moghini** [comment] 2018-11-01 20:56
> Not sure this is relevant, but I had this same problem after updating to the expo-cli. Turned out it was a firewall issue.

thank for your reply ,I turned firewall totally off and the problem is ongoing.

**Comment by jbetancourt8** [comment] 2018-11-02 02:17
Same here. I updated the expo client and created a project using `expo init` but when I do `expo start`, I get this error in my terminal `Could not access packager status at http://127.0.0.1:19006/status. Are you sure the packager is running and reachable?`. I have turned off firewall and the problem is still ongoing.

**Comment by masoud-moghini** [comment] 2018-11-02 11:42
think its better to use react-native-cli rather than expo.

**Comment by jakubste** [comment] 2018-11-02 12:17
@masoud-moghini is your wifi connection marked as "private" in Windows settings? Are you sure your phone is in the same network?

**Comment by jbetancourt8** [comment] 2018-11-02 13:13
I am using a Mac but I am sure I am on the same network. I use Expo all the time to work on react native projects. This issue came up after I installed the latest Expo client on my computer.

**Comment by jakubste** [comment] 2018-11-02 13:16
@jbetancourt8 I believe you're experiencing totally different issue. Please describe it in a more elaborative way in another ticket.

**Comment by jbetancourt8** [comment] 2018-11-02 14:00
> @jbetancourt8 I believe you're experiencing totally different issue. Please describe it in a more elaborative way in another ticket.

Ok, will do.

**Comment by fson** [comment] 2018-12-04 01:48
The "Network response timed out" error means your phone can not connect to the Expo CLI running on your computer. Here are some things you can check:
- Is Expo CLI running? If not you can start it with `expo start`. Check that the URL matches the one shown in the Expo client app.
- Does the URL shown in the app point to the IP address or hostname of your computer?
- Is a firewall blocking access to this port (e.g. 19000) on your computer? If the firewall settings can't be changed, you might want to use the tunnel URL. Start Expo CLI with `expo start --tunnel` (or switch connection type in the sidebar of Expo Dev Tools).

**Comment by VladislavAnkudinov** [comment] 2019-01-03 15:36
Have same problem. I can access ip and port via browser, where I can see some JSON with application parameters. But I failed to get same JSON from mobile browser and Expo app is also failing off course.  My mobile phone connected to the same wifi network, which is private, firewall seem to be disabled (not sure, I am not devops or system administrator). I can see that this is very popular problem according to Google suggest... maybe there is simple solution, but I did not found it. Looks like this is not the best way to connect local dev server and mobile phone

**Comment by lawalstephen** [comment] 2019-02-03 16:11
I had a similar problem and I later realized virtual ports from virtual machine or virtual box causes the problem you can disable them to allow expo select the right connection and ip address to use. 
hope this helps

**Comment by FreelancerAnkit** [comment] 2019-02-11 10:07
This is generally occured when there is some **firewall or AntiVirus** running in your windows tray or ios.
Just disable that antivirus live protection everything will be ok.

**Comment by janhesters** [comment] 2019-02-14 14:38
Same issue here on mac and stuck. I can't figure out how to allow access to that port.

**Comment by MJ-DEV91** [comment] 2019-02-17 07:12
Please reopen the issue.

I installed node v10.15.1 and then I install expo-cli: "npm install -g expo-cli". Then I used "expo init" for creating a new project. I run the project with npm start. The expo was run successfully and expo developer tools was run in the browser.

I installed the expo client on my real android device and android studio simulator, bur when I click on "run on android/device emulator" or when I scan the QR barcode, the error message is appeared: "Could not load exp://192.168.43.188:19000. Network response timed out"

"192.168.43.188" is my correct IP and my laptop and my device are in a same network. When I go to "192.168.43.188:19000" in my browser (on android studio emulator and my real device), I can see the JSON response (it takes about 25 seconds). Also I can see 192.168.43.188:19002 as well. 

I turned off any firewalls too.

Where is the problem?

**Comment by MohibWasay** [comment] 2019-02-23 15:35
![image](https://user-images.githubusercontent.com/6129326/53288498-8c572480-37aa-11e9-89e5-6cefa8148eb1.png)

Ports are opened. But still not working

**Comment by garvitkhandelwal** [comment] 2019-03-28 22:11
Any solution to this issue?

**Comment by thanveershah** [comment] 2019-04-12 10:40
> Not sure this is relevant, but I had this same problem after updating to the expo-cli. Turned out it was a firewall issue.
> 
> edit: I also had to change my home network to be 'private' as for some reason it had designated it 'public' (on win 8.1)

WORKED !!!!

**Comment by avalanche1** [comment] 2019-05-05 21:26
Make REALLY sure that your devices are on the same network. I've struggled with this only to find out that my laptop was on another wifi hotspot ahem

**Comment by karol1990** [comment] 2019-05-08 20:57
The problem may be in network devices you have defined. Check if generated IP address comes from the right source, for example WIFI network cause it may come from DockerNAT / VirtualBox etc. Additionaly make sure your firewall is configured correctly.

**Comment by dougvobel** [comment] 2019-05-14 23:20
thanks @karol1990 
I turned off the docker and it worked correctly

**Comment by msaddam619** [comment] 2019-05-15 12:20
I was facing the same problem and solved it by method **below**

To view open port :
 sudo ufw status verbose
if you cannot found 19000 port open then you need to open port using :
 sudo ufw allow 19000/tcp
and then again run
 sudo ufw allow 19001/tcp

**Comment by ChiuMungZitAlexander** [comment] 2019-05-19 14:48
It is more about firewall.

I use mcafee. After I add the port from 19000 to 19002, I can load the App.

**Comment by airnayden** [comment] 2019-05-22 11:14
Had the same problem today. I could access the address from my desktop browser, but Expo returned error, when trying to launch the app on the mobile device. 

Solution: my PC is using Wireless connection, but I have also other network adapters enabled - VMWare, Ethernet, Npcap etc. I disabled everything but the WiFi, restarted expo and it returned the correct address.

**Comment by GlynL** [comment] 2019-06-13 01:32
I had the same issue, but not the same solution. After trying everything suggested, I unplugged our WiFi range-extender and now it's working. Not a great solution though.

**Comment by brixbimboavengoza** [comment] 2019-06-21 07:06
You just had to use the same wifi connection on your desktop and phone.

**Comment by fatihaslaan** [comment] 2019-07-02 17:57
i had the same problem, i solved it with closing hamachi. Hamachi changes your ip adress. So maybe one of your device is using another ip adress on same wifi.

**Comment by evanlesmez** [comment] 2019-07-09 19:08
If you are on ubuntu check your firewall status and make sure to either allow the expo port or disable the firewall (it is disabled by default). 
sudo ufw disbale 
https://linuxconfig.org/how-to-enable-disable-firewall-on-ubuntu-18-04-bionic-beaver-linux

**Comment by alemkhodadadi** [comment] 2019-07-13 09:41
i just tried all the ways suggested above but not successful. the solution i found is just type `expo logout`  at terminal if your logged in

**Comment by samayo** [comment] 2019-07-16 20:17
Same problem. Is there any alternative to this app?

**Comment by garvitkhandelwal** [comment] 2019-07-16 20:36
@samayo You can use react-native-cli as an alternative.

**Comment by samayo** [comment] 2019-07-16 20:41
I am not using react, I am using vue to build an android app and this library just doesn't work for me

**Comment by HelloWebs** [comment] 2019-08-06 22:46
The issue is with the firewall, but it not recommended to turn it off, like that's terrible advice.
For me, I was using VS Code integrated terminal to run Expo so the connection came from vs code which is block.  
Using Powershell instead fixed the issue for me.
So its worth trying

**Comment by VinayakNivalkar** [comment] 2019-08-07 17:21
For me it was the same problem but it arised after i installed virtual box 
So Might be my Solution will work **make Sure that no other network connection is active** 
For me it was **VirtualBox Host-Only-Network**
I disabled it and Expo started Working

Apology for bad English

**Comment by anavathe** [comment] 2019-08-15 00:57
> @samayo You can use react-native-cli as an alternative.

What are the steps to use react-native-cli as an alternative? 
npm install -g react-native-cli 
npm start

And then try to scan the QR code on Expo?

**Comment by Edweis** [comment] 2019-08-30 05:22
> Make REALLY sure that your devices are on the same network. I've struggled with this only to find out that my laptop was on another wifi hotspot ahem

Thanks ! worked for me :+1:

**Comment by tranhungasd** [comment] 2019-08-30 22:14
> Had the same problem today. I could access the address from my desktop browser, but Expo returned error, when trying to launch the app on the mobile device.
> 
> Solution: my PC is using Wireless connection, but I have also other network adapters enabled - VMWare, Ethernet, Npcap etc. I disabled everything but the WiFi, restarted expo and it returned the correct address.

Thank you very much, you save my day

**Comment by Qamarkh** [comment] 2019-09-02 13:09
> Had the same problem today. I could access the address from my desktop browser, but Expo returned error, when trying to launch the app on the mobile device.
> 
> Solution: my PC is using Wireless connection, but I have also other network adapters enabled - VMWare, Ethernet, **Npcap** etc. I disabled everything but the WiFi, restarted expo and it returned the correct address.

I had spent almost 2hrs and my solution is
1. I had installed WireShark to check http request response and by default it installed "Npcap".
I did uninstall of "Npcap" and without disabling firewall my app working smoothly from my andriod real device 
Thanks airnayden for your help.

**Comment by mccordgh** [comment] 2019-09-09 20:10
+1 for @avalanche1 's answer. My phone had randomly disconnected from my wifi and so it was actually not on the same network. OOF.

**Comment by Goinmul** [comment] 2019-09-10 05:50
I am using Windows 10 and an Android device.
I tried almost every given solutions:

1) check if I am using the same WiFi on PC and device
2) disabling firewall
3) running npm start on powershell
4) switching WiFi to private
5) re-install expo cli

But I still get the "Network response timed out" issue.

**Comment by MatheusSw** [comment] 2019-09-20 18:19
What I have found to fix this issue is:

1. Set your connection as private in Windows firewall
2. On the MetroBundler window that should have opened once npm start finished executing, look at the bottom left corner and change the connection from LAN to Tunnel, and notice the QR Code change, now on your phone simply scan it again with the Expo app

**Comment by sultanfendonus** [comment] 2019-09-25 05:45
In my case, I had Docker desktop client installed in my pc. I just uninstalled Docker from my pc and it's working! Maybe there was a better way than uninstall but I didn't need Docker so I uninstalled it

**Comment by igrik12** [comment] 2019-09-28 08:06
Same as **sultanfendonus** I had docker installed with vEthernet adapters enabled. Disabling all virtual adapters in adapter settings solved the problem. The network is still private with firewall enabled...

**Comment by SiSa68** [comment] 2019-10-01 12:39
I'm from IRAN
We can't run expo because of sanctions against Iran
For all who have problem same as me, you should run VPN or proxy on your computer (it is not necessary for phone)
I used SSTP VPN on my computer and also did all suggested above (change network to private, allow expo ports on firewall,...) and now it WORKS!!!

AND don't forget to check that expo LAN IP is set correctly as your networks IP (not your VPN ip)
You can change expo Lan IP by this command:
`set REACT_NATIVE_PACKAGER_HOSTNAME=your_ip_address`

**Comment by alemkhodadadi** [comment] 2019-10-04 18:20
@SiSa68  niyazi be vpn nist refiq. haminjuri addi ham kar mikone. faghat havaset bashe signIn nakarde bashi too terminal

**Comment by vieirapcm** [comment] 2019-10-05 05:26
> Had the same problem today. I could access the address from my desktop browser, but Expo returned error, when trying to launch the app on the mobile device.
> 
> Solution: my PC is using Wireless connection, but I have also other network adapters enabled - VMWare, Ethernet, Npcap etc. I disabled everything but the WiFi, restarted expo and it returned the correct address.

Same here. I disabled everything but the Wi-Fi and it worked correctly. Thanks for the help!

**Comment by marcosadsj** [comment] 2019-10-09 16:45
I just disabled the docker adapters and restarted expo!
![Sem título](https://user-images.githubusercontent.com/19555173/66501463-d7078180-ea99-11e9-83ee-e684feeb90d5.png)

**Comment by seriousManual** [comment] 2019-10-14 06:57
I also do have this problem, but everything listed here did not help.
My devices are in the same network, I can access all the three ports from the expo-cli from my phone (so there is a connection).

When I try to start the application on my phone, a little notification in the console ("Warning: This project contains unoptimized assets...") pops up, which means that the connection requests did go through all the way to the bundler, nonetheless it answers with "Something went wrong."

**Comment by MatheusSw** [comment] 2019-10-14 14:38
> I also do have this problem, but everything listed here did not help.
> My devices are in the same network, I can access all the three ports from the expo-cli from my phone (so there is a connection).
> 
> When I try to start the application on my phone, a little notification in the console ("Warning: This project contains unoptimized assets...") pops up, which means that the connection requests did go through all the way to the bundler, nonetheless it answers with "Something went wrong."
> 
> FWIW: the same thing happens when not loading from the networ, instead using the android emulator locally on my machine. (also using the "local" connection)

Have you tried switching to use tunnel connection?

**Comment by seriousManual** [comment] 2019-10-15 06:35
> Have you tried switching to use tunnel connection?
Yes, didn't work. (The connection is not the issue, the request goes all the way through to the bundler)

**Comment by ggavi2000** [comment] 2019-10-15 10:07
I can't run on the web either.
However, it runs on mobile and mobile emulators.

![12345](https://user-images.githubusercontent.com/33927558/66822289-e9445c80-ef7e-11e9-8877-1f220c9ff6c1.jpg)

**Comment by rafser01** [comment] 2019-10-22 16:48
I have experienced with the same issue. How i resolved it:

1. First make sure, mobile device and pc are on the same network. 
2. Check expo version. If expo version is outdated, update the version. (npm i -g expo-cli)

It should solve the issue.

**Comment by rdagger** [comment] 2019-10-23 05:57
I had the same problem.  Disabling my VPN fixed it.

**Comment by naxtor** [comment] 2019-11-26 01:02
> @masoud-moghini is your wifi connection marked as "private" in Windows settings? Are you sure your phone is in the same network?

Thank you ! this worked for me.

**Comment by egesamichael** [comment] 2019-12-05 00:15
> Not sure this is relevant, but I had this same problem after updating to the expo-cli. Turned out it was a firewall issue.
> 
> edit: I also had to change my home network to be 'private' as for some reason it had designated it 'public' (on win 8.1)

worked for me :)

**Comment by mrdj07** [comment] 2019-12-08 17:36
Or create a custom Firewall rule to allow connections on ports 19000 & 19001.

**Comment by webblufter** [comment] 2019-12-12 11:08
Your laptop/PC and mobile should be on same network.
I just face that issue and my mobile was not connected to my modem. As I switch my connection on mobile to same the same network of my PC it works.

**Comment by naytun** [comment] 2019-12-12 17:44
If you are on Mac, please check firewall setting in System Preference, and disable it.

**Comment by mert4545** [comment] 2020-01-27 21:35
For Android Device users, when localhost: xxx URL is opened just after typing expo start in command line, change "CONNECTION" from "LAN" to "Local". "CONNECTION" is located just above the QR Code at the left most below. Then, by using Expo Client App downloaded in your Android device, scan the given QR Code and you are good to go!

**Comment by MaxMacleod** [comment] 2020-01-29 12:12
Advice suggesting disabling of live protection, disabling firewalls and/or disabling antivirus seems imprudent.

Hopefully a better solution can be found.

**Comment by ritveak** [comment] 2020-01-30 04:57
I had the same error, then I tried having both my laptop and my phone in same network.
It worked!
Had it not, i would have followed this blog https://medium.com/@colin_78999/solving-network-response-timed-out-when-using-expo-on-windows-b486c22d5584

**Comment by isaacdarcilla** [comment] 2020-02-11 01:33
If you are on a linux box, you can solve it by using **ufw**

- `sudo apt install ufw`
- `sudo ufw disable`

**Comment by nesibeyyubov** [comment] 2020-02-12 06:05
> 2\. n the MetroBundler wind

Worked !! THANKS

**Comment by dons20** [comment] 2020-02-12 17:00
Solved by enabling allowing node.js through my firewall for the particular network type I was on (check to see if it's private, public or domain). Also there were two of them, so I enabled them both for my domain and it worked fine after.

**Comment by chrismclarke** [comment] 2020-02-18 10:40
I had a similar problem, the bundler appeared to be running on the right network (for me 192.168.0.8) but device would timeout on connect (checked was on same wifi). For me I think it was a problem with ethernet adapters and/or firewall walls, as the following 3 things all worked to fix the problem (without requiring any of the others)

- Disabling firewall for private network in Windows Firewall
- Disabling additional Ethernet adapters (culprit being vEthernet which had been enabled in a recent windows 10/docker update)
- Changing connection mode from `Lan` to `Local`

I'm pretty confused how all of these managed to fix the same issue, why I could connect on 'localhost' but not direct ip, and why the firewall appeared to behave differently when vEthernet adapter was enabled or not, but at least it's working for me.

**Comment by Silverkanade** [comment] 2020-02-20 14:04
I solved the issue with the following steps:
- Creating a package.json file
  - Running ```npm init``` in the folder outside where the project folder is
  - For the fields required to input, remember to put **app.js** as the entry point.
- Changing the connection from LAN to **tunnel** in the bottom-left corner of the expo browser tab

**Comment by pmerrill** [comment] 2020-02-28 00:21
For me it was that I wasn’t logged into my account in the Expo app that gets installed on the virtual Android device.

**Comment by nathsimpson** [comment] 2020-03-16 23:09
For me, I had to delete the `.expo` folder before running Yarn. It contains info about networking that could be out of date.

**Comment by Rafay3198** [comment] 2020-03-19 10:22
Just use `expo start --tunnel` command :)

**Comment by waqaramjad** [comment] 2020-03-19 10:23
> Just use `expo start --tunnel` command :)

but it's slow

**Comment by waqaramjad** [comment] 2020-03-19 10:23
facing same problem , no solutions works

**Comment by SamuelJacome** [comment] 2020-03-26 16:17
Routes the internet through your notebook to your cell phone. Here it worked. :)

**Comment by zalkegopal** [comment] 2020-03-28 13:56
> @masoud-moghini is your wifi connection marked as "private" in Windows settings? Are you sure your phone is in the same network

Connecting to same network solved my problem. thanks.

**Comment by SupreethBaliga** [comment] 2020-04-06 10:58
> I was facing the same problem and solved it by method **below**
> 
> To view open port :
> sudo ufw status verbose
> if you cannot found 19000 port open then you need to open port using :
> sudo ufw allow 19000/tcp
> and then again run
> sudo ufw allow 19001/tcp

Had the same issue. This solution worked perfectly to resolve it. Thanks.

**Comment by kerolesmonsef** [comment] 2020-04-06 19:12
> This is generally occured when there is some **firewall or AntiVirus** running in your windows tray or ios.
> Just disable that antivirus live protection everything will be ok.

yes it works for me

**Comment by MalteMagnussen** [comment] 2020-04-14 17:29
> The "Network response timed out" error means your phone can not connect to the Expo CLI running on your computer. Here are some things you can check:
> 
> * Is Expo CLI running? If not you can start it with `expo start`. Check that the URL matches the one shown in the Expo client app.
> * Does the URL shown in the app point to the IP address or hostname of your computer?
> * Is a firewall blocking access to this port (e.g. 19000) on your computer? If the firewall settings can't be changed, you might want to use the tunnel URL. Start Expo CLI with `expo start --tunnel` (or switch connection type in the sidebar of Expo Dev Tools).

My app is on port 19002 on my computer, but my phone tries 19000 when I use the QR code. How do I connect to 19002 on the phone?

**Comment by VishwanathDalawai** [comment] 2020-04-20 11:34
Expo and react-devtools conflict. If you were using react-devtools, you must uninstall it:
stop the app
_npm uninstall react-devtools --global_
Rerun the app using _expo start_
Tunnel connection: Excess the App online 
LAN: Connecting via USB
Local: If devices are connected using same network

**Comment by kmturley** [comment] 2020-04-20 23:05
It seems strange you would pick a non-standard web port like 19000. Why not use ports in the normal range 3000 or 8000? Do you expect every developer to manually open their firewall ports?

You have hardcoded the ports and not allow them to be configured:
https://github.com/expo/expo-cli/blob/548ac8b32eac86529ff1a4e755e1fa5f47c1ff0e/packages/xdl/src/Project.ts#L2082

I can't change the firewall rules on my laptop due to Admin restrictions...

**Comment by gbanc** [comment] 2020-04-24 22:43
On Windows - friendly reminder to try setting static IP / restart your router:
Could not connect to expo via LAN, but i could via tunnel. Even though tunnel works - axios would not connect to my local API. 

I also couldnt connect to local dev server in Safari. 

I tried every possible solution from every thread, but not one mentioned IP address conflict. Tried `ipconfig /renew /release /flushdns`, setting static IP, and restart router. Now i can connnect to local dev server in Safari, as well as use Expo LAN connection.

**Comment by gbhipolitoglyph** [comment] 2020-04-27 03:15
> Not sure this is relevant, but I had this same problem after updating to the expo-cli. Turned out it was a firewall issue.
> 
> edit: I also had to change my home network to be 'private' as for some reason it had designated it 'public' (on win 8.1)

thanks. Also a firewall issue on my side using Ubuntu. Followed the instructions [here](https://www.cyberciti.biz/faq/how-to-open-firewall-port-on-ubuntu-linux-12-04-14-04-lts/) to allow incoming on ports 19000 and 19001.
In summary, used `sudo ufw status verbose` to check firewall status
and used `sudo ufw allow 19000` and `sudo ufw allow 19001` to allow **tcp & udp** on the ports. Resolved the issue.
P.S. didn't try if opening only **tcp** e.g. `sudo ufw allow 19000/tcp` is already enough.

**Comment by satty82** [comment] 2020-04-29 16:20
You need to disable firewall and in my case I used my own device hotspot to cannot to internet(means both running on same network)
Then it worked just fine .

**Comment by Krishatom** [comment] 2020-04-30 14:59
> @masoud-moghini is your wifi connection marked as "private" in Windows settings? Are you sure your phone is in the same network?

Thanks...worked for me :)

**Comment by BoomBooA** [comment] 2020-05-04 08:15
I was debug expo application on OnePlus.
Finally i found the android system disabled the wlan network for expo😂

**Comment by erikvinicius5** [comment] 2020-05-12 01:09
It seems it stoped working for me after I updated my mac to Catalina.
Not sure this is a good solution but what worked for me was:
1- Security & Privacy in system preferences;
2- Developer tools in Privacy tab;
3- Enable terminal.
Then I ran expo start again and it worked. After that I went back there and unchecked the option.

**Comment by Seanmclem** [comment] 2020-05-21 18:46
Fix for me on Windows 10:
I was already on the same wifi for both devices, network was already public. 
I didn't change my firewall for public or Domain, or any antivirus settings. 
All I had to change was Public Firewall, set to off. I never use public wifi on my laptop anyway.
That fixed it, now it works.

**Comment by goxr3plus** [comment] 2020-05-25 09:04
Yesterday it was working perfectly on LAN , today i opened the computer and it doesn't work , this is madness . Here tunnel we come again ..... 25 seconds to load the app .

**Comment by brunogirin** [comment] 2020-06-03 11:14
Adding some extra info in case someone else comes across the same problem. My issue stemmed from the fact that the [Expo CLI Quickstart](https://reactnative.dev/docs/environment-setup) says:

```
expo init AwesomeProject

cd AwesomeProject
npm start # you can also use: expo start
```

This suggests that `npm start` and `expo start` are equivalent. However, the minimal template used by `expo init` configures `package.json` in such a way that `npm start` is equivalent to `react-native start` instead of `expo start`. Replacing `react-native start` with `expo start` in `package.json` fixed the issue.

**Comment by kibbyd** [comment] 2020-06-03 15:02
Where it says connection type [TUNNEL] [LAN] [LOCAL] click LOCAL button

**Comment by arthurborgesdev** [comment] 2020-06-04 19:56
I'm using WSL2 and using Wifi on both the laptop and the smartphone. After I set the environment variable to change the IP, they are both on the same network. But now I figured out that I have to change or disable the firewall. How to do that as firewall in WSL is currently disabled?

**Comment by Alien0525** [comment] 2020-06-27 08:06
> Not sure this is relevant, but I had this same problem after updating to the expo-cli. Turned out it was a firewall issue.
> 
> edit: I also had to change my home network to be 'private' as for some reason it had designated it 'public' (on win 8.1)

Worked!! Thanks

**Comment by goxr3plus** [comment] 2020-06-29 08:14
Well in order local to work in Windows 10 i added the following on the hosts file :

127.0.0.1  localhost

No more tunnels :) blazing fast.

**Comment by aroblesgalit** [comment] 2020-07-24 03:47
> The "Network response timed out" error means your phone can not connect to the Expo CLI running on your computer. Here are some things you can check:
> 
> * Is Expo CLI running? If not you can start it with `expo start`. Check that the URL matches the one shown in the Expo client app.
> * Does the URL shown in the app point to the IP address or hostname of your computer?
> * Is a firewall blocking access to this port (e.g. 19000) on your computer? If the firewall settings can't be changed, you might want to use the tunnel URL. Start Expo CLI with `expo start --tunnel` (or switch connection type in the sidebar of Expo Dev Tools).

Is there a difference with just switching to Tunnel vs LAN? Tunnel seems to work just fine for me after failing to make it work on LAN.

**Comment by goxr3plus** [comment] 2020-07-24 15:41
Tunnel is extremely slow , please check my answer :)

**Comment by aroblesgalit** [comment] 2020-07-24 16:02
> Tunnel is extremely slow , please check my answer :)

Thanks for your response! Yeah for some reason, Tunnel wasn't getting the changes/updates. And then I tried LAN again cuz Tunnel stopped working for me, and LAN worked just fine. I have no idea why. LAN is definitely the way to go as long as you can get it to work.

**Comment by jaykiran** [comment] 2020-07-25 10:10
> You just had to use the same wifi connection on your desktop and phone.

WORKED!.. Thanks

**Comment by pratyaksh123** [comment] 2020-08-04 10:44
Struggling with this error from the past few days, it's way better to use react native CLI than expo.

**Comment by kvt0012** [comment] 2020-08-08 03:39
> Not sure this is relevant, but I had this same problem after updating to the expo-cli. Turned out it was a firewall issue.
> 
> edit: I also had to change my home network to be 'private' as for some reason it had designated it 'public' (on win 8.1)

old but gold, thanks for your solution.

**Comment by aricsangchat** [comment] 2020-08-21 07:16
Here was a solution for me on Windows 10. I just had to allow the port through the firewall. Used these instructions, https://community.spiceworks.com/how_to/159244-block-or-allow-tcp-ip-port-in-windows-firewall

**Comment by WillenOLeal** [comment] 2020-09-02 20:12
Hey guys for anyone using VirtualBox, simply change the network configuration from "NAT" to "Bridged." This ensures that your phone and the virtual machine are on the same LAN. Cheers!

**Comment by aarvil** [comment] 2020-10-15 01:33
This is almost certainly a network issue. As discussed above, be on same network, review firewall rules. If you're running on Windows Subsystem for Linux version 2, then know that network is set to internal by default. Go to Hyper-V Manager > Virtual Switch Manager, select the WSL network and switch to External network and map to your default LAN connection.

**Comment by JohnnyCarreiro** [comment] 2020-10-16 01:01
Hey there, 
For mac users
I have fixed this issue enabling node script on the firewall and adding Exponent-2.16.0.tar.app, click to add more applications on the firewall in your root user type command + shift + period (.), it'll show the occult files, fined .expo folder and add  Exponent...

<img width="592" alt="Screen Shot 2020-10-15 at 21 48 24" src="https://user-images.githubusercontent.com/67814602/96201053-e6819c00-0f31-11eb-9e07-a1d48ac8cd32.png">
<img width="592" alt="Screen Shot 2020-10-15 at 21 55 52" src="https://user-images.githubusercontent.com/67814602/96201059-e8e3f600-0f31-11eb-9045-51da2b3fabbc.png">
It works fine for me

**Comment by suryachandrakumar987** [comment] 2020-10-17 06:19
I also had this problem i solved it easily simply connect you'r phone to the internet which you use for you't pc this solved my problem

**Comment by brentvatne** [comment] 2020-10-23 22:38
lots of good, helpful comments recently in this thread and i don't want them to get buried so i'm going to close and lock this issue so they stick around in a prominent position

**Closed by brentvatne** 2020-10-23 22:38 UTC
