### ISSUE TITLE
Latest (--latest) not applied by default for upload:android

### ISSUE THREAD

**Issue by brookemitchell** [expo/expo-cli#2187] opened 2020-05-27 03:26 UTC
This one should be a quick fix I can PR for later today when I get the chance. A minor inconvenience but I was trying out `expo upload:android --use-submission-service` on Linux (very cool!) and found the `--latest` default argument wasn't applied by default

Instead, I was presented with the ` What would you like to submit? (Use arrow keys)
❯ I have a URL to the app archive ...` menu when using `expo upload:android --use-submission-service`

## Reproducible Demo
run `expo upload:android --help` see that --latest is a default argument
run `expo upload:android --use-submission-service` see that --latest isn't applied by default

**Comment by brentvatne** [comment] 2020-07-16 23:03
this appears to be resolved, i just tried it on my machine :) probably previously by @dsokal 

let me know if the issue is still happening for you.

**Comment by dsokal** [comment] 2020-07-17 07:27
Actually, we decided to change that behavior so the `--latest` option is not applied by default.
We just forgot to change the help output.

**Comment by dsokal** [comment] 2020-07-17 07:31
Fixed in https://github.com/expo/expo-cli/commit/45cc5f853a7ba5375470fda3e5cd17522ef22a8c

**Closed by dsokal** 2020-07-17 07:31 UTC
Labels: enhancement

**Comment by brentvatne** [comment] 2020-07-17 17:43
oh my bad i misread the issue, thanks for following up @dsokal

**Comment by brookemitchell** [comment] 2020-07-19 10:40
Thanks for the help output update @dsokal !
