### ISSUE TITLE
expo build:android hangs indefinitely

### ISSUE THREAD

**Issue by Iffabled** [expo/expo-cli#428] opened 2019-03-17 09:49 UTC
## Description

When trying to build an app for Android expo hangs indefinitely on `Building iOS bundle`.

## Expected Behavior

After executing `expo build:android` an app should be build.

## Observed Behavior

Expo hangs indefinitely on `Building iOS bundle`.

## Environment

```
Expo CLI 2.11.9 environment info:
    System:
      OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
      Shell: 4.4.19 - /bin/bash
    Binaries:
      Node: 10.15.3 - /usr/bin/node
      npm: 6.9.0 - /usr/bin/npm
    npmPackages:
      expo: ^32.0.0 => 32.0.6
      react: 16.5.0 => 16.5.0
      react-native: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz => 0.57.1
      react-navigation: ^3.0.9 => 3.4.0
    npmGlobalPackages:
      expo-cli: 2.11.9

```

## Reproducible Demo

1. Create a new app using expo.
2. Try to build it using `expo build:android`.

**Comment by aiham** [comment] 2019-07-10 13:00
Possible duplicate of #278

**Closed** 2019-12-08 01:24 UTC
Labels: expo build
