### ISSUE TITLE
Error while updating expo-cli to latest version

### ISSUE THREAD

**Issue by arnavozil** [expo/expo-cli#1245] opened 2019-11-19 16:48 UTC
# READ THIS FIRST, PLEASE!

We're looking to keep questions on our forums and bug reports on the GitHub repo -- please choose whichever you feel is more appropriate for your issue:

- For questions and help using Expo CLI, post in our community forums (log in with your Expo developer account): https://forums.expo.io/c/expo-cli
- File a bug on the Expo CLI repo (for bugs related to the Expo CLI tools): https://github.com/expo/expo-cli/issues/new
- File a bug on the main Expo repo (for other bugs): https://github.com/expo/expo/issues/new
- Request a feature on Canny: https://expo.canny.io/feature-requests

Thanks for reporting the issue you found with Expo CLI!

# Required format for issues

Please make our job easier by filling this template out to completion.

## Description

Error while updating expo-cli to latest version

## Expected Behavior

I was trying to update expo-cli to version 3.7.1 using npm install -g expo-cli, instead of updating, the command line produced an unexpected error.

## Observed Behavior

What actually happened when you performed the above actions?

If there's an error message, please paste the _full terminal output and error message_ in this code block:

```
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modu
les\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\
nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\kuldeep\AppData\Roaming\npm\node_modules\expo-cli\node_mod
ules\dtrace-provider
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
info looking for cached prebuild @ C:\Users\kuldeep\AppData\Roaming\npm-cache\_p
rebuilds\89bf70-iltorb-v2.4.4-node-v79-win32-x64.tar.gz
info found cached prebuild
info unpacking @ C:\Users\kuldeep\AppData\Roaming\npm-cache\_prebuilds\89bf70-il
torb-v2.4.4-node-v79-win32-x64.tar.gz
info unpack resolved to C:\Users\kuldeep\AppData\Roaming\npm\node_modules\expo-c
li\node_modules\iltorb\build\bindings\iltorb.node
info unpack required C:\Users\kuldeep\AppData\Roaming\npm\node_modules\expo-cli\
node_modules\iltorb\build\bindings\iltorb.node successfully
info install Successfully installed iltorb binary!
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://github.com/libxmljs/libxmljs/releases/download/v0.
19.7/node-v79-win32-x64.tar.gz
node-pre-gyp http 404 https://github.com/libxmljs/libxmljs/releases/download/v0.
19.7/node-v79-win32-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/libxmljs/libxmljs/r
eleases/download/v0.19.7/node-v79-win32-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for libxmljs@0.19.7 and node@13.1
.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/libxmlj
s/libxmljs/releases/download/v0.19.7/node-v79-win32-x64.tar.gz
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modu
les\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\
nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--f
allback-to-build" "--loglevel=http" "--module=C:\\Users\\kuldeep\\AppData\\Roami
ng\\npm\\node_modules\\expo-cli\\node_modules\\libxmljs\\build\\Release\\xmljs.n
ode" "--module_name=xmljs" "--module_path=C:\\Users\\kuldeep\\AppData\\Roaming\\
npm\\node_modules\\expo-cli\\node_modules\\libxmljs\\build\\Release" "--napi_ver
sion=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-
v79"
gyp ERR! cwd C:\Users\kuldeep\AppData\Roaming\npm\node_modules\expo-cli\node_mod
ules\libxmljs
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.j
s configure --fallback-to-build --loglevel=http --module=C:\Users\kuldeep\AppDat
a\Roaming\npm\node_modules\expo-cli\node_modules\libxmljs\build\Release\xmljs.no
de --module_name=xmljs --module_path=C:\Users\kuldeep\AppData\Roaming\npm\node_m
odules\expo-cli\node_modules\libxmljs\build\Release --napi_version=5 --node_abi_
napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\kuldeep\AppDat
a\Roaming\npm\node_modules\expo-cli\node_modules\node-pre-gyp\lib\util\compile.j
s:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kuld
eep\\AppData\\Roaming\\npm\\node_modules\\expo-cli\\node_modules\\node-pre-gyp\\
bin\\node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
node-pre-gyp ERR! cwd C:\Users\kuldeep\AppData\Roaming\npm\node_modules\expo-cli
\node_modules\libxmljs
node-pre-gyp ERR! node -v v13.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libxmljs@0.19.7 install: `node-pre-gyp install --fallback-to-build --lo
glevel http`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libxmljs@0.19.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kuldeep\AppData\Roaming\npm-cache\_logs\2019-11-19T16_36_3
0_088Z-debug.log
Installing Expo CLI failed. You can install it manually with:
  npm install --global expo-cli
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kuldeep\AppData\Roaming\npm-cache\_logs\2019-11-19T16_36_3
0_213Z-debug.log

```

## Environment

Please run `expo diagnostics` in the project folder and copy the output here:

Also specify:

- Phone/emulator/simulator platform, model and version:

## Reproducible Demo

Please provide a minimized reproducible demonstration of the problem you're reporting.

Issues that come with minimal repro's are resolved much more quickly than issues where a maintainer has to reproduce themselves.

**Comment by GollyJer** [comment] 2019-11-19 19:23
Same.
https://forums.expo.io/t/expo-cli-doesnt-work-for-me/30163/5?u=gollyjer

**Comment by wodin** [comment] 2019-11-20 05:14
Since this is not mentioned elsewhere in this thread, the problem is happening on Windows.

There are binaries of libxmljs for Mac and Linux for `node v72`, but not for Windows:
<img width="428" alt="image" src="https://user-images.githubusercontent.com/4579020/69210861-e1bb3900-0b64-11ea-8dad-442961c87470.png">

**Comment by fson** [comment] 2019-11-20 11:51
This is a duplicate of https://github.com/expo/expo-cli/issues/1237, so I'm closing this one in favor of #1237.

**Closed by fson** 2019-11-20 11:51 UTC
